### ISSUE TITLE
Default value?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#10]
<a href="https://github.com/ekkis"><img src="https://avatars3.githubusercontent.com/u/274980?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekkis](https://github.com/ekkis)**
_Monday Sep 16, 2013 at 21:49 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/100_

----

I've defined an option like this:

[Option('s', HelpText = "Save name", DefaultValue="Main")]
public string SaveName { get; set; }

but when I run my programme as:

c:> test ./file-to-munch.txt -s

I get a failure of ParseArgumentsStrict.  what have I done wrong?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Sep 16, 2013 at 22:05 GMT_

----

I forget CommandLine's behavior, but what happens if you put the `-s` before the positional argument? (also, you _have_ defined another option to consume `./file-to-munch.txt`, right?)

**Comment by ericnewton76** [comment]
<a href="https://github.com/ekkis"><img src="https://avatars3.githubusercontent.com/u/274980?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekkis](https://github.com/ekkis)**
_Monday Sep 16, 2013 at 22:25 GMT_

----

but I would imagine that

c:> test -s ./file-to-munch.txt

would cause the -s parameter to gobble the filename as an argument, which is not what's intended... which brings up the question, in unix one can use -- to end the options field, so that would allow me to write:

c:> test -s -- ./file-to-munch.txt

and that would mean: 1) specify a -s with the default value, and 2) pass an unbound parameter with value ./file-to-munch.txt

is there support for that syntax here?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Sep 16, 2013 at 23:17 GMT_

----

It [does](https://github.com/gsscoder/commandline/issues/31). Or at least it should. I haven't tried it out.

**Comment by moh-hassan** [comment]
Resolved
Unbound parameters are used as ValueAttributes
