### ISSUE TITLE
All unknown arguments are ignored despite IgnoreUnknownArguments being false

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#100]
<a href="https://github.com/cannontrodder"><img src="https://avatars2.githubusercontent.com/u/6507976?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cannontrodder](https://github.com/cannontrodder)**
_Wednesday Dec 07, 2016 at 14:29 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/385_

----

In this repro pulled from my unit tests, I am checking that parsing fails when the full option 'source' is used but with a single '-' character. This actually parses:

![image](https://cloud.githubusercontent.com/assets/6507976/20971431/517a8fa8-bc89-11e6-9cb1-6b20316a2de9.png)

I understand why "ource" is parsed as the value for "Source" in my options class - because I am using the short switch name by using one '-' character. In my opinion that makes 'sourcepath' and 'thisshouldnotbehere' unknown arguments, and I'd expect parsing to fail.

Is this expected behaviour?

```c#
void Main()
{
	var commandLine = "validate thisshouldnotbehere -source sourcepath thisshouldnotbehere";
	
	var args = commandLine.Split(' ');

	var parser = new Parser(with =>
	{
		with.CaseSensitive = false;
		with.HelpWriter = Console.Out;
		with.IgnoreUnknownArguments = false;
	});

	var result = parser.ParseArguments<CommandLineOptionsValidateOptions>(args);

	if (result.Tag == ParserResultType.NotParsed)
		throw new Exception("Unable to parse command line.");

	var parsedValue = ((Parsed<CommandLineOptionsValidateOptions>)result).Value;
}

[Verb("validate")]
public class CommandLineOptionsValidateOptions 
{
	[Option('s', "Source", Required = true)]
	public string Source { get; set; }

	[Option('m', "MultiDatabase")]
	public bool MultiDatabase { get; set; }

	[Option('d', "Database", Required = false)]
	public string DatabaseName { get; set; }
}

```

**Comment by ericnewton76** [comment]
<a href="https://github.com/dbjorge"><img src="https://avatars2.githubusercontent.com/u/376284?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dbjorge](https://github.com/dbjorge)**
_Monday May 01, 2017 at 23:18 GMT_

----

:+1:, if a user specifies positional values against an options class with no [Value] members and IgnoreUnknownArguments = false, I'd expect it to be an error.

**Comment by moh-hassan** [comment]
IgnoreUnknownArguments  is working fine in v2.x

**Comment by capslock66** [comment]
I have the same problem with 2.8 version :
My class for a verb don't specify any [value] properties, only [option]
If the user gives some values, the  IgnoreUnknownArguments don't generate error.

**Comment by moh-hassan** [comment]
@capslock66 
 IgnoreUnknownArguments  support only options and their values. Values only without no corresponding Value property is bypassed without firing error.
This is may be valuable when you need only to pass through options to a third party application like Unity Engine and you can't to capture it and re-send it to the third party application.
Have a look to this [discussion](https://github.com/commandlineparser/commandline/issues/620).

**Comment by poizan42** [comment]
It may be valuable in some cases where you don't have complete control over your command line. But it's definitely the opposite of valueable for the ususal case.

Consider that if you have a default verb then any misspelling of a verb ends up as an ignored value to the default verb instead of generating an error.
