### ISSUE TITLE
Parsing via reflection and executing a named method 

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#103]
<a href="https://github.com/navron"><img src="https://avatars2.githubusercontent.com/u/7018189?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [navron](https://github.com/navron)**
_Tuesday Jan 10, 2017 at 03:36 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/393_

----

I would like to be able to parse a large number of verb commands within an assembly and execute a default method in a single line of code

example:
```Parser.Default.ParseArguments(args, Assembly.GetExecutingAssembly(), "Run");```

This would be similar to 
```
  // Get all classes with command line Verb Attribute
  var verbTypes = (from type in Assembly.GetExecutingAssembly().GetTypes()
                             let testAttribute = Attribute.GetCustomAttribute(type, typeof(VerbAttribute))
                             where testAttribute != null
                             select type);
 // Parser the command line
 var results = Parser.Default.ParseArguments(args, verbTypes.ToArray());

results.WithParsed<VerbA>(action => action.Run()) 
           .WithParsed<VerbB>(action => action.Run())
           .WithParsed<VerbC>(action => action.Run());
```
In one console program I have 26 Verbs, mostly test actions. 

The only problem I couldn't work out is how to run an action on the results without having to Parse with a Type. Of course, there should be checks that the method exists, and possibly an execution flag in the ParsedResults class to indicate the method has ben run.

**Comment by moh-hassan** [comment]
See [wiki](https://github.com/commandlineparser/commandline/wiki/Verbs)
