### ISSUE TITLE
AddEnumValuesToHelpText does not work for nullable enums

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#104]
<a href="https://github.com/peetw"><img src="https://avatars2.githubusercontent.com/u/1334162?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peetw](https://github.com/peetw)**
_Thursday Jan 12, 2017 at 08:45 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/395_

----

When outputting HelpText, the following code will correctly list valid values for enum type options. However, if the option is a nullable enum type, then it will not list the valid values.

    parserResult.WithNotParsed(errors =>
    {
        // Use custom help text to ensure valid enum values are displayed
        var helpText = HelpText.AutoBuild(parserResult);
        helpText.AddEnumValuesToHelpText = true;
        helpText.AddOptions(parserResult);
        Console.Error.Write(helpText);
        Environment.Exit(1);
    });

Is this a bug, or is there another setting/workaround for nullable enums?

**Comment by dybalabj** [comment]
I'm having the same issue.  Are there any plans to address this?

**Comment by moh-hassan** [comment]
Can you try the nuget package  in Appveyor ci for test [CommandLineParser.2.6.0-93-Dev.nupkg](https://ci.appveyor.com/api/buildjobs/7yphew6novsbvjfq/artifacts/src%2FCommandLine%2Fbin%2FRelease%2FCommandLineParser.2.6.0-93-Dev.nupkg)
