### ISSUE TITLE
Missing ValueList attribute

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#11]
<a href="https://github.com/ekkis"><img src="https://avatars3.githubusercontent.com/u/274980?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekkis](https://github.com/ekkis)**
_Monday Sep 16, 2013 at 22:07 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/101_

----

to help me with other issues I posted, I decided to pull in the whole project into my solution.  upon compilation I get the error that ValueListAttribute cannot be found.  indeed it's not there... I don't see another project I should also add... what next?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Sep 16, 2013 at 22:20 GMT_

----

Looks like it's now called [ValueAttribute](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/ValueAttribute.cs#L11) which can specify a specific range of arguments to consume.

**Comment by ericnewton76** [comment]
<a href="https://github.com/ekkis"><img src="https://avatars3.githubusercontent.com/u/274980?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekkis](https://github.com/ekkis)**
_Monday Sep 16, 2013 at 22:30 GMT_

----

I don't think so.  looking at its definition I see there's only one constructor requiring an int

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Sep 16, 2013 at 23:14 GMT_

----

That's so that you can order multiple ValueAttributes. I think the equivalent to the old ValueList would be `[Value(0)]`. With no min and no max, you can provide between 0 and Inf extra values.

**Comment by wilbit** [comment]
I've just migrated my project from version 1.9.71 to 2.3.0.
The replacement `[ValueList(typeof(List<string>))]` => `[Value(2, MetaName = "files", Required = false)]` works for me pretty well. I used **2** because I have 3 positional parameters (src, dest & wildcards).

I believe maintainers may close this ticket.
