### ISSUE TITLE
Duplicate errors list at some circumstances

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#110]
<a href="https://github.com/zii-dmg"><img src="https://avatars2.githubusercontent.com/u/2846896?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zii-dmg](https://github.com/zii-dmg)**
_Friday Jan 20, 2017 at 16:33 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/409_

----

Pass no arguments, use verbs, have no CopyrightAttribute and no AssemblyCompanyAttribute on assembly. Result is help text with duplicate errors list:
```
Tests2 1.0.0.0
Copyright (C) 1 author
ERROR(S):
No verb selected.
ERROR(S):
No verb selected.
```

Reasons:
[HelpText.cs, line 229, first errors list](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Text/HelpText.cs#L229),
[HelpText.cs, line 239, second errors list](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Text/HelpText.cs#L239).

First is appearing because `CopyrightInfo.Default` throwing exception because no assembly attributes.
Second is appearing because we have `NoVerbSelectedError`.

Also strange that default copyright have author `"author"` and year `1` when no attributes. Maybe  copyright should be empty and not written to console.

**Comment by moh-hassan** [comment]
CopyrightInfo.Default (in CopyrightInfo.cs) fires an exception :

>InvalidOperationException("CopyrightInfo::Default requires that you define AssemblyCopyrightAttribute or AssemblyCompanyAttribute.")

HelpText  swallow this exception and hide it from the user and duplicate the error message twice  as given below:

>Copyright (C) 1 author
ERROR(S):
Required option 'r, read' is missing.
ERROR(S):
Required option 'r, read' is missing. 
.... rest of help ....
		
It's nice to show this exception within ERROR(S)  to help fixing this error.
This help user to fill these assembly attributes in AssemplyInfo.cs:

		[assembly: AssemblyCompany("Company xyz")] 	
		[assembly: AssemblyCopyright("Copyright ©  2018 Company xyz")]  

Filling these assembly attributes stop duplication of ERROR(S)
