### ISSUE TITLE
How to implement an option whose value is optional?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#114]
<a href="https://github.com/EmmaZhu"><img src="https://avatars2.githubusercontent.com/u/6396650?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EmmaZhu](https://github.com/EmmaZhu)**
_Thursday Mar 02, 2017 at 03:55 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/418_

----

Is there any way to implement an option (let's say with name "option1") that it works like:
1. --option1 value1, means to set it to "value1"
2. --option1, means it's set without a value

Our application is a long running one that we'd like to persist a running checkpoint on disk if user wants to. If user indicates a file path, we write the checkpoint to it; If user just indicate the option to persist the checkpoint but doesn't specify a path, we write the checkpoint to the default path.

Is there any way we can do this?

Thanks
Emma

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Friday Mar 03, 2017 at 16:10 GMT_

----

Hi @EmmaZhu unfortunately this library doesn't support "value optional" parameters. By setting a `Default` value (like below) it will only be set when `--option1` is _missing_. This is a good idea for a feature, though.

    public class Options
    {
        [Option("option1", Default="value1")]
        public string MyOption { get; set; }
    }

Here are a few alternative approaches that come to mind:
1. Some applications like wget use a `-` as a sigil indicating to take the input [from somewhere else](http://stackoverflow.com/questions/13478857/wget-read-input-from-standard-input). You could use the same to indicate the default value.
2. Two separate options (`--option1` and `--option1default`)

**Comment by moh-hassan** [comment]
Option should have a value othewise parser raise error "missing value". 
If the option has a default value, it can be dropped from the commandline and parser set its value to the default.

**Comment by moh-hassan** [comment]
close for age.
