### ISSUE TITLE
Mark attributes with ReSharper annotations to help code analysis

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#118]
<a href="https://github.com/imanushin"><img src="https://avatars2.githubusercontent.com/u/4425474?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [imanushin](https://github.com/imanushin)**
_Sunday Mar 19, 2017 at 14:12 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/422_

----

[ReSharper](https://www.jetbrains.com/resharper/) has unused methods/properties highlighting to understand, what code can be removed safely.
CommandLine library uses reflection for code invokation, so ReSharper is unable to lookup the calls. 
See below screenshot from Visual Studio ([I used this file from opensource project](https://github.com/Litee/SolutionCop/blob/master/src/SolutionCop.CommandLine/CommandLineParameters.cs))

![image](https://cloud.githubusercontent.com/assets/4425474/24081554/240b334a-0cc7-11e7-9d13-b22257fcdb7e.png)

**Comment by moh-hassan** [comment]
Vs 2017 support code analysis for unused code.
