### ISSUE TITLE
When using ValueOptionAttributes, setting a property as Required always fails

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#12]
<a href="https://github.com/wags1999"><img src="https://avatars1.githubusercontent.com/u/5712472?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wags1999](https://github.com/wags1999)**
_Thursday Oct 17, 2013 at 19:14 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/104_

----

In version 1.9.71.2, when using ValueOptionAttributes to define order-specific parameters (I'm using this for backwards compatibility), if I set any properties as Required, the parsing thinks it fails.  This is because in OptionMap.cs, in EnforceRequiredRule, the option.IsDefined has never been set in the Parser.DoParseArgumentsCore() and subsequent valueMapper.MapValueItem() methods.

**Comment by moh-hassan** [comment]
Working in v2.x
