### ISSUE TITLE
Add support for multicharacter short option

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#124]
<a href="https://github.com/alexxn"><img src="https://avatars1.githubusercontent.com/u/5682814?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexxn](https://github.com/alexxn)**
_Monday Mar 27, 2017 at 16:20 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/431_

----

Sometime it is usefull to have not only single char short option like` [Option('d', "download-file")]` but something like `[Option('gf', "graph-file")]`.

This is not a common approach, but might be needed for compatibility of command line parameters with other products.

**Comment by ericnewton76** [comment]
<a href="https://github.com/XenHat"><img src="https://avatars3.githubusercontent.com/u/980408?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [XenHat](https://github.com/XenHat)**
_Monday Mar 27, 2017 at 20:39 GMT_

----

I'm in favor of this as well. Just a side note though, it would probably be more like `[Option("gf", "graph-file")]` as C-like languages use single quotes for the `char` type which can only take one character unless an array is used.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Mar 27, 2017 at 21:56 GMT_

----

This is not going to happen with short options - short options must be a single character only. This conforms to the standard UNIX getopt format. commandline also allows bundling of short options so `-gf` is functionally equivalent to `-g -f`. What are your thoughts on an alias for long options (so `--graph-file` and `--gf` are equivalent)?

Example of short arg bundling:

```csharp
void Main()
{
	Parser.Default.ParseArguments<Options>("-lgn Arnold".Split())
	.WithParsed(o => o.Dump())
	.WithNotParsed(e => e.Dump());
}

public class Options
{
	[Option('l', "logging")]
	public bool Logging { get; set; }

	[Option('g', "graphics")]
	public bool Graphics { get; set; }

	[Option('r', "realtime")]
	public bool Realtime { get; set; }

	[Option('n', "name")]
	public string Name { get; set; }
}
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/alexxn"><img src="https://avatars1.githubusercontent.com/u/5682814?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alexxn](https://github.com/alexxn)**
_Monday Mar 27, 2017 at 22:00 GMT_

----

  Aliases is also a very handy feature.

**Comment by ericnewton76** [comment]
<a href="https://github.com/XenHat"><img src="https://avatars3.githubusercontent.com/u/980408?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [XenHat](https://github.com/XenHat)**
_Tuesday Mar 28, 2017 at 09:28 GMT_

----

Alias would be handy, indeed. it would simplify backward-compatibility for me.

**Comment by sun2sirius** [comment]
With one-character options ParseArguments throws an exception "Long name should be longest than one character". Why is there a limitation? I really need single-character options - why is it not supported?

**Comment by o4zloiroman** [comment]
Please implement something already to overcome this issue, as there's a finite amount of letters in an alphabet. Having multiple longName parameters should do the trick as well.

**Comment by Khaos66** [comment]
This is really sad. I wanted to modernize an old app that uses multichar short options and now I can't...

Wouldn't it be an option to add it as Opt-In? I don't want `-gf` to become interpreted as `-g -f` anyways...

**Comment by DanJBower** [comment]
Was this ever implemented? Aliases would be super handy for me
