### ISSUE TITLE
HelpVerbOption is not working properly

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#125]
<a href="https://github.com/eocron"><img src="https://avatars1.githubusercontent.com/u/5383002?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eocron](https://github.com/eocron)**
_Wednesday Mar 29, 2017 at 11:38 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/432_

----

Hello, found problem with HelpVerbOption, it does not pass verb name if specified like this:
    
     app.exe help some-verb-name

Can you please check this?
Also, I questioned it on stackoverflow [here](http://stackoverflow.com/questions/43092065/command-line-parser-verb-help-not-working).

**Comment by ericnewton76** [comment]
<a href="https://github.com/CatchemAl"><img src="https://avatars0.githubusercontent.com/u/4703989?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CatchemAl](https://github.com/CatchemAl)**
_Thursday Mar 30, 2017 at 11:43 GMT_

----

I am currently struggling with the exact same issue and stumbled upon this. If it is not a bug, the documentation probably needs clarifying.

**Comment by moh-hassan** [comment]
Myapp verb --help
