### ISSUE TITLE
Is it possible to use case insensitive with Verbs? 

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#132]
<a href="https://github.com/pduer"><img src="https://avatars2.githubusercontent.com/u/8514833?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pduer](https://github.com/pduer)**
_Tuesday Apr 25, 2017 at 13:41 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/439_

----

Since verbs are defined as attributes before classes, can you still use case insensitivity?

**Comment by ericnewton76** [comment]
<a href="https://github.com/KomAuras"><img src="https://avatars2.githubusercontent.com/u/3600993?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KomAuras](https://github.com/KomAuras)**
_Friday Jul 21, 2017 at 07:01 GMT_

----

+1 for feature

**Comment by ericnewton76** [comment]
<a href="https://github.com/JeremyMorton"><img src="https://avatars3.githubusercontent.com/u/10471528?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JeremyMorton](https://github.com/JeremyMorton)**
_Tuesday Aug 22, 2017 at 22:40 GMT_

----

When creating the Parser, alter the settings to turn off case sensitivity.
```
      var parser = new Parser(settings =>
      {
        settings.CaseSensitive = false;
      });
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/pduer"><img src="https://avatars2.githubusercontent.com/u/8514833?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pduer](https://github.com/pduer)**
_Wednesday Aug 23, 2017 at 11:50 GMT_

----

Wow, yeah that will do the trick! 

I really like this library, wish I knew what to contribute to make it better!

**Comment by JJoe2** [comment]
> [<img alt="" width="48" height="48" src="https://avatars3.githubusercontent.com/u/10471528?v=4">](https://github.com/JeremyMorton) **Comment by [JeremyMorton](https://github.com/JeremyMorton)**
> _Tuesday Aug 22, 2017 at 22:40 GMT_
> 
> When creating the Parser, alter the settings to turn off case sensitivity.
> 
> ```
>       var parser = new Parser(settings =>
>       {
>         settings.CaseSensitive = false;
>       });
> ```

With version 2.4.3.0 I tried replacing:

    var parser = Parser.Default;

by the above code, but it wasn't enough.  By spelunking I discovered that I also had to set:

    settings.HelpWriter = Console.Error;

I would have expected the above code to return a parser whose settings were identical to `Parser.Settings.Default` except those specifically modified by the `Action<ParserSettings>`.
