### ISSUE TITLE
Bug: Error supplying Required Value & Option with same Text

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#133]
<a href="https://github.com/Good-man"><img src="https://avatars2.githubusercontent.com/u/4473709?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Good-man](https://github.com/Good-man)**
_Tuesday Apr 25, 2017 at 14:54 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/440_

----

@gsscoder 

Given:
```
class Options
{
    [Value(0, Required = true)]
    public string Text { get; set; }

    [Option("option", Required = true)]
    public string Option { get; set; }
}
```
` mycmd.exe "test" --option "test" `

produces:

```
ERROR(S):
  A required value not bound to option name is missing.

  --option        Required.

  --help          Display this help screen.

  --version       Display version information.

  value pos. 0    Required.

```
whereas 

` mycmd.exe "test1" --option "test2" `

works fine.  

It's not apparent why passing the same value would cause commandline to behave differently.

**Comment by ericnewton76** [comment]
<a href="https://github.com/JeremyMorton"><img src="https://avatars3.githubusercontent.com/u/10471528?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JeremyMorton](https://github.com/JeremyMorton)**
_Tuesday Aug 22, 2017 at 22:38 GMT_

----

This is especially common when you have integer options and values, since it can be common to want to specify 0 or 1 for both an option and a value.

**Comment by ericnewton76** [comment]
<a href="https://github.com/sajagi"><img src="https://avatars0.githubusercontent.com/u/322023?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sajagi](https://github.com/sajagi)**
_Thursday Oct 05, 2017 at 11:58 GMT_

----

This bug is still present in the latest nuget package (2.1.1-beta), but it looks like it's fixed already in source code.

**Comment by moh-hassan** [comment]
Resolved.  
Try it [online](https://dotnetfiddle.net/v9Fv5T)
