### ISSUE TITLE
Parser.ParserSettings.MutuallyExclusive=true - does not work as stated in the documentation

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#14]
<a href="https://github.com/coyot"><img src="https://avatars3.githubusercontent.com/u/157004?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [coyot](https://github.com/coyot)**
_Tuesday Nov 19, 2013 at 14:26 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/109_

----

According to the https://github.com/gsscoder/commandline/wiki/Mutually-Exclusive-Options

this works like that: 

```
;; permitted
$ app --enablejavascript --documentroot ~/var/local/website

;; denied
$ app --anonymouslogin --enablejavascript
```

BUT based on my research - this works exactly OPPOSITE! You are able to set values from DIFFERENT sets, not set values which are in the same "mutually exclusive set" - this is correct name, but this does not work as described...

**Comment by ericnewton76** [comment]
<a href="https://github.com/coyot"><img src="https://avatars3.githubusercontent.com/u/157004?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [coyot](https://github.com/coyot)**
_Thursday Dec 19, 2013 at 14:29 GMT_

----

Any updates about this task?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Dec 19, 2013 at 15:48 GMT_

----

I'm pretty sure the documentation is wrong -- I would expect it to behave like the code does, not like the docs. If you want, you can update the wiki yourself.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Jul 09, 2015 at 17:35 GMT_

----

http://stackoverflow.com/questions/10639320/command-line-parser-with-mutually-exclusive-required-parameters

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Jul 09, 2015 at 17:36 GMT_

----

@nemec, are you sure? I think docs are correct.

**Comment by gerardog** [comment]
Docs (for 1.x) were correct. MutuallyExclusive means only one of each set can appear together. The OP misunderstood the docs. I believe this should be closed.
