### ISSUE TITLE
Expected input format for DateTime

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#141]
<a href="https://github.com/rogics"><img src="https://avatars2.githubusercontent.com/u/5059347?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rogics](https://github.com/rogics)**
_Monday Jun 12, 2017 at 07:30 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/450_

----

What is expected input format for DateTime parameter?
I'm getting  1/1/0001 12:00:00 AM as a result whatever format I try!?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Jun 15, 2017 at 05:46 GMT_

----

Can you post what you've tried? `2017-01-10 12:10:15` works fine for me, among other formats.

**Comment by djowatts** [comment]
@ericnewton76 In the latest version available (2.3.0) the example you use above did set the date, but not the time for me. I got the time to parse successfully by changing it to `2017-01T10 12:10:15`

**Comment by walterX12** [comment]
For me worked `2019-01-01T12:10:15` (version 2.6.0)
