### ISSUE TITLE
Package CommandLineParser 1.9.71 is not compatible with netcoreapp1.1 

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#145]
<a href="https://github.com/ibruynin"><img src="https://avatars2.githubusercontent.com/u/15861800?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ibruynin](https://github.com/ibruynin)**
_Friday Jun 23, 2017 at 09:25 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/454_

----

Hi

I'm unable to install CommandLineParser in a .net core app.

Install-Package : Package CommandLineParser 1.9.71 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package CommandLineParser 1.9.71 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)

Is it possible to support this as well?

Thanks!
Ian

**Comment by ericnewton76** [comment]
<a href="https://github.com/HelloKitty"><img src="https://avatars0.githubusercontent.com/u/5829095?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HelloKitty](https://github.com/HelloKitty)**
_Friday Jun 23, 2017 at 18:55 GMT_

----

@ibruynin , you should enable pre-release nugets to gain access to the netstandard 2.1.1-beta.

**Comment by Athari** [comment]
@ericnewton76 This issue is obsolete and should be closed.
