### ISSUE TITLE
Verbatim values are parsed as options (when they shouldn't be)

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#159]
<a href="https://github.com/cdmihai"><img src="https://avatars0.githubusercontent.com/u/2255729?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cdmihai](https://github.com/cdmihai)**
_Friday Aug 18, 2017 at 23:32 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/470_

----

Given an options class with an option of type string:

```c#
    class Options
    {
        [Option('c', "command", HelpText = "command")]
        public string Command { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var result = Parser.Default.ParseArguments<Options>(args);

            result
                .WithParsed<Options>(
                    o =>
                    {
                        Console.WriteLine($"{o.Command}");
                    })
                .WithNotParsed(
                    e =>
                    {
                        Environment.Exit(1);
                    });
        }
    }
```

I would expect multi word values surrounded by quotes to be treated verbatim as a value for the string option.

Instead, CommandLineParser may end up parsing the verbatim string when it shouldn't:

```
MeasureCommand.exe -c "-a -e"
MeasureCommand 1.0.0
Copyright (C) 2017 MeasureCommand

ERROR(S):
  Option 'a' is unknown.

  -c, --command    command

  --help           Display this help screen.

  --version        Display version information.


MeasureCommand.exe -c "-c -a"
MeasureCommand 1.0.0
Copyright (C) 2017 MeasureCommand

ERROR(S):
  Option 'c, command' is defined multiple times.

  -c, --command    command

  --help           Display this help screen.

  --version        Display version information.


MeasureCommand.exe -c " -c -a"
c=[ -c -a]

MeasureCommand.exe -c "foo -c -a"
c=[foo -c -a]
```

**Comment by wexman** [comment]
I have the same problem. I want to specify parameters to my exe that are to be passed on to another .exe. For example:

`starter.exe SomeOtherExe -f "this is to=be -unparsed"`

**Comment by wexman** [comment]
Just found out that it works - kind of - when using a blank after the opening quotes, for example

starter.exe SomeOtherExe -f " this is to=be -unparsed"

(the difference will probably be hard to notice). Only downside is that the resulting string option will include the leading blank, but that should be handable.

**Comment by wexman** [comment]
Now I still need to find out how (if at all) to escape quotes when needing to pass on these...

**Comment by moh-hassan** [comment]
This is not a bug, it's how CMD handle quotation marks and process commandline to get `string[] args`.
use triple quote like:

                  MeasureCommand.exe -c """-a -e"""
in that case "-a -c" will be passed as one string to the Parser.

**Comment by RobThree** [comment]
I'm trying to build a string:

    grep {options}

So I'm trying `mycommand.exe -g "-i foo"` to get `grep -i foo`. I just don't get this to work; even when I try the suggested triple quotes: `mycommand.exe -g """-i foo"""` results in `grep "-i foo"`, but I don't want the quotes. I could trim the quotes but then the problem is that I want to be able to quote values too: `grep -i "some thing foo"` for example. I... just don't see how?
