### ISSUE TITLE
Can't disable a boolean argument with a default value of True

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#17]
<a href="https://github.com/crmckenzie"><img src="https://avatars3.githubusercontent.com/u/947569?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [crmckenzie](https://github.com/crmckenzie)**
_Tuesday Jan 14, 2014 at 18:47 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/115_

----

-c false should turn off the switch for -c.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Tuesday Jan 14, 2014 at 19:38 GMT_

----

```
public bool MyValue { get { return _myValue; } set { _myValue = !value; } }
```

Just kidding.

That's actually a really good idea and it lets the boolean value be scripted: `MyApplication.exe -c "$myBool"`

**Comment by ericnewton76** [comment]
<a href="https://github.com/igitur"><img src="https://avatars1.githubusercontent.com/u/145854?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [igitur](https://github.com/igitur)**
_Monday Sep 08, 2014 at 10:04 GMT_

----

I created a pull request for this. PR #133

**Comment by ericnewton76** [comment]
<a href="https://github.com/Kimi-Arthur"><img src="https://avatars2.githubusercontent.com/u/2446305?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kimi-Arthur](https://github.com/Kimi-Arthur)**
_Tuesday Jun 16, 2015 at 06:14 GMT_

----

Here is a solution I think is good.
For long option, provide a 'no' option to negate it.
Like "--dryrun" can be negated with "--nodryrun".

**Comment by ericnewton76** [comment]
<a href="https://github.com/Mizipzor"><img src="https://avatars1.githubusercontent.com/u/139879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mizipzor](https://github.com/Mizipzor)**
_Sunday Jun 21, 2015 at 08:30 GMT_

----

@igitur, as you can see in the issue history your PR is listerd here since you referenced this issue number in it, GitHub does this automatically. :)

**Comment by ericnewton76** [comment]
<a href="https://github.com/n074v41l4bl34u"><img src="https://avatars1.githubusercontent.com/u/657784?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [n074v41l4bl34u](https://github.com/n074v41l4bl34u)**
_Thursday Feb 16, 2017 at 20:36 GMT_

----

To me it seems more like a bug then an enhancement. Either way it is a small thing and already fixed in other branches so implementing it might be an easy win for the project.

**Comment by alexandre-lecoq** [comment]
It doesn't seem to be fixed in 2.2.1. Any idea when the fix will be released ?

**Comment by anderslyman** [comment]
Seeing this as well

**Comment by moh-hassan** [comment]
Fixed using  nullable  bool
