### ISSUE TITLE
Short `-h` option for help

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#172]
<a href="https://github.com/alexreg"><img src="https://avatars3.githubusercontent.com/u/67036?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alexreg](https://github.com/alexreg)**
_Sunday Oct 15, 2017 at 23:16 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/492_

----

This would be a nice feature to have (configurable in `HelpText` perhaps) as an addition to the long `--help` option.

**Comment by moh-hassan** [comment]
Supporting `-h` can cause Breaking change for Application which may use `-h` as option.
With Custom Help and setting `AutoHelp=false`, can help in implementing  `-h`
```cs
class Options
{

//....
 [Option('h',"help","Show help screen"
  public bool Help {get;set;}  //using AutoHelp=false
}
```
