### ISSUE TITLE
TimeSpan option failing to parse with "bad format"

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#173]
<a href="https://github.com/georgiosd"><img src="https://avatars3.githubusercontent.com/u/1672054?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [georgiosd](https://github.com/georgiosd)**
_Monday Oct 16, 2017 at 07:30 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/493_

----

If defined a `TimeSpan?` property in my options and passed it as "00:30" from the commandline but it failed with "bad format". 

Is this not supported?

**Comment by ericnewton76** [comment]
<a href="https://github.com/SuperJMN"><img src="https://avatars3.githubusercontent.com/u/3109851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SuperJMN](https://github.com/SuperJMN)**
_Sunday Oct 22, 2017 at 16:31 GMT_

----

I'm having the same problem with a nullable enum.

**Comment by ErikSchierboom** [comment]
> I'm having the same problem with a nullable enum.

Same here.

**Comment by nemec** [comment]
I think this is the root of the problem: https://weblogs.asp.net/pjohnson/Convert.ChangeType-doesn_2700_t-handle-nullables

> Convert is not very extensible and was designed around a fixed set of types

The library uses `Convert.ChangeType` internally to convert from string which doesn't support nullable at all. We need to gut it and add support for `ComponentModel`/`TypeConverter`, which would also let developers add converters for custom types.
