### ISSUE TITLE
Has the approach to verbs in v2 changed?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#178]
<a href="https://github.com/ravensorb"><img src="https://avatars3.githubusercontent.com/u/2222472?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ravensorb](https://github.com/ravensorb)**
_Thursday Nov 02, 2017 at 18:53 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/500_

----

I was reviewing the code and the following wiki for vers
https://github.com/gsscoder/commandline/wiki/Latest-Version  and I cannot see how they line up.

Ex - the following will not compile
```
var result = CommandLine.Parser.Default.ParseArguments<AddOptions, UpdateOptions, DeleteOptions(args).MapResult(
    (AddOptions aopts) => {},
    (UpdateOptions upopts) => {},
    (DeleteOptions dopts) => {});
```
It complains that there is no support for more than one Generic and from looking at the code, I didn't see any overrides or extensions to ParseArguments that supports multiple generics.  So I was curious if the approach had changed.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Nov 02, 2017 at 19:08 GMT_

----

Two things:

1. `MapResult` has a final delegate parameter that is required to be of type `IEnumerable<Error>` for any errors.
2. Each delegate must return a _value_ - they are `Func` not `Action` and each value must be the same type. If you quickly add `return "";` to each of those it compiles for me.

**Comment by ericnewton76** [comment]
<a href="https://github.com/ravensorb"><img src="https://avatars3.githubusercontent.com/u/2222472?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravensorb](https://github.com/ravensorb)**
_Thursday Nov 02, 2017 at 19:16 GMT_

----

Cool  So i just tried build 2.1.1-beta and I cannot get the snippet above to compile 

```
error CS0305: Using the generic method 'Parser.ParseArguments<T>(IEnumerable<string>)' requires 1 type arguments
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Nov 02, 2017 at 19:20 GMT_

----

Did it mention a file/line number?

**Comment by ericnewton76** [comment]
<a href="https://github.com/ravensorb"><img src="https://avatars3.githubusercontent.com/u/2222472?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravensorb](https://github.com/ravensorb)**
_Thursday Nov 02, 2017 at 19:23 GMT_

----

Its in my simple test app and when I look at the object explorer I only see a ParseArguments<T> and not other overloads for more generic args.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Nov 02, 2017 at 19:53 GMT_

----

Sorry I misread and thought you were building the source code of the library. This worked for me on the latest beta:

```csharp
var result = CommandLine.Parser.Default.ParseArguments<AddOptions, UpdateOptions, DeleteOptions(args).MapResult(
    (AddOptions aopts) => {return ""; },
    (UpdateOptions upopts) => {return ""; },
    (DeleteOptions dopts) => {return ""; },
    (IEnumerable<Error> errs) => {return ""; });
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/ravensorb"><img src="https://avatars3.githubusercontent.com/u/2222472?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ravensorb](https://github.com/ravensorb)**
_Thursday Nov 02, 2017 at 20:10 GMT_

----

That helped -- I found the issue :)  It appears you must add the using statement

```
using CommnadLine;
```

Without that it doesn't find the extension methods or the Error option.

**Comment by mhmd-azeez** [comment]
@ericnewton76  Wouldn't it be better to mention the need to add `using CommnadLine;` in the README.md example as well? Or at least write `Parser.Default.ParseArguments` instead of `CommandLine.Parser.Default.ParseArguments` to force the programmer to add a using statement.

Because it's not obvious from the example that these are extension methods and can produce frustrating compilation errors.

**Comment by heinermann** [comment]
Just ran into this myself, thanks whoever ran into this issue first and shared the fix. 🙏🏻
