### ISSUE TITLE
Is it possible to pass a pipe symbol (|) as a parameter value?

### ISSUE THREAD

**Issue by natiki** [commandlineparser/commandline#181]
Hi,

- In line with https://github.com/gsscoder/commandline/issues/501 I am posting here even though we are still using 1.9.71

I have a little console app that parses CSV's and occastionally the separator is a pipe (|) symbol. Is there any way to pass this on the command line that would not confuse the parser?

`MyConsoleApp --csv-separator=|`

**Comment by nemec** [comment]
Have you tried putting it in quotes? If you're using Powershell as your shell, the pipe is a reserved character and needs to be quoted.

**Comment by natiki** [comment]
For most shells | is considered a reserved character the same as < > etc. So I was just wondering if this had been catered for explicitly or not.

**Comment by natiki** [comment]
I implemented an encoding on the command line to pass characters that would annoy the command line whether it be command.com or powershell.exe
