### ISSUE TITLE
Hide argument from help text for an argument

### ISSUE THREAD

**Issue by mjamro** [commandlineparser/commandline#190]
I would like to propose an enhancement to allow hiding of an option from auto generated command help. This would be useful for handling deprecated arguments, which should not be used, but are present for backward compatibility.

This could be done by adding additional parameter to the `Option` attribute like this:

```
public class ProgramArguments
{
    [Option("arg1", ExcludeFromHelpOutput = true)]
    public bool Arg1{ get; set; }

    [Option("arg2")]
    public bool Arg2{ get; set; }

    [HelpOption]
    public string GetUsage()
    {
        return HelpText.AutoBuild(this, (HelpText current) => HelpText.DefaultParsingErrorsHandler(this, current));
    }
}
```

When `ExcludeFromHelpOutput` is set to true command help would not include `arg` and include only `arg2`.

**Comment by ericnewton76** [comment]
What about ```Deprecated = true``` or ```DeprecatedMessage = "Option is deprecated"``` on the ```OptionAttribute```?

**Comment by yar229** [comment]
[Option(Hidden = true)]

**Comment by ericnewton76** [comment]
@yar229 I thought I saw you suggest using the ```System.ObsoleteAttribute``` which could work well... it'll also highlight areas in your code where the option property being used is obsoleted.  Did you change your mind?

I think potentially the Obsolete attribute could be supported in addition to ```[Option(Hidden=true)]```

**Comment by yar229** [comment]
I'm using both  `[Obsolete]` and `[Option(Hidden = true)]`
It would be nice to make descendant from OptionAttribute, but this one is sealed :(

**Comment by mjamro** [comment]
I think support for `[Obsolete]` and `[Option(Hidden = true)]` as @yar229  suggested would be great and cover all cases. 

First one will mark the parameter as obsolete in the help text. Second will hide the entire attribute in help text.

**Comment by JVimes** [comment]
I second having the help message reflect `[Obsolete]`. Maybe something like:

    --Database    OBSOLETE: (Default: Test) Specifies which database to use.

**Comment by vadi2** [comment]
`Hidden = true` works in the end.
