### ISSUE TITLE
NuGet packages with .NET Core support

### ISSUE THREAD

**Issue by brgrz** [commandlineparser/commandline#193]
The docs and readme state project supports .net core but not which specific version of .net standard and when I installed the NuGet package it brings down the .NET Framework 4.6.1 version for which VS then says it is incompatible with my .NET Core 2.0 console project.

Is .NET Core already supported, if so, which are the supporting NuGet packages or do we have to build it ourselves?

**Comment by nemec** [comment]
Hi @brgrz the [latest beta](https://www.nuget.org/packages/CommandLineParser/2.1.1-beta) is compatible with NETStandard 1.5 (according to [this](https://github.com/dotnet/standard/blob/master/docs/versions.md), it's .NET Core 1.0). Unless I messed something up, this package should support both NS1.5 and the full framework simultaneously. I have not yet tried building the source directly against NS2.0.

**Comment by MikeFoden** [comment]
@brgrz I found that if you uninstall it and then install the latest v2.1.1-beta, it gets added as a .NET Standard reference correctly.

**Comment by ericnewton76** [comment]
Does this satisfy the issue to where we can close it?

**Comment by brgrz** [comment]
Yes, installing v2.1.1-beta from the Prerelease feed does indeed work.
