### ISSUE TITLE
Latest Release news: release is imminent!

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#195]
This is just a placeholder issue to let everyone know that I'm trying to push a release out but running into this issue: https://github.com/dotnet/cli/issues/6381

**Comment by ericnewton76** [comment]
So now just somewhat struggling with F# and FAKE build system used here in Commandlineparser library.

Anybody good with F# pay attention to this repo ?  Might need to go to original repo at https://github.com/gsscoder/commandline

**Comment by slang25** [comment]
@ericnewton76 cool. I'd be interested in helping. Is there a branch I can look at or an error you are getting?

**Comment by ericnewton76** [comment]
It (the error) seems to have been resolved by AppVeyor or Github, it was related to token/secrets and the webhooks to download commits and kick off builds.

Release of v2.2 is imminent!

**Comment by ericnewton76** [comment]
@nemec only hold up to release is tagging the commit with v2.2.0.  What day do you think is best?  Should we wait til end of next week, to allow people to get back into work and so forth?  

I just dont wanna (potentially) create a brand new problem for people walking into work settings next week after our holidays.  Everybody's Nuget will want them to update to v2.2.0

**Comment by nemec** [comment]
I like the mental image of a bunch of developers running into work next week to see what new Christmas toys are in the Nuget update queue! Yes, I think the end of next week will be a good time for this long-awaited release.

**Comment by johnjaylward** [comment]
should this just be closed?
