### ISSUE TITLE
Fixed issue where it was treating 'help' as the verb that usage info was...

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#2]
<a href="https://github.com/tombatron"><img src="https://avatars0.githubusercontent.com/u/119369?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tombatron](https://github.com/tombatron)**
_Thursday Apr 04, 2013 at 01:55 GMT_
_Originally opened as https://github.com/gsscoder/commandline/pull/74_

----

... requested for.

Let's say that I have an application called 'example' that has a verb called 'dothing'. If I entered the following on the console:

```
example help dothing
```

The usage text displayed isn't for the verb specified but the default usage text.

----

_**[tombatron](https://github.com/tombatron)** included the following code: https://github.com/gsscoder/commandline/pull/74/commits_

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Apr 04, 2013 at 13:24 GMT_

----

Hi,
you're right the correct behavior should the one described on the top.

**Thanks for reporting and for the fix.**

Sorry but for the moment I'm unable to accept PR (as stated in https://github.com/gsscoder/commandline/issues/67).

This will be of great help in my current 2.0 development (for the moment still unpublished); since it's a deep kernel rewrite, you can understand, that in the transitory phase this would mean maintain two branches...

The fix will be integrated in the new branch. :D

Thanks,
Giacomo Stelluti Scala

**Comment by ericnewton76** [comment]
<a href="https://github.com/tombatron"><img src="https://avatars0.githubusercontent.com/u/119369?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tombatron](https://github.com/tombatron)**
_Thursday Apr 04, 2013 at 13:30 GMT_

----

Awesome!

**Comment by ericnewton76** [comment]
<a href="https://github.com/jonnyyu"><img src="https://avatars0.githubusercontent.com/u/2011471?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonnyyu](https://github.com/jonnyyu)**
_Friday Sep 13, 2013 at 11:09 GMT_

----

Hi can we take a few minutes to merge this PR?  
The issue is really a deal breaker for the Verb commands feature in stable 1.9.71.2. Who can use Verb commands without verb specific help?

Since it already took 5 months to develop the  2.0 since then, maybe it will take another few months. Before the 2.0 is ready, can we just take a few time let current version work?

After all, this is really a one-line fix.

Thanks!

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Friday Sep 13, 2013 at 23:20 GMT_

----

@jonnyyu this pull request can't be merged as-is since the codebase has changed radically since then. ~~Are you still experiencing this problem?~~

Can you upgrade to the latest version from git (2.0) and see if it's still an issue?

On the project homepage there's a "download zip" button on the bottom right. Just extract the project folder and add it as a reference in your solution. Only @gsscoder has NuGet privileges, so I can't help there.

**Comment by ericnewton76** [comment]
<a href="https://github.com/jonnyyu"><img src="https://avatars0.githubusercontent.com/u/2011471?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonnyyu](https://github.com/jonnyyu)**
_Monday Sep 23, 2013 at 15:40 GMT_

----

No, I finally gave up using it and switch to ManyConsole instead.

On Sat, Sep 14, 2013 at 7:20 AM, Dan Nemec notifications@github.com wrote:

> @jonnyyu https://github.com/jonnyyu this pull request can't be merged
> as-is since the codebase has changed radically since then. Are you still
> experiencing this problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gsscoder/commandline/pull/74#issuecomment-24430970
> .

## 

Yingshen(Jonny) Yu

**Comment by ericnewton76** [comment]
<a href="https://github.com/JMerrill"><img src="https://avatars0.githubusercontent.com/u/1194073?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JMerrill](https://github.com/JMerrill)**
_Monday Jan 19, 2015 at 14:09 GMT_

----

How different is the ManyConsole API? How long did it take you to convert from CommandLine? Thanks for any info.

**Comment by moh-hassan** [comment]
Resolved.
For verb help, run:

        myapp  myverb --help
