### ISSUE TITLE
Is there a way to override the "version" command?

### ISSUE THREAD

**Issue by Eason-Lian** [commandlineparser/commandline#200]
I'm trying to write some custom logic in version command. Is there a way to do that? I'm using the latest version (v2.0.275.0).

**Comment by ericnewton76** [comment]
Can you clarify a little more of what your doing, whats happening, and what you were expecting?

**Comment by Eason-Lian** [comment]
@ericnewton76 Thanks for replying! For some reason, I'm not able to modify assembly information. That means the version which "--version" shows is not correct. 

What I want is to specify assembly version in a configuration file (xml/json) and then read them when user is typing "--version". I created a custom VersionOptions in my project but unfortunately it can't be reached. Is there a way to override the default version option?

**Comment by stabiliser** [comment]
I have the same problem, am wanting to have a 'version' command to retrieve the version from a server, but CommandLineParser is always outputting the client version if I use 'version'.
