### ISSUE TITLE
Allows negative decimal numbers as values

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#21]
<a href="https://github.com/tbroust-trepia"><img src="https://avatars3.githubusercontent.com/u/4717186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tbroust-trepia](https://github.com/tbroust-trepia)**
_Friday Sep 12, 2014 at 08:09 GMT_
_Originally opened as https://github.com/gsscoder/commandline/pull/136_

----

If you provided "-2.5" as a parameter value, the library was basically considering it wasn't a value, but another parameter, because of both the negative sign and the dot. This fixes it.

----

_**[tbroust-trepia](https://github.com/tbroust-trepia)** included the following code: https://github.com/gsscoder/commandline/pull/136/commits_

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Monday Jun 08, 2015 at 16:10 GMT_

----

again, this is against stable; postponed until all PR work with 2.0 ends

thanks

**Comment by moh-hassan** [comment]
Resolved
