### ISSUE TITLE
FSharp.Core reference

### ISSUE THREAD

**Issue by thyn** [commandlineparser/commandline#213]
Please add FSharp.Core reference or remove it from project.

Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by ericnewton76** [comment]
I'll check into that, might be a problem with the build, its supposed to not actually include that reference on release.

**Comment by nemec** [comment]
@thyn did you get this error in the NuGet package or by trying to compile the source?

**Comment by ericnewton76** [comment]
I feel like this should be an alternative build, to include the FSharp.Core reference in the library... ie a separate Nuget package ```CommandLineParser-WithFSharp``` or something.  This way I can create separate nuspec that includes FSharp.Core as a package dependency separately.

@nemec what do you think?  I'm leaning this way.

**Comment by nemec** [comment]
Sounds good. I don't think we need F# core in the main library either.

**Comment by ericnewton76** [comment]
Released v2.2.1 which separates the library into two separate Nuget packages: CommandLineParser and CommandLineParser.FSharp
