### ISSUE TITLE
Require one or more of a set of options

### ISSUE THREAD

**Issue by Valinwolf** [commandlineparser/commandline#216]
Right now I'm doing manual verification that at lease one of my specific options are used. It would be nice if I could create a set like the `MutuallyExclusiveSet` that does it for me. I assume this is not implemented, since I cannot find it in either of the wikis.

_Random thought: I could theoretically simulate this if I could create multiple `MutuallyExclusiveSet`s on each option - creating a `MutuallyExclusiveSet` for every possible combination..._

**Comment by moh-hassan** [comment]
[wiki/Mutually-Exclusive-Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
