### ISSUE TITLE
ParserStateAttribute missing?

### ISSUE THREAD

**Issue by Valinwolf** [commandlineparser/commandline#219]
Trying to throw an error if they give a bad format and I was trying to use the info in the [old wiki](https://github.com/gsscoder/commandline/wiki/) under Display A Help Screen: [Handling Parsing Errors](https://github.com/gsscoder/commandline/wiki/Display-A-Help-Screen#handling-parsing-errors), and I can't find any of the mentioned *ParserState* in the library. Using them generates an error.

**Comment by nemec** [comment]
Only the "Latest Version" page in the old wiki is accurate for version 2.0 - that's why we didn't migrate the whole wiki over to this repository.

If you're using `WithNotParsed` or `MapResult` to access the results, one of the values is an `IEnumerable<Error>`  that contains all parser errors.

**Comment by Valinwolf** [comment]
Well, the whole reason I was looking for that is because I need to add a parser error from the property set. How do I do that? Or is it even possible?

**Comment by nemec** [comment]
I'm not sure I understand what you mean by 'parser error from the property set'. Any example?

**Comment by Valinwolf** [comment]
```
        private DateTime create,modify,access;

        [Option('c', "created", HelpText = "Set creation date", Default = "")]
        public string CreationDate
        {
            get
            {
                return create.ToLongDateString();
            }
            set
            {
                try
                {
                    if(value != "")
                        create = DateTime.Parse(value);
                }
                catch (Exception)
                {
                    // invalid format
                }
            }
        }
```
In the excerpt of my code, I want to replace the `// invalid format` line with something that shows the error/help screen, just like if I used a bad option, and halt parsing

**Comment by nemec** [comment]
I've tried a few different things, but I don't think it's possible to auto-generate help text _and_ stop parsing at the same time. If you let parsing finish (so you have access to the result object) you can generate the help text like this, though:

```csharp
var result = Parser.Default.ParseArguments<Options>(args);
Console.WriteLine(HelpText.AutoBuild(result, err => err, ex  => ex).ToString());
```

**Comment by Valinwolf** [comment]
That might work... I just have to figure out how to pass the error from my options class to my main class and make it print if there was errors.

**Comment by moh-hassan** [comment]
To upgrade my application from v1.9.71 to v2.3, Can I remove  `ParserStateAttribute` from the application and depend on ` WithNotParsed or MapResult` as described in [@nemec](https://github.com/commandlineparser/commandline/issues/219#issuecomment-357336085)
>If you're using WithNotParsed or MapResult to access the results, one of the values is an IEnumerable<Error> that contains all parser errors.

Are there any other side effect?
