### ISSUE TITLE
Upgrade to 2.2.1 adds several System Nuget packages

### ISSUE THREAD

**Issue by bradgentry** [commandlineparser/commandline#220]
When I upgraded from 2.0.275-beta to 2.2.1 (in a .NET 4.7 project), it added all of these System Nuget packages:

`<package id="System.Collections" version="4.0.11" targetFramework="net47" />`
`<package id="System.Console" version="4.0.0" targetFramework="net47" />`
`<package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net47" />`
`<package id="System.Globalization" version="4.0.11" targetFramework="net47" />`
`<package id="System.IO" version="4.1.0" targetFramework="net47" />`
`<package id="System.Linq" version="4.1.0" targetFramework="net47" />`
`<package id="System.Linq.Expressions" version="4.1.0" targetFramework="net47" />`
`<package id="System.Reflection" version="4.1.0" targetFramework="net47" />`
`<package id="System.Reflection.Extensions" version="4.0.1" targetFramework="net47" />`
`<package id="System.Reflection.TypeExtensions" version="4.1.0" targetFramework="net47" />`
`<package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net47" />`
`<package id="System.Runtime" version="4.1.0" targetFramework="net47" />`
`<package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net47" />`

Is this what you would expect?

**Comment by nemec** [comment]
Hi @bradgentry yes that is expected right now. They are added as a consequence of our .NET Core support. In a later version we may be able to optimize the dependencies a bit better for users on the full framework.

**Comment by ericnewton76** [comment]
He does bring up something that I noticed a few times, the nuspec is specifying the rc2 versions of all these assemblies, which probably should get cleaned up:

```
    <dependencies>
      <group targetFramework=".NETStandard1.5">
        <dependency id="System.Collections" version="4.0.11-rc2-24027" />
        <dependency id="System.Console" version="4.0.0-rc2-24027" />
        <dependency id="System.Diagnostics.Debug" version="4.0.11-rc2-24027" />
        <dependency id="System.Globalization" version="4.0.11-rc2-24027" />
        <dependency id="System.IO" version="4.1.0-rc2-24027" />
        <dependency id="System.Linq" version="4.1.0-rc2-24027" />
        <dependency id="System.Linq.Expressions" version="4.0.11-rc2-24027" />
        <dependency id="System.Reflection" version="4.1.0-rc2-24027" />
        <dependency id="System.Reflection.Extensions" version="4.0.1-rc2-24027" />
        <dependency id="System.Reflection.TypeExtensions" version="4.1.0-rc2-24027" />
        <dependency id="System.Resources.ResourceManager" version="4.0.1-rc2-24027" />
        <dependency id="System.Runtime" version="4.1.0-rc2-24027" />
        <dependency id="System.Runtime.Extensions" version="4.1.0-rc2-24027" />
      </group>
    </dependencies>
```

Any thoughts on that, @nemec?
