### ISSUE TITLE
Commandline Nuspec targets prerelease netstandard15 libraries

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#222]
We should upgrade these and potentially separate out net45/net46/net47 to not need to include these (since they are part of desktop framework.  Addresses thoughts brought up with #220 

```
    <dependencies>
      <group targetFramework=".NETStandard1.5">
        <dependency id="System.Collections" version="4.0.11-rc2-24027" />
        <dependency id="System.Console" version="4.0.0-rc2-24027" />
        <dependency id="System.Diagnostics.Debug" version="4.0.11-rc2-24027" />
        <dependency id="System.Globalization" version="4.0.11-rc2-24027" />
        <dependency id="System.IO" version="4.1.0-rc2-24027" />
        <dependency id="System.Linq" version="4.1.0-rc2-24027" />
        <dependency id="System.Linq.Expressions" version="4.0.11-rc2-24027" />
        <dependency id="System.Reflection" version="4.1.0-rc2-24027" />
        <dependency id="System.Reflection.Extensions" version="4.0.1-rc2-24027" />
        <dependency id="System.Reflection.TypeExtensions" version="4.1.0-rc2-24027" />
        <dependency id="System.Resources.ResourceManager" version="4.0.1-rc2-24027" />
        <dependency id="System.Runtime" version="4.1.0-rc2-24027" />
        <dependency id="System.Runtime.Extensions" version="4.1.0-rc2-24027" />
      </group>
    </dependencies>
```

**Comment by nemec** [comment]
We should probably upgrade to .net core 2.0 while we're at it. We're still using project.json which has been dead for a while. Add an empty targetframework for 45, 46,and 47 and hopefully NuGet will install only the needed depencencies.

**Comment by ericnewton76** [comment]
Ok, I'll play with that sometime this week.  

Do we get any benefits from going to NetStandard20?   Seems like NetStandard15 works for now unless you know of some functionality missing

**Comment by nemec** [comment]
Our .net core project format (.xproj, project.json, etc.) are not supported by VS 2017. I know 1.5 came out before the new .csproj project format, so I'm not sure if we can upgrade and keep 1.5 support at the same time. If we can, no problem, but we should definitely upgrade away from project.json so that we get the latest tooling support during development.

**Comment by PhilPJL** [comment]
@ericnewton76 
The benefit for me (and other .NET 4.x) users is that when we reference CommandLineParser we aren't forced to reference a load of .NETStandard packages unnecessarily.
