### ISSUE TITLE
Seem to be some missing with this fork

### ISSUE THREAD

**Issue by JasonReynolds92** [commandlineparser/commandline#223]
I am upgrading my previous app from 4.6.2 to core2, Thus changing over to this CommandLineParser from Gio's as the previous didn't seem to support Core. Now i have an issue of specifics could not be found 

`      #region Properties

      [ParserState]
      public IParserState LastParserState { get; set; }
     
      #endregion
     
      #region Functions
     
      [HelpOption]
      public string GetUsage()
      {
            //Output usage plus any errors if found.
            return HelpText.AutoBuild(this, current => HelpText.DefaultParsingErrorsHandler(this, current));
        }

        #endregion
    }
}`

Any help or documentation direction would be great.

Thankyou

**Comment by oricgn** [comment]
Hi Jason,

perhaps same problem like https://github.com/commandlineparser/commandline/issues/182

Regards
Oliver
