### ISSUE TITLE
How to remove empty line between each options in help display ?

### ISSUE THREAD

**Issue by sybaris** [commandlineparser/commandline#224]
Hello

When I have several options, the display of help show me an empty line between each option.
I saw the property **AdditionalNewLineAfterOption** in HelpText.
I would like to set this to false for AutoBuild, but how can I do that ?

Thanks for advance
Sybaris

**Comment by DominikWiesend** [comment]
This does the Job for me, but I'm struggling getting a additional line between...
ERROR(S)
USAGE

If you wanna have the copyrights as well, use another constructor for [HelpText] (new HelpText(SentenceBuilder.Create(), ..., ....)


```
Parser myParser = new Parser(config => config.HelpWriter = null);
ParserResult<object> myResult = myParser.ParseVerbs<DUALHOME, MOVE>(args);

myResult.WithNotParsed(errs =>
{
    HelpText myHelpText = HelpText.AutoBuild(myResult, onError =>
    {
        HelpText nHelpText = new HelpText(SentenceBuilder.Create(), "MS Operation Manager - AgentManagement (agtmve)");
        nHelpText.AdditionalNewLineAfterOption = false;
        nHelpText.AddDashesToOption = true;
        nHelpText.MaximumDisplayWidth = 4000;
        nHelpText.AddOptions(myResult);
        return HelpText.DefaultParsingErrorsHandler(myResult, nHelpText);
    },
    onExample => { return onExample; });
    Console.Error.WriteLine(myHelpText);
});
```

**Comment by sybaris** [comment]
Hi 

Thanks for your answer. 
It's works when I have an error : help is displayed as I want. But when I call my program with the --help option, I still have  an empty line between each option. I don't understand why...

Regards,
Sybaris
