### ISSUE TITLE
Can't parse custom types.

### ISSUE THREAD

**Issue by jmenashe** [commandlineparser/commandline#228]
Custom types are no not parsed correctly via their string constructors. An error is thrown and the entire parsing attempt fails. More generally, it would be best to operate under the principle of least surprise.

**Comment by jmenashe** [comment]
In an earlier version of CommandLineParser (I believe 1.9.7) I was able to resolve this by performing a single-argument string constructor lookup and using that in the case that TypeConverter-based parsing failed for nullable types. The codebase has changed significantly since that time so I'm not sure if the same approach would apply. In any case, I would recommend either 1) supporting single-argument string constructors as an alternative to TypeConversion and other explicit conversion approaches, or 2) throw an exception with an informative error message when the following criteria hold:

a. An command line argument has been supplied with a value that cannot be successfully parsed,
b. Parsing fails because no type conversion methods exist

Essentially, common mistakes should yield helpful error messages rather than just anonymous failures.

**Comment by moh-hassan** [comment]
Custom types should have ctor with one string parameter

**Comment by AdamCoulterOz** [comment]
@moh-hassan you should also honour built-in TypeConverter behaviour... if a custom type has a loaded TypeConverter that supports converting the given type from a string, you should use that (before looking for a constructor which takes 1 string argument, which is potentially very unsafe).

This is how most Web and JSON libraries handle converting from strings to custom objects.
