### ISSUE TITLE
Constructor called 10 times when converting

### ISSUE THREAD

**Issue by antonioortizpola** [commandlineparser/commandline#229]
Why this code:
```
public class Program
    {

        static int Main(string[] args)
        {
            var verbs = typeof(Program).Assembly.DefinedTypes
                .Where(t => t.CustomAttributes.Any(a => a.AttributeType == typeof(VerbAttribute)))
                .Select(ti => ti.AsType())
                .ToArray();
            var resultCode = Parser.Default.ParseArguments(args, verbs).MapResult(
                (IVerb verb) => verb.Execute(),
                errs => 1
            );

            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();

            return resultCode;
        }
    }

    [Verb("testWeeklySchedule", HelpText = "Test using some fake data.")]
    internal class TestWeeklySchedule : IVerb
    {
        public TestWeeklySchedule(TimeOfDay startTime, IEnumerable<DayOfWeek> daysOfWeek)
        {
            //StartTime = TimeSpan.Parse(startTime);
            StartTime = startTime;
            DaysOfWeek = daysOfWeek;
        }

        [Option(HelpText = "Time to start event.")]
        public TimeOfDay StartTime { get; }

        [Option(Required = true, HelpText = "Days to execute event.", Min = 1)]
        public IEnumerable<DayOfWeek> DaysOfWeek { get; }

        public int Execute()
        {
            Console.WriteLine("Hello world with schedule " + JsonConvert.SerializeObject(this));
            return 0;
        }
    }

    internal class TimeOfDay
    {
        public static int timesCalled = 0;
        public TimeOfDay(string timeAsString)
        {
            timesCalled++;
            Console.WriteLine("Constructor called with " + timeAsString);
            Time = TimeSpan.Parse(timeAsString);
        }

        public TimeSpan Time { get; }
    }
```

Calls the constructor 10 times?!?!?!?!?!?!?!
The output is

> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Constructor called with 00:00
> Hello world with schedule {"StartTime":{"Time":"00:00:00"},"DaysOfWeek":[1]}
> Press any key to exit...

**Comment by antonioortizpola** [comment]
And how can i use the enums by the name and not by index?
- Why there is no easy way to add custom converters?
I want to add a TimeSpan object, but there is no easy way, i have only made it work creating an object with a string constructor.

- Why default does not work? (it throws a parse exception from string)
If I change the code from
```
[Option(HelpText = "Time to start event.")]
        public TimeOfDay StartTime { get; }
```
To
```
[Option(Default = "00:00", HelpText = "Time to start event.")]
        public TimeOfDay StartTime { get; }
```
The converter stops working

**Comment by vaz-rodrigo** [comment]
> Why default does not work? (it throws a parse exception from string)

Try using "DefaultValue" instead of "Default".

Also, try not using "JsonConvert.SerializeObject(this)", look for an alternative and check if it still calls the constructor 10 times.

**Comment by antonioortizpola** [comment]
> Try using "DefaultValue" instead of "Default".

I could not find the "DefaultValue" option (using net core 2).
![screenshot_15](https://user-images.githubusercontent.com/11655127/35758663-c36b2bb0-083a-11e8-8153-e6062943dc8a.png)

> Also, try not using "JsonConvert.SerializeObject(this)", look for an alternative and check if it still calls the constructor 10 times.

Yes, is still calling the constructor 10 times
![screenshot_16](https://user-images.githubusercontent.com/11655127/35758854-a39ca0ce-083b-11e8-908b-aef6d67750d3.png)

**Comment by Athari** [comment]
@antonioortizpola With the way the library is written, there're way too many multiple iterations over `IEnumerable`s. The fact that it can cause side effects is completely ignored. Even the base type `Maybe` which is used throughout the code, causes double iteration just to check whether a sequence is empty.

![](https://i.imgur.com/IIipREz.png)

See the blue squiggles? Those are mostly multiple enumerations detected by ReSharper in just one method.

I'd recommend against putting any complicated logic into types the library directly interacts with.

**Comment by antonioortizpola** [comment]
Sure, it is just what we are doing, just simple and quick converters that do not cause trouble if they are called some extra times and just at the beginning of the app, however, is nice to see the root of the problem, i could not make the time to check the source so thanks a lot for the clarification.

I know is too radical to change the code to avoid this, but maybe a note in the documentation to warn the newcomers to be careful about this could be great.

**Comment by moh-hassan** [comment]
Tested with v2.4.3+ and Constructor is called only once.
