### ISSUE TITLE
Project is not dead!

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#23]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsscoder](https://github.com/gsscoder)**
_Thursday May 28, 2015 at 18:24 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/152_

----

I apologize for not being able to coordinate issues, pull requests and for not replying to all emails.
I was very engaged in various heavy and challenging projects around Europe.

I next days (or may be weeks) I'll try to catch up with everything...

_For now I repeat what I've said to few (of many, sorry) emails I've replied: please use the consolidated code base of latest stable on branch [stable-1.9.71.2](https://github.com/gsscoder/commandline/tree/stable-1.9.71.2)._

<del>At the moment I can't make any preview for the future: maybe the new pre-release 2.0.0.0 (actual master branch) will be discarded, maybe not or maybe both versions will go ahead together. As always suggestions are welcome.</del><br/>
**EDIT**
- I've to check ISSUEs but there's good chance that for an intermediate period stable-1.9.72.2 could evolve in its path.
- But there's no doubt that pre-release 2.0 will stabilize, becoming the official branch. I'm working to make it happen.

**EDIT 2**
- All PRs that can be merged to trunk as been merged.
- Now I can review ISSUEs.

Regards,
Giacomo Stelluti Scala

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Saturday May 30, 2015 at 04:41 GMT_

----

You may have received one or mail mail linked to this **issue/announcement**, just for a first feedback. Your emails are now filed in my gmail with `projects\lib-cmdline` label for further examination.

Please be patient you'll receive a better reply.

Regards.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Saturday Jun 06, 2015 at 13:25 GMT_

----

I'm going to close this issue, but feel free to add comments.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Saturday Jun 06, 2015 at 14:48 GMT_

----

Re-open, for visibility...

**Comment by ericnewton76** [comment]
<a href="https://github.com/Nate-Wilkins"><img src="https://avatars1.githubusercontent.com/u/2957868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nate-Wilkins](https://github.com/Nate-Wilkins)**
_Sunday Jun 07, 2015 at 17:12 GMT_

----

:+1:

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Monday Jun 08, 2015 at 04:07 GMT_

----

Thank you for voting up! If you think some PR or ISSUE should have precedence please tell, so a discussion can start.
Have a nice day.
Giacomo

**Comment by ericnewton76** [comment]
<a href="https://github.com/Nate-Wilkins"><img src="https://avatars1.githubusercontent.com/u/2957868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nate-Wilkins](https://github.com/Nate-Wilkins)**
_Tuesday Jun 09, 2015 at 13:26 GMT_

----

I would love a feature to suite #107 but that's probably not a priority.

@cosmo0 has a fork with quite a few other people's PRs maybe that should be merged back first?

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Tuesday Jun 09, 2015 at 14:22 GMT_

----

Not at the moment, @Nate-Wilkins, but is an interesting feature and will be when trunk stabilizes.

The issue you pointed out is probably thought for latest stable, but I'm currently working on 2.0 pre-rel, which will not be abandoned.
I'm going to edit this announcement to point it out.

Backing to the feature, when finished with PR (as you can see from GitHub activity, I'm really back to work): I'll try to catch up with issue.

Thank you for expressing your preference on feature requests.

Stay tuned.

Regards.

PS:
- I know that my absence resulted in a various fork to be maintained, this was good for the project and for the its users too (thank you, guys!).
- I'm going to maintain this repo (which as you and people know is the official one), for various reason: from the joy that gives me working on open source environment, for not leaving users alone anymore and also because I actually use `CommandLine.dll` practically in any closed source project of my job activities.

**Comment by ericnewton76** [comment]
<a href="https://github.com/arutkowski00"><img src="https://avatars0.githubusercontent.com/u/8336970?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arutkowski00](https://github.com/arutkowski00)**
_Sunday Oct 01, 2017 at 20:40 GMT_

----

Ok, but I think now it is dead.

**Comment by kenny-evitt** [comment]
This project's still among the living. This issue can be laid to rest.
