### ISSUE TITLE
'ParserResultExtensions' is not generic and so cannot have type arguments.

### ISSUE THREAD

**Issue by svetovich** [commandlineparser/commandline#230]
I just updated to v2.2.1 and I'm having some issues converting my old code to be compatible with the new version.  I've managed to get most of it done but I'm having an issue with the .WithParsed and .WithNotParsed functions of the Results variable.  The full error message is below and is the same for both functions ...

> Public Function WithParsed(action As Action(Of Startup.Arguments)) As ParserResult(Of Startup.Arguments)' defined in 'ParserResultExtensions' is not generic (or has no free type parameters) and so cannot have type arguments.

My "Options" class is named "Arguments" and all options are strings.  Not too sure where to go from here.

This is the line of Code I'm using to call these functions ...

```
Dim Results As ParserResult(Of Arguments) = Parser.Default.ParseArguments(Of Arguments)(Args)
Results.WithParsed(Of Arguments)(Function(opts) RunAutomation(opts)).WithNotParsed(Of Arguments)(Function(errs) OpenApplication())
```

And my options are below ...

```
Class Arguments
    <[Option]("p", "process", Required:=True, HelpText:="Enter either ""report"" or ""batch"".")> Public Property ProcessOption As String
    <[Option]("n", "name", Required:=True, HelpText:="Enter the name of the report or batch number to run")> Public Property NameOption As String
    <[Option]("r", "run", Required:=True, HelpText:="For a report, enter the location from the Library. For the batch, enter the type of reports to run.")> Public Property RunOption As String
    <[Option]("d", "date", Required:=False, HelpText:="Enter the date to run the process for.")> Public Property DateOption As String
    <[Option]("u", "user", Required:=False, HelpText:="Enter the user to run the process as.")> Public Property UserOption As String
    <[Option]("b", "batch", Required:=False, HelpText:="Enter the batch id that the report is running under.")> Public Property BatchId As String
End Class
```

**Comment by nemec** [comment]
Hi, I'm pretty unfamiliar with VB.Net but what you posted looks like it should be correct. What are the type signatures (parameters, return type, etc.) for `RunAutomation` and `OpenApplication`?

**Comment by svetovich** [comment]
`RunAutomation` and `OpenApplication` are both subs that don't have any returns.  And only `RunAutomation` looks for paramters, and that is the Arguments from the command line.

**Comment by nemec** [comment]
Change the word 'Function' to 'Sub' in your lambdas - Functions return a value, apparently. Then remove the generic arguments entirely from `WithParsed` and `WithNotParsed` and let the compiler infer the types. Then it compiles and runs for me in LINQPad.

	Dim Args As String = "-p thing -r asdoi -n kaka"
	Dim Results As ParserResult(Of Arguments) = Parser.Default.ParseArguments(Of Arguments)(Args.Split)
	Results.WithParsed(Sub(opts) RunAutomation(opts)).WithNotParsed(Sub(errs) OpenApplication())

**Comment by svetovich** [comment]
That didn't seem to help.  I don't think the issue is with the calls to my Subs.  In Visual Studio, even after making your suggested change, that has the error line is the `(Of Arguments)` section of the `.WithParsed(Of Arguments)` and `.WithNotPared(Of Arguments)`.

![2018-01-25_8-59-50](https://user-images.githubusercontent.com/29309431/35391962-359a41dc-01ae-11e8-87f7-3895296ad5b5.png)

**Comment by nemec** [comment]
Remove `(Of Arguments)` as well (see the final line of code I posted above).

**Comment by svetovich** [comment]
That seemed to have gotten rid of the error.  Thank you for your help.
