### ISSUE TITLE
Lambda design

### ISSUE THREAD

**Issue by flemingtech** [commandlineparser/commandline#232]
This is just so mind numbingly bloody stupid:
```
parser.ParseArguments<CmdLineOptions>(args).WithParsed(options => {
	DatabaseUpdateManager updateMgr = new DatabaseUpdateManager(options);
	updateMgr.Execute();
});
```
Why would this library assume that I want my entire application to be executing inside a lambda call? Is it going to handle my exceptions for me? Is it going to clean something up after my application finishes? Why would I want the instance of the parsing class lasting for the entire life of my application run? Do you really think I want your library stuck on my call stack for all of eternity? 

I assume you actually DO care about the community, so what is the actual benefit of the user community to this change? 

Sure I could use the library as follows... but come on this is horrible and you know it is. Having to use a lambda to get the resulting instance?

```
CmdLineOptions options = null;
parser.ParseArguments<CmdLineOptions>(args).WithParsed(o => options = o);
if (options != null) {
	DatabaseUpdateManager updateMgr = new DatabaseUpdateManager(options);
	updateMgr.Execute();
}
```

**Comment by nemec** [comment]
Thank you for your feedback. This is a fork of the original project, so if you are looking for rationale you will have to track down the original author and ask him. Best I can understand, the author was inspired by functional programming and F#'s [match expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/match-expressions).

You are welcome to continue using version 1.7 of the library but we don't provide support for it.

**Comment by sdg002** [comment]
Agree. Elegant work mostly. The authors lost focus in some areas.
