### ISSUE TITLE
Links to wiki in Readme.md are broken

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [commandlineparser/commandline#234]
They refer to https://github.com/gsscoder/commandline

**Comment by Warmag2** [comment]
Also, if you manage to access the wiki, the information is outdated.

I may be stupid, but I can't figure out how the help text builder works this time around, and proper documentation which accounts for the recent changes would really help.

**Comment by nemec** [comment]
Thanks, I fixed all references to the old page in the readme. The primary documentation today is in this repostitory's wiki (linked now in the readme).

You can still use `HelpText.AutoBuild` to generate a help text, but you need to pass in a parsing result in order to use it.
