### ISSUE TITLE
Separator Attribute Does Not Work

### ISSUE THREAD

**Issue by weswitt** [commandlineparser/commandline#237]
Using this fails:

        [Option('h', "host", Required = true, Separator = ':')]
        public string Host { get; set; }
        [Option('p', "port", Required = true, Separator = ':')]
        public int Port { get; set; }

The Host option parses a null string and the Port option will cause a parse error. Using this command line: "-h:192.168.1.185 -p:1883".

I'm using the 2.1.1-beta version of the library.

Am I doing something wrong or is this a bug?

**Comment by nemec** [comment]
Hi @weswitt,

Apologies, it sounds like we did not explain the `Separator` attribute properly. It is used to delimit multiple values within a single option, like the below. I don't believe it is possible to customize the separator between an argument and a value (either `--arg value` or `--arg=value`, or for short args `-avalue` with no space)

```csharp
void Main()
{
	var result = Parser.Default.ParseArguments<Options>("-p 80:443".Split());
	result.WithParsed(o => o.Dump());
}

public class Options
{
	[Option('p', "ports", Separator=':')]
	public IEnumerable<int> Ports {get;set;}
}
```

**Comment by weswitt** [comment]
OK, thanks for the clarification.

This would be a good feature to have!
