### ISSUE TITLE
Is it possible to have more than 16 verbs?

### ISSUE THREAD

**Issue by finnball** [commandlineparser/commandline#239]
I am migrating from v1.9.71 to v 2.2.1 where I have a project which heavily relies on verb usage.

I've managed to successfully parse verbs, though I can't figure out how to parse more than 16.

```
            Parser.Default.ParseArguments
                <VerbOption1,
               // Snip
                VerbOption20>(args)
                .WithParsed<VerbOption1>(opts => Console.WriteLine("One pressed"))
                // Snip
                .WithParsed<VerbOption20>(opts => Console.WriteLine("Twenty pressed"));
```

In v1.9.71, I would do it like this:

```
object invokedVerbInstance = null;
string verb = "";

            if (!Parser.Default.ParseArguments(args, options,
                (verb, subOptions) =>
                {
                    invokedVerb = verb;
                    invokedVerbInstance = subOptions;
                }))
//Followed by a switch statement, triggered on the verb. 
```

Is there a way around this such that I can parse a verb and fire off a function?

**Comment by nemec** [comment]
Have you tried this overload to `ParseArguments`?

    Parser.Default.ParseArguments(args, new[]{ typeof(VerbOption1), ..., typeof(VerbOption20) });

**Comment by finnball** [comment]
Thanks, this worked :) Please close the issue and consider adding this to the wiki as it wasn't clear to me.
