### ISSUE TITLE
TimeSpan parsing

### ISSUE THREAD

**Issue by cdibbs** [commandlineparser/commandline#241]
I see recent commits about getting TimeSpans to parse. Are these included in the 2.2.1 release on NuGet? If so, I cannot get them to work.

```c#
public class Options {
        [Option('t', "timeout", Required = false)]
        public TimeSpan Timeout { get; set; } = TimeSpan.FromHours(24);
}

// ... 
ParserResult<Options> parseResult = Parser.Default.ParseArguments<Options>(args);
```

This throws a bad format error when given "--timeout=15:0:0".

**Comment by nemec** [comment]
Hey @cdibbs those commits were merged into our develop branch but have not made their way into master yet, which our NuGet package is built from. No hard timeline on the next release at the moment.

**Comment by cdibbs** [comment]
@nemec - Alright, thanks! Got confused by the relative timing of 2.2.1.

**Comment by walterX12** [comment]
For me worked format 26.00:00:00 is 26 days, 10:00:00  is 10 hours
