### ISSUE TITLE
Required multiple values

### ISSUE THREAD

**Issue by fvaillancourt** [commandlineparser/commandline#244]
[Option('i', "input", Required = true, Min = 1)]
public IEnumerable< string > Inputs { get; set; }

If no input is provided, it complains that input is missing

[Option('i', "input", Required = true, Min = 1)]
public string[] Inputs { get; set; }

Will not complain and crash later in the code because Inputs is null. (I did not check as it should be impossible to get there...)

**Comment by nemec** [comment]
Good catch, we should fix the error message there. The real error for the second should be `Non scalar properties should be sequence of type IEnumerable<T>.`, aka "we don't support multiple values on a string array"

**Comment by moh-hassan** [comment]
Resolved
The generated Error in HelpText:

>ERROR(S):
Option 'i, input' has no value.
  Required option 'i, input' is missing.
