### ISSUE TITLE
Enum with Flags Attribute

### ISSUE THREAD

**Issue by hallem** [commandlineparser/commandline#247]
I was implementing this in a few of the console applications that I'm building and found that it would be really nice to have Flags support for an Enum. Right now the only solution is to use a collection of Enum values and then parse it out in code. Which is fine, but it would be a really nice to have if the library did that for you.

**Comment by nemec** [comment]
Hi @hallem can you give a few examples of the CLI UI you would expect to see for this feature?

Something like this?

    program --colors "Blue|Yellow"

(the quotes are necessary because `|` and `&` are shell operators)

**Comment by hallem** [comment]
yeah that would work great.

**Comment by YoungCP** [comment]
`--colors Blue,Yellow`, `--colors Blue+Yellow` or even `--colors Blue Yellow` would be preferred for me... maybe make a separator configurable?

**Comment by nemec** [comment]
By the way, this is a workaround to get the behavior in the current system, but it does add an extra property to the options. I imagine it's similar to @hallem's original solution.

```csharp
void Main()
{
	Parser.Default.ParseArguments<Options>("--color Blue Yellow".Split())
	.WithParsed(o => o.BackgroundColor.Dump());
}

class Options
{
	public Color BackgroundColor
	{
		get
		{
			return _BackgroundColors.Aggregate((Color)0, (o, c) => o | c);
		}
	}
	
	[Option('c', "color")]
	public IEnumerable<Color> _BackgroundColors { get; set; }
}

[Flags]
enum Color
{
	Blue = 1,
	Red = 2,
	Yellow = 4
}
```

**Comment by hallem** [comment]
@nemec That's basically what I'm doing now. Was just looking for a cleaner way to do it.

**Comment by ghost** [comment]
@hallem Hi, you found solution?
