### ISSUE TITLE
Getting started, getting stuck

### ISSUE THREAD

**Issue by gbritton1** [commandlineparser/commandline#249]
Trying out this library with a toy example:
```
using CommandLine;
using System;

namespace Test_CommandArgs
{
    class Options
    {
        [Option('a', "optiona", Required = true, HelpText = "Option A")]
        string a {get; set;}
    }

    class Program
    {
        static void Main(string[] args)
        {
            var results = CommandLine.Parser.Default.ParseArguments<Options>(new string[] {});
            Console.WriteLine(results.Tag);
            Console.WriteLine(results.);
        }
    }
}

```

For the last line, I was hoping that VS would show me an attribute that I'd expect to hold a reference to the options object, but I can't see it:

![2018-03-03_8-44-23](https://user-images.githubusercontent.com/12263288/36935011-bbb81176-1ebf-11e8-8011-3c090ca5e890.png)

What am I doing wrong?  How do I get that reference?

**Comment by nemec** [comment]
The `WithParsed` method takes an `Action<Options>` delegate that contains the parsed value.

    results.WithParsed(opt =>
    {
        Console.WriteLine(opt.a);
    }

**Comment by gbritton1** [comment]
Hmmm.  Pity it doesn't expose the parsed value directly, say in a ParserResult.Value property.  This means an awkward (to me) workaround like:

 ```
   class Program
    {
        static void Main(string[] args)
        {
            var results = CommandLine.Parser.Default.ParseArguments<Options>(args);
            results.WithParsed(o => RealMain(o));
            results.WithNotParsed(e =>  
                {
                    foreach(var i in e) Console.WriteLine("Error: " + i); 
                    throw new ArgumentException("Invalid Argument(s).");
                });
        }
        static void RealMain(Options o)
        {
            // Now we really start.
        }
    }
}
```
Also, both approaches are at odds with the example code which looks very nice [https://archive.codeplex.com/?p=commandline](url)

**Comment by gbritton1** [comment]
I see, I need a type cast.  got it

**Comment by cat-prices** [comment]
Agree with this issue, it used to be nice to use and with most recent changes the QuickStart example is wrong. Needs to be more obvious how to get at the parsed values passed in. It's kind of the point of the whole utility. For parsing the arguments.

**Comment by ericnewton76** [comment]
I'm going to weigh in on the very original description, where the OP couldn't get results.a.  This was because the Options type had declared string a without using the "public" access modifier

```c#
    class Options
    {
        [Option('a', "optiona", Required = true, HelpText = "Option A")]
        string a {get; set;}
    }
```

You need a **public** access modifier on that property to get access to that property outside of the Options type.

```c#
    class Options
    {
        [Option('a', "optiona", Required = true, HelpText = "Option A")]
        /**/public/**/ string a {get; set;}
    }
```

Also, when you're looking at archive.codeplex.com for the Quick Start, you're looking at something that is years old.  The Quick Start example works with v2+ of the library, which is what is current.

**Comment by ericnewton76** [comment]
And like @nemec said, you can use the parsed results within the WithParsed method... in gbritton1's example, the fully parsed arguments are passed into the function "RealMain".

You can now easily wrap code within the RealMain code with a try/catch or whatever your design specifications need, with the additional benefit of a fully typed and parsed command line parsed and provided for you as an instance of the Options type.

**Comment by ericnewton76** [comment]
If the quickstart example could be improved for a user that isnt familiar with the library, a pull request would be welcome and thanks in order.
