### ISSUE TITLE
using my own instance (option 2 as per the wiki) writes nothing to the console:

### ISSUE THREAD

**Issue by gbritton1** [commandlineparser/commandline#250]
using my own instance (option 2 as per the wiki) writes nothing to the console:

   ```
 public class Options
    {
        [Option('t', "tacos",
            Default = "desmenuzado", 
            HelpText = "Kind of taco you want")]
        public string Tacos { get; set; }
    }
    public class Program
    {
        public static int  Main(string[] args)
        {
            var testArgs = new string[] {"-b", "burritos"};
            var parser = new Parser(with => with.EnableDashDash = true);
            var result = parser.ParseArguments<Options>(testArgs);
            return result.MapResult(DoIt, _ => 1);
        }

        static int DoIt(Options o)
        {
            Console.WriteLine(o.Tacos);
            return 0;
        }
    }
```

This test should produce an error, but no error is printed on the console.  If I use the default instance (option 1 on the wiki), I do get error messages:
`
var result = Parser.Default.ParseArguments<Options>(testArgs);`

**Comment by nemec** [comment]
Hello @gbritton1, the default parser sets up some "default" settings as well that aren't included when initializing it yourself. You have two options:

1. Print the details yourself using that second delegate to `MapResult` (`_` is of type `IEnumerable<Error>` and you can get the details from there)
2. Set the HelpWriter property to the Console (I imagine this is what you are looking for)

```csharp
var parser = new Parser(with =>
{
    with.EnableDashDash = true;
    with.HelpWriter = Console.Out;
});
```

Hope this helps :)

**Comment by moh-hassan** [comment]
It's working fine.
