### ISSUE TITLE
Solution won't build

### ISSUE THREAD

**Issue by gbritton1** [commandlineparser/commandline#263]
I'm trying to build the solution on my own box.  It won't build due to nuget errors:

> Dependency '"CommandLine": {
>   "target": "project"
> }' has invalid version specification.

and

> Error occurred while restoring NuGet packages: Invalid restore input. UAP projects must contain exactly one target framework. Input files: C:\Users\Jerry\Source\Repos\commandline\tests\CommandLine.Tests\CommandLine.Tests.csproj, C:\Users\Jerry\Source\Repos\commandline\tests\CommandLine.Tests\project.json.

So, how is one supposed to build it?

**Comment by nemec** [comment]
That is very weird, this isn't a UAP project so I'm not sure why the compiler thinks it is.

What version of VS are you using? Trying to use it with a regular framework or core app? 

It sounds like it's trying to use both project files at the same time. Maybe temporarily you can delete the one you aren't using

**Comment by gbritton1** [comment]
VS 2017, I didn't specify a framework.  I just cloned the repo and tried to build it.  I suspect its the test project that is causing the problems.

Update: Unloading the test project then building the project worked.  So we have the culprit
