### ISSUE TITLE
Ability to customize version

### ISSUE THREAD

**Issue by mdentremont** [commandlineparser/commandline#266]
I cannot seem to appropriately  configure the version number, the best I'm able to get is:
```
static void Main(string[] args)
        {
            var parserResult = Parser.Default.ParseArguments<SimulatorArguments>(args);

            parserResult
                .WithNotParsed(errs =>
                {
                    var helpText = HelpText.AutoBuild(parserResult);
                    helpText.Heading = new HeadingInfo("Project Name", "some version");
                    System.Console.Error.Write(helpText);
                })
...
```

But with this the assembly name & assembly version are prepended to the version in the output:
```
$ theProgram.exe --version
TheProject 1.0.0.0Project Name some version
Copyright...
```

**Comment by gbritton1** [comment]
I think that's in your project properties/Application/Assembly info

**Comment by mdentremont** [comment]
@gbritton1 In our project we populate the versions using the git tag, so we don't make changes to AssemblyInfo.cs

**Comment by gbritton1** [comment]
You could though, and its not a bad idea.   if you look at the properties of your executable, e.g. File Explorer, you'll see the assembly version.  That's generally a good idea.  How will File Explorer (and others)  see your git-tag based versions?
