### ISSUE TITLE
Has dependencies? 

### ISSUE THREAD

**Issue by m-sterspace** [commandlineparser/commandline#267]
I'm a little confused. It says that this package has no dependencies and that you can include the CSharp files in your project, however, I'm unable to get this working. It seems to be using / referencing CSharpx and RailwaySharp which both appear to be unrelated projects. I'm producing a simple portable utility so would ideally like to avoid having to install a separate dll for this, but could anyone provide some guidance on how you're supposed to embed the .cs files directly in a .net framework project?

**Comment by nemec** [comment]
See #251 - the 'no dependencies' promise only applies to the final NuGet package, not the intermediate build steps. `CSharpx` and `RailwaySharp` are both written by the original author of `commandlineparser` and I don't know why he decided to make them separate repositories. You should be able to copy over those files too into your project

I would also highly recommend utilizing [ILMerge](https://github.com/Microsoft/ILMerge) - it will take multiple DLLs and combine them into a single DLL/EXE - that way you can use any Nuget package and still retain a single EXE when deployed.
