### ISSUE TITLE
Support double dash to terminate options

### ISSUE THREAD

**Issue by RedX2501** [commandlineparser/commandline#270]
Does commandline support using double dash to terminate option parse and indicate that the rest will be unparsed?

For example git has this option to disambiguate between file names and refs:

    git checkout this-is-a-branch

will interpret `this-is-a-branch` as a branch name if it exists. If it does not exist it is tried as a filename.

    git checkout -- this-is-a-branch

will unambiguously identify `this-is-a-branch` as a filename.

Or if you have a tool that takes positional arguments

    dosomething -somebody-created-a-file-that-starts-with-a-dash

Now I can't really pass this filename in because it will try to parse `-s` as an option.

Using `--` this becomes possible:

    dosomething -- -somebody-created-a-file-that-starts-with-a-dash

This is even specified in POSIX command line handling: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

> Guideline 10:
>     The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

**Comment by nemec** [comment]
Try the `EnableDashDash` option in the parser configuration. The default parser is not configured to use the double dash feature.

```csharp
void Main()
{
	var p = new Parser(conf => {
		conf.EnableDashDash = true;
	});
	var parserResult = p.ParseArguments<Options>("-- --name 10".Split());

	parserResult.WithParsed<Options>(options => options.Dump());
	parserResult.WithNotParsed<Options>(errs => errs.Dump());
}

class Options
{
	[Option('n', "name")]
	public string Name { get; set; }
	
	[CommandLine.Value(0)]
	public IEnumerable<string> Thing { get; set; }
}
```

**Comment by RedX2501** [comment]
This bug #156 is very annoying and makes handling a single expected value a bit annoying in conjunction with DashDash but I guess the original issue is implemented.
