### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by Rohansi** [commandlineparser/commandline#284]
.NET Standard 2.0 is much more consistent across runtimes and shouldn't need to install 10+ dependencies when used in full .NET Framework or .NET Core projects.

There shouldn't be any need to change code, only the csproj to target an additional platform.

**Comment by Rohansi** [comment]
The csproj and project.json files could maybe be replaced by the new csproj format to make this all easier. [This table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) shows which runtimes the different .NET Standard levels support.

**Comment by ericnewton76** [comment]
I was definitely considering it now that higher standard frameworks are in the wild at this point. Might not make the end of may rrlease but probably soon after

**Comment by andrewaggb** [comment]
I'd certainly prefer it as well.  I've been using an older fork for some time and tried to update to this version and backed out because it pulled in many deps.  netstandard 2 is much cleaner.

**Comment by SidShaytay** [comment]
Any idea when .net standard 2.0 targets will be released? It's coming down with a lot of dependencies right now.

**Comment by ericnewton76** [comment]
I’m gonna try to find some time soon. Been a lot going on and trying to find an outdoor cat that I miss a lot

**Comment by ericnewton76** [comment]
Newest version supporting Net Standard 2.0 is now built and published.

https://www.nuget.org/packages/CommandLineParser/2.4.3

https://github.com/commandlineparser/commandline/releases/tag/v2.4.3
