### ISSUE TITLE
Option of nullable enum type failing to parse

### ISSUE THREAD

**Issue by sierramike** [commandlineparser/commandline#287]
Hi,

First, I want to really thank the author(s) for their wonderful work on this framework!

But, I have one small issue that is really annoying. I have an option of nullable enum type:

    [Option("delayif", HelpText = "Sets the delay application trigger")]
    public StartMode? DelayIF { get; set; }

`StartMode` is an enum. I want `DelayIF` property to be null if argument is not passed in command line.

I actually do NOT want to have a default value, but really have a null value.

When executing, calling `myapp.exe --delayif none` results with an error:

    Option 'delayif' is defined with a bad format.

Removing the nullable type resolves the issue.

So, I'm using the workaround of adding a "NotSet" value in the Enum, and using it as a default in the options class, but this causes the help screen to show `(Default: NotSet)`, which I do not want.

Would be really helpful if this bug could be addressed, thanks!

**Comment by ericnewton76** [comment]
I believe this is a known issue. Might even be a PR that is submitted to address it. I’m currently a bit tied up so if you could look through older issues and PRs and make a reference to them here would be very helpful. 

I’m actually targeting a new release sometime end of may

**Comment by paultechguy** [comment]
Would love to see a nullable enum working.

**Comment by feliwir** [comment]
Can this be fixed please?

**Comment by moh-hassan** [comment]
It's resolved in v2.6.0
