### ISSUE TITLE
passing multiple verbs

### ISSUE THREAD

**Issue by raaj-repos** [commandlineparser/commandline#291]
Is it possible to pass multiple verbs in one single command line. We are using a console app to update couple of connection string  and app settings.

**Comment by nemec** [comment]
No it is not possible. Once you 'enter' a verb you cannot leave it again.

**Comment by raaj-repos** [comment]
Is there any alternate way I could try? We give this console to DevOps and they would run the script. They would not like to run the script twice since it got lots of stuff which we cannot run twice.

**Comment by nemec** [comment]
I can think of two options, do either of these sound feasible for your use case?

1. Refactor the work that cannot be done twice into another verb, then run a sequence of commands (e.g. in a shell script)
  * `app.exe prework --argument`
  * `app.exe adduser --name fred`
  * `app.exe adduser --name bob`
  * (repeat, etc.)
2. Change the connection string variable (and any others) to an `IEnumerable`, which would allow you to pass multiple values to the property in one execution. Then loop through and apply your verb actions to each of those values
  * `app.exe myverb --connection "192.168.1.10:2378" "192.168.1.5:8765"`

**Comment by fm611** [comment]
I did it with parsing the remaining arguments again:

Options Classes:

``` 
    class FirstVerb
    {
        [Value(0)]
        public IEnumerable<string> SubArgs { get; set; }
    }

    [Verb("second", HelpText = "Add file contents to the index.")]
    class SecondVerb
    {
        [Value(0)]
        public IEnumerable<string> SubArgs { get; set; }
    }

    [Verb("subParseONE", HelpText = "Add file contents to the index.")]
    class SubParseOne
    {
        [Value(0)]
        public string Value { get; set; }
    }

    [Verb("subParseTWO", HelpText = "Add file contents to the index.")]
    class SubParseTwo
    {
        [Value(0)]
        public int Value { get; set; }
    }
```

Console Class:

```
        static void Main(string[] args)
        {
            var result = Parser.Default.ParseArguments<FirstVerb, SecondVerb>(args)
                .WithParsed<FirstVerb>(FirstParseMethod);
        }

        private static void FirstParseMethod(FirstVerb parsedArgs)
        {
            Parser.Default.ParseArguments<SubParseOne, SubParseTwo>(parsedArgs.SubArgs)
                .WithParsed<SubParseOne>(SubParseONEMethod)
                .WithParsed<SubParseTwo>(SubParseTWOMethod);
        }

        private static void SubParseONEMethod(SubParseOne parsedArgs)
        {
            Console.WriteLine(parsedArgs.Value);
        }
        private static void SubParseTWOMethod(SubParseTwo parsedArgs)
        {
            Console.WriteLine(parsedArgs.Value);
        }
```

But you need at least two different verbs regarding #217
