### ISSUE TITLE
"Option 'version' is unknown" when using Environment.GetCommandLineArgs()

### ISSUE THREAD

**Issue by JVimes** [commandlineparser/commandline#293]
When parsing `Environment.GetCommandLineArgs()`, the built-in `--version` option gives "Option 'version' is unknown". Should print version info.

Repro:
```c#
using CommandLine;
class Program
{
    class CommandLineOptions { }

    public static void Main(string[] args)
    {
        var myArgs = Environment.GetCommandLineArgs();
        // Note: I'm parsing myArgs, not args
        var result = Parser.Default.ParseArguments<CommandLineOptions>(myArgs);
    }
}
```
Actual result:
```PowerShell
PS> .\ConsoleApp1.exe --version
ConsoleApp1 1.0.0.0
Copyright c  2017
ERROR(S):
Option 'version' is unknown.

  --help       Display this help screen.

  --version    Display version information.
```

Expected result (switch from `myArgs` to `args`):
```PowerShell
PS> .\ConsoleApp1.exe --version
ConsoleApp1 1.0.0.0
```

Note: my use case is a WPF app, trying to parse arguments without creating a Main().

**Comment by nemec** [comment]
Can you try:

        var result = Parser.Default.ParseArguments<CommandLineOptions>(myArgs.Skip(1));

`GetCommandLineArgs` adds the program name at the beginning of the array which isn't accounted for in `Main(string[] args)`.

**Comment by JVimes** [comment]
That did it. Thanks!
