### ISSUE TITLE
Lots of NuGet dependencies when .NET version >4.6

### ISSUE THREAD

**Issue by JVimes** [commandlineparser/commandline#295]
When I install CommandLineParser in a project targeting a .NET version greater than 4.6, I get many extra packages brought in:

![image](https://user-images.githubusercontent.com/6148201/40686392-6757eca8-6354-11e8-8be7-5f984041bd00.png)

Can this be avoided? Is it the situation described [here](https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies)? Thanks.

**Comment by nemec** [comment]
Yes, it is the same situation you linked to. This is a factor of the library using .net standard pre-2.0. The issue is tracked in #227
