### ISSUE TITLE
Readloop for non set required parameters

### ISSUE THREAD

**Issue by StefanKert** [commandlineparser/commandline#296]
First of all thanks for the great work you did and are doing with CommandLineParser. It is a great utility we really often use in our daily work.

One thing that I am missing (probably I am just overlooking this feature) is the possibility to trigger a loop that asks for all required parameters similar to powershell:

![image](https://user-images.githubusercontent.com/7176615/40965847-2b046f5a-68af-11e8-9229-ec24aeea379d.png)

We already implemented some basic functionality to achieve this and I would be glad to do a Pull Request on this to get this into CommandLineParser by default. But before doing that I wanted to ask if this is already possible and if it makes sense to you to add this functionality.

If it makes sense to add this we can probably start a discussion on how this can be achieved or if there are any better ways than "loop + readline".

**Comment by bugproof** [comment]
That would be good
