### ISSUE TITLE
change in FlatternHierarchy method 

### ISSUE THREAD

**Issue by rlsf** [commandlineparser/commandline#299]
Hello,
The current implementation of FlatternHierarchy method returns the current type first.
This in turn causes the help routine to print the options/values attributes of the current type before inherited types.
From my point of view, however, the current type should be returned last, so common options/values which are declared in the base class will appear first in the help message.

example:

```
public class CliBase
{
  [Option("opt1")]
  public string Opt1 { get; set; }
}

public class CliCommand : CliBase
{
  [Option("opt2")]
  public string Opt2 { get; set; }
}
```

printing the help information for CliCommand, will result in opt2 being printed before opt1, while i expect the reverse order, so any new command inheriting from CliBase will have opt1 printed first.

the actual code change is in FlattenHierarchy method, instead of current implementation, use this one:

```
private static IEnumerable<Type> FlattenHierarchy(this Type type)
{
	if (type == null)
	{
		yield break;
	}

	foreach (var @interface in type.SafeGetInterfaces())
	{
		yield return @interface;
	}
	foreach (var @interface in FlattenHierarchy(type.BaseType))
	{
		yield return @interface;
	}
	yield return type;
}
```

**Comment by nemec** [comment]
Do you have an example of any negative consequences of showing the current type's members first in a scenario with a base class and multiple derived classes?

**Comment by rlsf** [comment]
in my eyes, it goes against the common logic: if i define a base class for
a set of commands, it's because it contains common options and values.
those options and values are more likely to be required ones.
i would expect those common required options/values to appear first, before
any command specific required or optional options and values.

e.g.


public class ProjectBaseCommand
{
  [Option('p', "project", HelpText = "project name", Required = true)]
  public string Project { get; set; }
}

[Verb("action")]
public class ProjectActionCommand : ProjectBaseCommand
{
  [Option('a', "action_name", HelpText = "project action")]
  public string ActionName { get; set; }
}

[Verb("export")]
public class ProjectExportCommand : ProjectBaseCommand
{
  [Option('f', "export_file")]
  public string ExportFile { get; set; }
}


with this code, although only the base class qualifier is mandatory, it
will be printed last in the help message of both commands, if the commands'
qualifier list is extended, the required qualifier will be the last to be
listed, although it is mandatory, after any mandatory/optional qualifier of
the derived class.

RL
