### ISSUE TITLE
Specifying that an Option requires another Option

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#3]
<a href="https://github.com/st1led"><img src="https://avatars2.githubusercontent.com/u/4096687?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [st1led](https://github.com/st1led)**
_Tuesday Apr 09, 2013 at 09:55 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/76_

----

Hi everybody, is there a way in CommandLine (I guess in a way similar to what is done with mutually exclusive properties) to specify that an option requires another option to be set? This is a short example:

```
        [Option('v', "verbose",
            Required = false,
            DefaultValue = false,
            HelpText = "Prints log messages.")]
        public bool Verbose { get; set; }

        [Option('o', "optional-operation",
            Required = false,
            DefaultValue = false,
            HelpText = "Performs an operation (a.k.a. \"does something\") in the code.")]
        public bool PerformOperation { get; set; }

        [Option('t', "time-limit",
            Required = false,
            DefaultValue = false,
            HelpText = "Requires option -o. Specifies a time limit for the optional operation")]
        public int OperationTimeLimit { get; set; }
```

In this scenario, one would want to allow command line arguments like `-o` and `-vot` but not `-vt` or `-t` for instance, since in the latter the option `-t` is specified without `-o`. Is this currently possible in CommandLine?

Regards,
Stefano

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Wednesday Apr 10, 2013 at 06:46 GMT_

----

Hi, @st1led,
I'm sorry but I'm not sure to understand what you want to get...

Can you be so kind to reformulate your question telling ___what you're not able to get__ and than explaining **what you want to get**?

Regards, Giacomo

**Comment by ericnewton76** [comment]
<a href="https://github.com/st1led"><img src="https://avatars2.githubusercontent.com/u/4096687?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [st1led](https://github.com/st1led)**
_Wednesday Apr 10, 2013 at 08:03 GMT_

----

Thank you for your support, I'll try to reformulate the question in a clearer way. I would like to know if CommandLine offers some API for a behavior like the following one:

```
        [Option('v', "verbose",
            Required = false,
            DefaultValue = false,
            HelpText = "Prints log messages.")]
        public bool Verbose { get; set; }

        [Option('o', "optional-operation",
            Required = false,
            DefaultValue = false,
            HelpText = "Performs an operation (a.k.a. \"does something\") in the code.")]
        public bool PerformOperation { get; set; }

        [Option('t', "time-limit",
            Required = false,
            RequiresOptions = {"optional-operation"},
            DefaultValue = false,
            HelpText = "Requires option -o. Specifies a time limit for the optional operation")]
        public int OperationTimeLimit { get; set; }
```

Note that in this example I defined option `-t` with an hypothetical parameter `RequiresOptions`, specifying that calling the program with the argument `-t` without having set the argument `-o` leads to a parsing error.  This is what I meant in the first post as "Specifying that an Option requires another Option".

To achieve this behavior, I have to manually write some code in my program to check if arguments have been correctly set. Since I can't find any way to do it in CommandLine, I'm asking if such feature exists, or is planned for future versions and if not... Would it be a good idea for future CommandLine versions? To me having dependencies between arguments sounds like a pretty common scenario.

Regards,
Stefano

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Apr 10, 2013 at 16:17 GMT_

----

I think that it's a good idea. I'm not sure what kind of syntax you were going for with `{"other-stuff"}`, but it could be made into an array of strings.

A couple potential issues: What if the option you depend on doesn't have a long option? If an option defines both a short and long option, which do you use?

**Comment by ericnewton76** [comment]
<a href="https://github.com/st1led"><img src="https://avatars2.githubusercontent.com/u/4096687?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [st1led](https://github.com/st1led)**
_Wednesday Apr 10, 2013 at 16:34 GMT_

----

The syntax was just an attempt to specify an array of identifiers representing the options (just `o` in the example) that current option (`t` in the example) depends on.

Since an Option can specify either a long or a short name, there would be the need to add a new parameter (named `Identifier`), unique for each Option. In this way `RequiredOptions` would be an array of the same type as `Identifier`.

I guess `Identifier` could be a simple integer, or a string, or maybe a more complicated object encapsulating the long and short name of an Option.

Regards,
Stefano

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Apr 10, 2013 at 20:37 GMT_

----

I'm inclined to recommend using the property name itself (e.g. `PerformOperation`). If you define an option without either a short or long identifier, the parameter name is determined using [reflection](https://github.com/gsscoder/commandline/wiki/Mapping-Properties-To-Options#implicit-name) already.

**Comment by ericnewton76** [comment]
<a href="https://github.com/st1led"><img src="https://avatars2.githubusercontent.com/u/4096687?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [st1led](https://github.com/st1led)**
_Wednesday Apr 10, 2013 at 21:03 GMT_

----

Using the property name sounds like a brilliant idea to me. This way the `RequiresOptions` parameter can be defined as an array of strings, each being the property name of the required option. No need to add further parameters, then.

Regards,
Stefano

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Apr 10, 2013 at 21:16 GMT_

----

If only delegates were allowed as arguments to an attribute... you could do so much with strong typing.

```
[DependsOn<Config>(c => c.PerformOperation)]
public int OperationTimeLimit { get; set; }
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/shengqh"><img src="https://avatars0.githubusercontent.com/u/2760757?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shengqh](https://github.com/shengqh)**
_Friday Apr 19, 2013 at 14:54 GMT_

----

Is there any news about this feature? I met such problem too.

**Comment by ericnewton76** [comment]
<a href="https://github.com/Mizipzor"><img src="https://avatars1.githubusercontent.com/u/139879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mizipzor](https://github.com/Mizipzor)**
_Thursday Jan 28, 2016 at 12:04 GMT_

----

To me it makes more sense allowing a _time-limit_ to be set, even if the _optional-operation_ is **not** set. The time limit would then just be ignored by the program. And if you want to enforce this dependency it's a trivial check to do after parsing. I don't think the increased parsing complexity is worth it to provide this functionality built in.

Can we find some other program that behaves this way, with argument dependencies?

**Comment by IanKemp** [comment]
So... how do we do this? I can't see anything in the wiki that indicates that this feature is available.

**Comment by rmeshksar** [comment]
Why is this issue closed? Is there anyway to do it now that is not documented?
