### ISSUE TITLE
Assembly 'commandline' has non matching file name: 'CommandLine.dll'. This can cause build issues on some platforms.

### ISSUE THREAD

**Issue by johnburkert** [commandlineparser/commandline#306]
Unity gives this error when using the v2.2.1 netstandard1.5 dll from NuGet. The netstandard1.5 dll has "commandline.dll" as the "Original filename" in the "Properties -> Details" tab.  The net40 and net45 dlls have "CommandLine.dll" as the "Original filename".

**Comment by ericnewton76** [comment]
With #307 PR merged to move to Net Standard 2.0, is this still an issue?
