### ISSUE TITLE
How to include spaces in command-line argument?

### ISSUE THREAD

**Issue by backspacer80** [commandlineparser/commandline#308]
I am trying to pass a command-line argument that contains spaces. I would expect that this can be achieved by using quotes but it's not possible. Is this a bug or is there a different way to include spaces?

My code:

```
    [Verb("test")]
    class TestAction
    {
        [Value(0, Required = true, MetaName = "message", HelpText = "Specify the message here")]
        public string Message { get; set; }
    }

```
Below is the printed output for the Message property when providing different values:

```
test this_is_a_message
this_is_a_message
test this is a message
this
test "this is a message"
"this
```

**Comment by nemec** [comment]
What does your program (relevant to the parser) look like? It absolutely handles spaces.

**Comment by backspacer80** [comment]
The program passes input into a preprocessor. After your answer I realised that it was our preprocessor that did not handle the spaces correctly. My apologies!
