### ISSUE TITLE
Parse struct/classes

### ISSUE THREAD

**Issue by ghost** [commandlineparser/commandline#309]
How i can parse this:

```

    class TestParseObject
    {
        [Option('e', "read", Required = true, HelpText = "Input files to be processed.")]
        public IEnumerable<string> SomeStrings { get; set; }

        [Option('t', "timeout", Required = true)]
        public int Delay { get; set; }

        [Option('s', "hard", Required = true)]
        public SimpleHard Object { get; set; }
    }

    public class SimpleHard
    {
        [Value(0)] public int Price { get; set; }
    }
```

input string:
```
  var args = new[]
            {
                "-e", "s", "b", "-t", "24","-s","22"
            };


```
_

> Where -e s b -t 24 work correct, but how parse struct/class?

_

**Comment by moh-hassan** [comment]
The class `SimpleHard `should have a constructor that accepts a string, so this is working:

		 public class SimpleHard
			{
				public int Price { get; set; }
				public SimpleHard(string number)
				{
					Int32.TryParse(number, out int j);
					Price = j;
				}
			}


For the args: -e s b -t 24 -s 22 
the option TestParseObject.Object.Price will be evaluated to 22
