### ISSUE TITLE
Add .NETFramework 3.5 as a target framework

### ISSUE THREAD

**Issue by estrizhok** [commandlineparser/commandline#310]
Could you please consider compiling your awesome library for net35? Yes, it is old, but there are people who still have to use it.

**Comment by ericnewton76** [comment]
That's unfortunate, being stuck on 3.5!

I'll see what can be done.  There's already some traction for better multi targeting.

In the meantime, can you build the project under 3.5 ?  What problems do you see?

**Comment by estrizhok** [comment]
Thank you for looking at the issue!

Actually, I have already tried to and succeeded in compiling it for 3.5. I had to replace all `string.IsNullOrWhitespace` with `string.IsNullOrEmpty`, and change how default value for a given type is calculated (for there is no `DefaultExpression` in NET3.5). There were some other changes related to co-/contravariance, but nothing serious, and all the tests passed.

I wanted to propose it as pull request, but couldn't figure out from the first glance how you generate a nuget package targeting different frameworks. And then got distracted :)

**Comment by moh-hassan** [comment]
JFI, Microsoft has stoped the support of .NETFramework 3.5
REf: [Lifecycle FAQ—.NET Framework](https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework)
It's better to plan of upgrading application running .net3.5 to .net4.5+

**Comment by ericnewton76** [comment]
Newest release 2.4.3 supports Net standard 2.0 which I know is much beyond Framework 3.5 and even Framework 4.5.

A PR or help to keep that backward compatibility going would help.  I dont even have VS2015 on my machine anymore to double check this.

**Comment by NN---** [comment]
@moh-hassan .NET 3.5 is supported.
Check here: https://support.microsoft.com/en-us/lifecycle/search/548

.NET Framework 3.5 Service Pack 1 
Mainstream Support End Date: 10/10/2023
Extended Support End Date: 10/10/2028

Also in your link it is clearly stated that it is supported
```
.NET Framework 3.5 SP1, beginning with Windows 10 version 1809 and Windows Server 2019, is a standalone product and receives 5 years of mainstream support followed by 5 years of extended support. For operating systems released prior to Windows 10 version 1809 and Windows Server 2019, .NET 3.5 SP1 remains a component of the Windows version on which it is installed.
```

**Comment by NN---** [comment]
You can use [Theraot](https://github.com/theraot/Theraot) library for older .NET versions support.

**Comment by moh-hassan** [comment]
Closed for age.
