### ISSUE TITLE
Where and why this option error.

### ISSUE THREAD

**Issue by moh-hassan** [commandlineparser/commandline#320]
In CommandLineParser  v2.3, a  run-time Exception message is fired

>Run-time exception : Sequence contains more than one matching element

  That is the option class:
  
		public class Options
              {
            [Option('r', "read", MetaValue = "FILE", Required = false, HelpText = "Input file with data to process.")]
            public string InputFile { get; set; }

            [Option('w', "write", MetaValue = "FILE",
                HelpText = "Output FILE with processed data (otherwise standard output).")]
            public string OutputFile { get; set; }

            [Option('c', "calculate", HelpText = "Add results in bottom of tabular data.")]
            public bool Calculate { get; set; }

            [Option('v', MetaValue = "INT", HelpText = "Verbose level. Range: from 0 to 2.")]
            public int? VerboseLevel { get; set; }

		//Run-time exception: Sequence contains more than one matching element
              // option with shortName only, no longName is provided
            [Option('i', HelpText = "If file has errors don't stop processing.")]  
            public bool IgnoreErrors { get; set; }
          
        }
               
      1- what the option that raise this exception?
	     It's a nice if the error message contain the name of the option property 'IgnoreErrors' to help a quick fix for the error.
		
	  2- I found that providing only shortName (without longName) raise this exception which is a misleading error message.
	    How this error message express the error of the option IgnoreErrors?

 Check   [the demo](https://dotnetfiddle.net/ZPxoHQ)

**Comment by nemec** [comment]
This one is pretty odd, looks like a bug to me. It should be possible to define an option with just `'i'`

**Comment by moh-hassan** [comment]
@nemec 
The bug is resolved :)
The root problem  was an extra space in the commandLine args which causes the misleading error message, especially when providing both shortName and longName, it works fine.

I useded RemoveEmptyEntries in splitting the string to remove the extra spaces in commandline args.

Now, it's working fine after modification.
Check the [Working Demo ](https://dotnetfiddle.net/bk3mMq)

Really, as you said, It should be possible to define an option with just 'i'

But, the question , How the parser give different exceptions based on providing shortName, longName in case of  extra spaces in the commandline args.
(kindly, review the comments of the different cases of the option  in the   [old demo.](https://dotnetfiddle.net/ZPxoHQ)

Thanks.
