### ISSUE TITLE
Localization and SentenceBuilder

### ISSUE THREAD

**Issue by SpawnProd** [commandlineparser/commandline#321]
In current version we can't localize a few things.
"Default" word, "Valid values", "pos.", "value pos."...
Everything we can put in SentenceBuilder I suppose.
Also it's not clearly for me, why you use RequireWord as parameter (in AddOptionsImpl function for example).

**Comment by SpawnProd** [comment]
I can do it by myself (just finished), but can I change sdk version for .Net Core build? Current version "1.0.0-preview2-003121" a little bit ancient...
Also, for nupkg in CommandLine.nuspec will be great to change dependency version from "4.0.11-rc2-24027" to "4.3" (without changing .Net Standard). (Issue #297 )

**Comment by moh-hassan** [comment]
Localization is supported in v2.6.0
A localization demo is [available](https://github.com/commandlineparser/commandline/tree/master/demo/ReadText.LocalizedDemo)
