### ISSUE TITLE
Documentation of the Usage annotation

### ISSUE THREAD

**Issue by blelem** [commandlineparser/commandline#328]
As a new user of the commanline library, I found it a little difficult to work out how the [Usage] annotation worked. The currently provided example in the wiki is quite rapidly covering nitty gritty details that are perhaps more confusing than helping for beginners.

I edited the *Usage Attribute* section in the wiki with a new super simple example to get newbies started. 
Here is my update: 
https://github.com/blelem/commandline/wiki

Perhaps that edit could be merged to the official wiki?

**Comment by nemec** [comment]
Hi @blelem the new Usage section look good to me. I believe Github wikis are editable by any Github user, so you are welcome to add the changed text yourself (the github diff shows the entire page being added at once, so it's a bit difficult for me to see what sentences you changed vs. what was already there).

**Comment by blelem** [comment]
I can't find a way to edit. Maybe I don't have needed rights? According to github https://help.github.com/articles/about-github-wikis/  :

>By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.

**Comment by nemec** [comment]
Ok I manually coped over your Usage section to replace the existing one. Thank you for contributing to this project!
