### ISSUE TITLE
FormatCommandLine options in correct order

### ISSUE THREAD

**Issue by mbullock976** [commandlineparser/commandline#329]
Hi

Is it possible I can run FormatCommandLine for the options below, so that the commandline output is in the order of the properties specified below? In my example below "fflags" switch appears first when I want it to be appear in the order specified below. I.e So that -protocol_whitelist appears first

Thank you

`
class Options
    {        
        [Option("protocol_whitelist", Separator = ',')]
        public IEnumerable<string> ProtocolWhitelist { get; set; }

        [Option("re")]        
        public bool InputStreamAsNativeFrameRate { get; set; } = true;
     
        [Option("fflags")]
        public string FormatFlags { get; set; } = "+genpts";

        [Option("use_wallclock_as_timestamps")]
        public int ApplyTimestampsToInputFrames { get; set; } = 1;

    }
`

I get the following output:

--fflags +genpts --protocol_whitelist file,udp,rtp,tcp,http --re --use_wallclock_as_timestamps 1

I want to to be:

--protocol_whitelist file,udp,rtp,tcp,http --re --fflags +genpts --use_wallclock_as_timestamps 1

**Comment by mbullock976** [comment]
It looks like I've managed to get around this issue by specifying a short name in alphabetical order to force the ordering.

`class Options
    {
        [Option('a',"protocol_whitelist", Separator = ',')]
        public IEnumerable<string> ProtocolWhitelist { get; set; }

        [Option('b', "re")]
        public bool InputStreamAsNativeFrameRate { get; set; } = true;

        [Option('c',"fflags")]
        public string FormatFlags { get; set; } = "+genpts";

        [Option('d', "use_wallclock_as_timestamps")]
        public int ApplyTimestampsToInputFrames { get; set; } = 1;

        [Option('e',"i")]
        public string InputStream { get; set; }
    }`

**Comment by nemec** [comment]
There is no option to order by when the property "appears" in the class body. In fact, from what I've read there is no guarantee that Reflection will return properties in the same order on all operating systems, so we don't rely on that.

I am glad you found a workaround that solves your need.
