### ISSUE TITLE
Default usage display

### ISSUE THREAD

**Issue by ShadowDancer** [commandlineparser/commandline#336]
I think it would be nice if help screen displayed by default list of usages, just like windows many system commands do (ex. dir /?). For example:

// current output
```
MyApp.exe help
MyApp 1.0.0
Copyright (C) 2018 MyApp 

  verb1    Help text for verb 1
  verb2    Help text for verb 2
  help             Display more information on a specific command.
  version          Display version information.
```

// would be nice output
```
MyApp 1.0.0
Copyright (C) 2018 MyApp 

Example usage:
MyApp verb1 -verb1switch -verb1switch2
MyApp verb2 -verb2switch -verb2switch2 -verb2collection:verb2collection2

  verb1    Help text for verb 1
  verb2    Help text for verb 2
  help             Display more information on a specific command.
  version          Display version information.
```

// help for verb
```
MyApp 1.0.0
Copyright (C) 2018 MyApp 

Example usage: // could also support sets, not pictured
MyApp verb1 -verb1switch -verb1switch2

  --verb1switch Help text for verb1switch
  --verb1switch2 Help text for verb1switch
  help             Display more information on a specific command.
  version          Display version information. -- why this is here???
```

**Comment by nemec** [comment]
Have you tried adding 'examples' to your class [like the following](https://github.com/commandlineparser/commandline/blob/67f77e1232a1db6e11d0fa528726e35d307dd63f/demo/ReadText.Demo/Options.cs#L41-L51)?

    class HeadOptions
    {
        [Usage(ApplicationAlias = "ReadText.Demo.exe")]
        public static IEnumerable<Example> Examples
        {
            get
            {
                yield return new Example("normal scenario", new HeadOptions { FileName = "file.bin"});
                yield return new Example("specify bytes", new HeadOptions { FileName = "file.bin", Bytes=100 });
                yield return new Example("suppress summary", UnParserSettings.WithGroupSwitchesOnly(), new HeadOptions { FileName = "file.bin", Quiet = true });
                yield return new Example("read more lines", new[] { UnParserSettings.WithGroupSwitchesOnly(), UnParserSettings.WithUseEqualTokenOnly() }, new HeadOptions { FileName = "file.bin", Lines = 10 });
            }
        }
    }

**Comment by ShadowDancer** [comment]
I think it should be generated automatically. Examples are for examples, and switch list is for copying to terminal.

Examples are good tool if You have multiple sets doing different things, however if You have single "thing" with multiple switches Examples are not that good. Also they have to be written manually.
