### ISSUE TITLE
Not all types with a string constructor can be used

### ISSUE THREAD

**Issue by shmuelie** [commandlineparser/commandline#339]
The README states:

> You can also map to every type with a constructor that accepts a string (like System.Uri).

That's not true, as the code does a check and only classes with a constructor that except a string will be used. If the type is a struct/value type the constructor will not be used. While I'd like this to be changed to match the README and work for value types too, at least update the README please.

Thanks

**Comment by fromm1990** [comment]
I have arrived at the same conclusion myself. Structs with a constructor that takes a single string parameter throws the following exception: 

> System.NotSupportedException: 'TypeConverter cannot convert from System.String.'

**Sidenote**
I find the need to have a constructor that takes a string parameter a bit constraining as this requires wrapper classes for already existing types found in libraries. I would imagine, that it would be possible to add support for type converters. A type converter, could be as simple as Func<string, T>. The user should then be able to register a type converter and associate it to the type it is supposed to handle. This way, it is possible to add support for already existing classes/structs.

**Comment by moh-hassan** [comment]
Fixed in v2.8.0
