### ISSUE TITLE
How do I handle the situation when parsing failed using a simple if-else condition block?

### ISSUE THREAD

**Issue by sdg002** [commandlineparser/commandline#342]
This is what I have understood so far. I wonder if this if-else comparison is correct. Appears to work .

            var result = CommandLine.Parser.Default.ParseArguments<MyCmdline>(args);
            if (result is CommandLine.NotParsed<MyCmdline>)
            {
                Console.WriteLine("Invalid command line");                
                return;
            }
            MyCmdline cmdline = (result as CommandLine.Parsed<MyCmdline>).Value;

**Comment by moh-hassan** [comment]
Your code is working, but you had to Cast to get `cmdline` and also you had to cast to get the parsing errors.

You can avoid casting and do the same if..then using the Parser extension methods, by rewriting  your code  as:

		    var result = CommandLine.Parser.Default.ParseArguments<MyCmdline>(args);
			result.WithParsed<MyCmdline>(o =>
						   {
							  //you needn't casting to get 'cmdline'
							 //MyCmdline cmdline = (result as CommandLine.Parsed<MyCmdline>).Value;
							 MyCmdline cmdline = o;
						   })
				.WithNotParsed<MyCmdline>(errs =>	
					{
							Console.WriteLine("Invalid command line");    
                                                        //you can handle  errs,             
							return;
					});

**Comment by nemec** [comment]
Yes, @moh-hassan has it right. Those extension methods give you direct access to the mycmdline instance and to the errors.
