### ISSUE TITLE
fsharp demo with union or enum?

### ISSUE THREAD

**Issue by jrr** [commandlineparser/commandline#349]
I briefly fiddled with them, and couldn't immediately get either working. Is the library expected to handle input types of F# discriminated unions and/or enums?

```fsharp

type FooUnion =
    | One
    | Two
    | Three

type BarEnum =
    | Aaa = 0
    | Bbb = 1
    | Ccc = 2

type CommandLineOptions =
    {   
        [<Option('e', "exercise", HelpText = "Do unions work?")>]
        Union: FooUnion; 
        
        [<Option('e', "enum", HelpText = "how about enums?")>]
        Enum: BarEnum; 
    }
```

**Comment by moh-hassan** [comment]
Old question, but may help others.
`enums` is supported.
`discriminated unions`  is not supported because it has no correspondence in c#.

**Comment by moh-hassan** [comment]
Close for age
