### ISSUE TITLE
Can a verb have a child verb?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#35]
<a href="https://github.com/sgrassie"><img src="https://avatars2.githubusercontent.com/u/194140?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sgrassie](https://github.com/sgrassie)**
_Friday Jul 17, 2015 at 10:56 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/201_

----

I'd like to allow the following scenarios:

```
$ app verb -t
$ app verb childverb -u
$ app verb otherchildverb -z
```

Where `-u` and `-z` are both specific to the respective child verbs. Is the documentation in the wiki for this still valid, or has it changed in 2.0+?

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Saturday Jul 18, 2015 at 03:57 GMT_

----

Hi @sgrassie, thank you again for being there.

Starting from easy things... 2.0+ documentation is condensed in this [part of the wiki](https://github.com/gsscoder/commandline/wiki/Latest-Version).

Command Line never supported nested verb (nor previous stable), but it's a very interesting.

We can introduce a property to set the parent verb:

``` csharp
[Verb("verb1")]
class VerbOptions1 { }

[Verb("verbchild1", Parent="verb1")]
class VerbChildOptions1 { }
```

Than all options classes will be normally passed to `ParseArguments<T1 ... Tn>` with properly modified `InstanceChooser.Choose` call.

**Comment by ericnewton76** [comment]
<a href="https://github.com/pthivierge"><img src="https://avatars3.githubusercontent.com/u/3816098?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pthivierge](https://github.com/pthivierge)**
_Thursday Dec 03, 2015 at 18:52 GMT_

----

I am also looking for something like this, this may be useful.  +1.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Sunday Dec 06, 2015 at 01:24 GMT_

----

Given the way verbs are [defined now](https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/ParserTests.cs#L136), out of band, this may be difficult to implement.

It may be possible to recursively call [choose](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/InstanceChooser.cs#L23) with the remaining arguments (after excluding the first matched verb) and incorporate @gsscoder's suggestion of a `parent` parameter.

**Comment by ericnewton76** [comment]
<a href="https://github.com/pthivierge"><img src="https://avatars3.githubusercontent.com/u/3816098?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pthivierge](https://github.com/pthivierge)**
_Monday Dec 07, 2015 at 09:18 GMT_

----

Ok thanks, I understand.  As of now, my alternative is to create more verb commands, instead of nested ones.

**Comment by ericnewton76** [comment]
<a href="https://github.com/Mizipzor"><img src="https://avatars1.githubusercontent.com/u/139879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mizipzor](https://github.com/Mizipzor)**
_Friday Jan 29, 2016 at 22:21 GMT_

----

Crazy idea, what if the verb name contained a space? Would that be able to fake a hierarchy?

**Comment by johnjaylward** [comment]
Isn't this the same as #13? maybe close as a duplicate?

**Comment by moh-hassan** [comment]
Dupl #13
