### ISSUE TITLE
Flawed Examples

### ISSUE THREAD

**Issue by The-Futurist** [commandlineparser/commandline#362]
@mizipzor @nemec @ericnewton76 @gimmemoore @Thilas

Hi, the example code on the project home page here is flawed. There's a comma missing after `false `in the `Options `class and the compiler cannot resolve `RunOptionsAndReturnExitCode`. I also see numerous problems reported by others about examples in general that have not been responded to for over a year!

In fact neither `RunOptionsAndReturnExitCode `nor `HandleParseError `appear when I search your source code whereas `WithParsed `for example is clearly part of the source.

I installed this from NuGet and have version 2.3.0 for .Net 4.6 installed. Bear in mind I'm seeking a solid library here that we can use for all of our console apps going forward, these initial frustrations do not inspire confidence.

If this project has been abandoned or is not being maintained please let us know, at this stage I have no option but to look at alternatives (or even develop my own).

**Comment by nemec** [comment]
Hi @Korporal, `RunOptionsAndReturnExitCode` and `HandleParseError` are just placeholders for you to place your own delegates. They are not part of the library. If you want something you can copy-paste without touching, try the QuickStart.

**Comment by The-Futurist** [comment]
@nemec - OK thanks for that note and yes the simple quick start is fine. Perhaps someone can update that README to emphasize the presence of place holders as well as explain a little about what they represent?

**Comment by moh-hassan** [comment]
Readme is fixed.
