### ISSUE TITLE
Is it possible to specify the valid values for an option?

### ISSUE THREAD

**Issue by ndaian** [commandlineparser/commandline#368]
Is it possible to specify the valid values for an option?

Something like
[Option('o', "opt1", Default = "val1", ValidValues = {"val1", "val2", "val3"})]

**Comment by ZedZipDev** [comment]
The good question!

**Comment by nemec** [comment]
This is a duplicate of #45. The short answer is no, it would have to be handled post-parsing. If your values are valid Enum fields you can set up an Enum instead of a string. That won't work for things like `4.1`, which aren't allowed in Enums.
