### ISSUE TITLE
Accepting ONLY fixes PR until stable release

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#37]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsscoder](https://github.com/gsscoder)**
_Saturday Aug 01, 2015 at 06:20 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/213_

----

As you can see I've recently promoted the library from **alpha** to **beta**.

Please be patient if I'll not accept enhancement PR until it becomes **stable**.

As a developer you know that adding complexity will delay the consolidation of a stable code base, a solid prerequisite for proceeding with future changes.

Obviously I'll accept any fix, or better everyone is encouraged to submit fixes or also new tests to cover untested parts.

A good practice is always open issue, discuss and than submit a PR.

Thanks everyone!

cc/ @nemec @Thilas @mizipzor @gimmemoore

**Comment by kenny-evitt** [comment]
This seems like it can be closed.
