### ISSUE TITLE
WiKi - Confusing

### ISSUE THREAD

**Issue by The-Futurist** [commandlineparser/commandline#372]
It would help if the patterns used in the various example command lines was explained. For example although I'm a very very experienced Windows software engineer and understand .Net very well it is far from obvious what the "$" means, e.g.

`$ app --userid=root`

It might even be more helpful to use a simple screenshot of a small console window as it would appear to a user.

In addition I have simple option like this:

```
        [Option(/*'u', "update",*/ Required = false, HelpText = "Enables the application to update the database.")]
        public bool Update { get;  set; }

```

Yet if I then submit a line containing `--update=false`  I find that the Update property is always true!

Your example (in the WiKi) implies this should set it to false, again this is extremely bewildering.

I also cannot see how I can implement this:

`myapp --mode=ftp`

or

`myapp --mode=file`

In such a way that the only legal values are "ftp" and "file"

**Comment by Snefheff** [comment]
Same issue with bool parameters

[Option('v', "ValidateOnly", Default = false, HelpText = "Check only")]
        public bool ValidateOnly { get; set; }

omitting the --ValidateOnly parameter sets it to false
including --ValidateOnly true   sets it to true
including --ValidateOnly false  still sets it to true

**Comment by Snefheff** [comment]
bool options are set or not.   

like the dir command
dir *   shows the directory listing
dir * /L  shows in lowercase because /L is 'set'

you don't use dir * /L = true

**Comment by ericnewton76** [comment]
Hi @Korporal 

regarding keeping mode only being file or ftp, the library doesnt currently have any way to force that.

I have designs in my head about an Option Validation that would be pluggable into the parsing to raise issues with the commandline options in a structured way.  I can imagine them being added in a minor release since there's no breaking change.
