### ISSUE TITLE
Suggestion - Support List<T> values as well as IEnumerable<T> values

### ISSUE THREAD

**Issue by The-Futurist** [commandlineparser/commandline#374]
It would be helpful to allow List<T> as well as IEnumerable<T> as the type for Value args. This is because in almost every case we must convert the IEnumerable to a List (or array) in order to process it full (like validate how many there are etc).

IEnumerable is fine but unwieldy and it's unlikely the sequence would ever need to be an IEnumerable, it will always be a small set of values.

Thx

**Comment by noamyogev84** [comment]
some code pointers maybe? 😄

**Comment by moh-hassan** [comment]
`Enumerable<T>` can be converted  to `List<T>`   using Linq.
