### ISSUE TITLE
Question: Does the library include/expose a utility to convert a string into args?

### ISSUE THREAD

**Issue by The-Futurist** [commandlineparser/commandline#375]
I was wondering if the library has this ability, I'd expect you to possibly rely on something like this for unit testing. Ideally I could supply a string that is (literally) a copy of a typed in arg list, and have that broken up into a set of smaller strings (like .Split does but clearly more intelligent).

I'd like to use this for unit testing my own applications hence my question (I'd rather not write my own).

**Comment by nemec** [comment]
For unit testing I format most CLIs in a way that Split handles correctly. If it doesn't work, I create an array manually.

You could try PInvoking what Windows does (or find the equivalent in the .NET Core codebase): https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-commandlinetoargvw
