### ISSUE TITLE
Having an enum for a value does not work, but changing it to an option does

### ISSUE THREAD

**Issue by Pyritie** [commandlineparser/commandline#385]
I have a simple application that I would like to give two command line arguments -- one tells the program what action to take, the other is a file path.

So I set my code up like this:

```
internal enum CmdAction
{
    One,
    Two,
    Three
}

internal sealed class CmdOptions
{
    [Option('p', "path")]
    public string Path { get; set; }

    [Value(0, Required = true)]
    public CmdAction Action { get; set; }
} 
```

If I run my program with the arguments of `One -p C:/example/file.txt`, I get an error message of:
```
A value not bound to option name is defined with a bad format.
A required value not bound to option name is missing.
```

However, if I change Action to:

```
[Option('a', "action")]
public CmdAction Action { get; set; }
```

and then run with `-a One -p C:/example/file.txt`, it works fine.

Why is this?

**Comment by moh-hassan** [comment]
I test the enum type option with command:

            One -p C:/example/file.txt77

and it's working fine without errors

The parsed values are:
>p= C:/example/file.txt
Action= One

Try it in a life [demo](https://dotnetfiddle.net/cmQRVp)
