### ISSUE TITLE
Displaying help text with fluent syntax?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#39]
<a href="https://github.com/jawn"><img src="https://avatars3.githubusercontent.com/u/1705112?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jawn](https://github.com/jawn)**
_Wednesday Aug 12, 2015 at 08:58 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/223_

----

Using the latest nuget of the version 2.0 pre-release, I can display help text like this:

```
var results = Parser.Default.ParseArguments<Options>(args)
  .WithParsed(opts => /* handle options here */)

if (results.Tag == ParserResultType.NotParsed)
{
  var helpText = HelpText.AutoBuild(results);
  Console.WriteLine(helpText);
}
```

Is there a way to do this within the fluent syntax?

Something like
    var results = Parser.Default.ParseArguments<Options>(args)
      .WithNotParsed(opts => Console.WriteLine(HelpText.AutoBuild()));
      .WithParsed(opts => /\* handle options here */)

Since AutoBuild() requires results, this can't be called within the fluent syntax. That's already logged as #88, however I would like to know whether a different solution is available.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Wednesday Aug 12, 2015 at 13:23 GMT_

----

Hi @jawn, happy you choose this library.

If you invoke the parser using default singleton like in posted sample, you don't need any call to `AutoBuild()`. This is because this instance is pre-configured with a `ParserSettings.HelpWriter` set to `Console.Error` and when this property has a value the help screen is automatically generated and displayed.

In this case just stay with the `WithParsed` and job is done.

_If you want handle help text manually, there's various way to do it from using `AutoBuild()` to mixing various intermediate step to get whatever customization you want._

Any way a **possible** fluent version, could be an extension to `ParserResult` like `result.AutoBuild()`...

If this not helped, please let me know.

PS: If possible use `ParserResult` extension methods instead of manually checking `Tag` discriminator and cast the instance.

**Comment by moh-hassan** [comment]
Closed for age.
