### ISSUE TITLE
Nuget Package Installation Fails

### ISSUE THREAD

**Issue by jwbats** [commandlineparser/commandline#395]
Attempting to install 2.4.3 in a .NET Core 2.2 console project.

```
Install-Package : NU1108: Cycle detected. 
  CommandLineParser -> CommandLineParser (>= 2.4.3).
At line:1 char:1
+ Install-Package CommandLineParser -Version 2.4.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'CommandLineParser'.
At line:1 char:1
+ Install-Package CommandLineParser -Version 2.4.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by moh-hassan** [comment]
I can install CommandLineParser  successfully  in  a Console project: netcoreapp2.2 in vs 2017 by the command:

          PM> install-package CommandLineParser

Check the syntax of command and have a look to this [issue](https://github.com/NuGet/Home/issues/6754)

**Comment by jwbats** [comment]
I tried installing via the nuget package manager and then by copy pasting the command from the official nuget page. These both failed.

The issue you link applies to me. My project had the same name as this dependency. That was probably the cause. Tnx!

**Comment by moh-hassan** [comment]
Welcome.
Glad that you resolved your issue.
