### ISSUE TITLE
Igoring spaces and dashes.

### ISSUE THREAD

**Issue by materiywakal** [commandlineparser/commandline#398]
Is it possible for parser to ignore somehow spaces and dashes ?
For example: -u "C:\Folder\some - file.txt"

**Comment by ericnewton76** [comment]
Not sure what you're aiming for here... can you add more info to your original post?

**Comment by materiywakal** [comment]
Uhh. English is not my native but i will try.
I have an option:
[Option('u', "upload", HelpText = "some text.")]
public string UploadArg { get; set; }

So for example i'm trying to parse this command:
-u "C:\Folder\some - file.txt"

But as a result i get:
 "C:\Folder\some

Can i some how get value of string in quotes?

**Comment by moh-hassan** [comment]
Use dashdash  configuration:

                 var p = new Parser(settings => settings.EnableDashDash = true);
                 p.ParseArguments<Opts>(args);



In the commandline you can pass:

            myprogram.exe   -u -- "C:\Folder\some - file.txt"
Read this [discussion](https://github.com/commandlineparser/commandline/issues/422)
