### ISSUE TITLE
Added Windows Style LongName ("/") to Options along with the required…

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#40]
<a href="https://github.com/Rusk85"><img src="https://avatars1.githubusercontent.com/u/4667261?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Rusk85](https://github.com/Rusk85)**
_Saturday Aug 15, 2015 at 22:02 GMT_
_Originally opened as https://github.com/gsscoder/commandline/pull/224_

----

… unit tests. I have refrained from altering the core logic. Instead I added two overloaded methods for Parser.ParseArguments(...) with an additional optional parameter "useWinStyleOptions" which is set to true per default. From there on I simply check all arguments for the win style flag ("/") and replace them with the stock double dashes ("--"). The result I pass to the original ParseArguments-Methods.

While as a personal preference I take unix style options over windows style options every day but there is a remote service I am using that is among other things capable of executing applications. I cant easily change the service - its fairly old and written in vb.net - but I checked the implementation. Turns out its capable of interpreting windows style options and passing that to the application it starts. So there you go.

There might be others in a similar situation to whom this could be a possible solution.

Please review the code.

----

_**[Rusk85](https://github.com/Rusk85)** included the following code: https://github.com/gsscoder/commandline/pull/224/commits_

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Saturday Aug 15, 2015 at 23:16 GMT_

----

The only problem I can think of here is how to enforce using only long names. Short names will still require a `-` and I can imagine a developer who doesn't know/forgets and gets confused.

Otherwise, this might be a nice compromise for #108. I think you could even implement this as an extension method under a different namespace (like `CommandLine.Windows`) to reinforce the fact that the UNIX way is preferred.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Sunday Aug 16, 2015 at 06:26 GMT_

----

@Rusk85, thanks for PR. This is also discussed in #108, as stated by @nemec.

I'm forced to temporary delays any PR except fixes as explained here in #213 announcement, until project reaches **STABLE** status.

Anyway I'll accept fixes.

Thank you! :)

**Comment by johnjaylward** [comment]
looks like a dup of #15

**Comment by moh-hassan** [comment]
DUP #15
