### ISSUE TITLE
Pure [Value] parsing fails if value starts with "-" or "--"

### ISSUE THREAD

**Issue by AWoelfel** [commandlineparser/commandline#406]
For a Option class 

    class OptionsA
    {
        [Value(0)]
        public string Arg1 { get; set; }

        [Value(1)]
        public string Arg2 { get; set; }

        [Value(2)]
        public string Arg3 { get; set; }

        [Value(3)]
        public string Arg4 { get; set; }
    }

or 

    class OptionsB
    {
        [Value(0)]
        public IEnumerable<string> Arg { get; set; }

    }

parsing failes if any provided arguments start with "-" or "--"

    //Works
    Parser.Default.ParseArguments<OptionsA>(new[] { "blub", "foo", "bar", "bleep" }).MapResult((OptionsA a)=> 0, (errors => 0));

    //Not ERROR => Option 'bar' is unknown.
    Parser.Default.ParseArguments<OptionsA>(new[] { "blub", "foo", "--bar", "bleep" }).MapResult((OptionsA a) => 0, (errors => 0));

    //Works
    Parser.Default.ParseArguments<OptionsB>(new[] { "blub", "foo", "bar", "bleep" }).MapResult((OptionsB a) => 0, (errors => 0));

    //Not ERROR => Option 'bar' is unknown.
    Parser.Default.ParseArguments<OptionsB>(new[] { "blub", "foo", "--bar", "bleep" }).MapResult((OptionsB a) => 0, (errors => 0));
    
    //Works
    Parser.Default.ParseArguments<OptionsA>(new[] { "blub", "foo", "bar", "bleep" }).MapResult((OptionsA a) => 0, (errors => 0));

    //Not ERROR => Option 'b' is unknown.
    Parser.Default.ParseArguments<OptionsA>(new[] { "blub", "foo", "-b", "bleep" }).MapResult((OptionsA a) => 0, (errors => 0));

I am using CommandLine version 2.4.3 (from NuGet)
I can reproduce the Errors above on .Net Core 2.0, 2.1 and 2.2
I hav not teste Versions 1.X of .Net Core

**Comment by ericnewton76** [comment]
if you need `-` or `--` in your actual argument value, you will have to quote it.    

Psuedo code, and I'm not sure if this actually works ATM but should:
```
Parser.Default.ParseArguments<OptionsB>(new[] { "blub", "foo", "\"--bar\"", "bleep" }).MapResult((OptionsB a) => 0, (errors => 0));
```

**Comment by rmunn** [comment]
https://github.com/commandlineparser/commandline/wiki/How-To#q3 has the answer to this. CommandLineParser tries to emulate the behavior of the Linux `getopt` parser, and the standard command-line parsing on Linux is to use `--` (a command-line argument consisting of nothing but two hyphens) to signal the parser "okay, all options are parsed now, so anything after this is a value". I.e., on Linux if you have a file named `--foo` and you try to delete it with the standard `rm` command:

* `rm --foo` produces an error "rm: unrecognized option '--foo'"
* `rm -- --foo` successfully deletes the `--foo` file

So to parse values that start with hyphens, make sure you've used the `EnableDashDash` option in creating your Parser instance, then

```csharp
Parser.Default.ParseArguments<OptionsA>(new[] { "blub", "foo", "--", "--bar", "bleep" }).MapResult((OptionsA a) => 0, (errors => 0));
```

should work for you and parse `--bar` as a value.

**Comment by AWoelfel** [comment]
@rmunn Thank your for the answer.
As this issue is over an year old i allready lost track of it
Nevertheless i will give it a try!


Have a nice weekend!
Alex
