### ISSUE TITLE
v2.3.0 cannot resolve symbol mutuallyexclusive

### ISSUE THREAD

**Issue by nine-2-five** [commandlineparser/commandline#410]

**Comment by zoller27osu** [comment]
the MutuallyExclusiveSet option (https://github.com/gsscoder/commandline/wiki/Mutually-Exclusive-Options) in the old gsscoder version of the library has become the "SetName" option.

E.g. If you have 2 options annotated with [Option(SetName = "set1")] and [Option(SetName = "set2")], then the parser will complain if the user tries to use both.

**Comment by mmajcica** [comment]
Is there a way to associate a set to the chosen value of the property?

By this I mean the following:

app --auth-type PAT --token "asdf"

In this example, I would like to make sure that the user specified a token in case of a PAT value, meanwhile

app --auth-type Basic --username "admin" --password "pwd"

here in case of the Basic auth type, I would like to validate username and password arguments.

**Comment by moh-hassan** [comment]
[How to use](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
