### ISSUE TITLE
More ways to have commandlines?

### ISSUE THREAD

**Issue by roozbehid** [commandlineparser/commandline#416]
Doing a project I realized many options and ways to configure commandline are missing and being told by many that this is one of the best libraries out there, makes me think that there is a reason that these options were not implemented.

So my question is, is there a guideline or something that developers follow? or just nobody needed these features or ...?

For example I couldnt make commandline to work to understand followings

     myapp.exe -ab 
     myapp.exe --metadata title=title --medata comment=comment 
     myapp.exe =otherseperator

So problem with first one is two letter verb.
Second line, it seems you can not have multiple verbs
Third one, I just didnt see a way to change default '-' to something else.

**Comment by moh-hassan** [comment]
>So problem with first one is two letter verb.

The option `-ab` is considered as two flags (boolean options) 

              -a -b
  Flags  can be merged together as  `-ab`

 >Second line, it seems you can not have multiple verbs  

This is considered multiple options, but it's implemented as (with space as a separator, or you can assign your own):

                       myapp.exe --metadata title=title comment=comment   
You can define multi verbs, but one verb at a time and verb has no preceding - or --

                merge -a file1 file2 -o file

>Third one, I just didnt see a way to change default '-' to something else.

The symbol - and -- are [GNU and POSIX specifications standard](https://refspecs.linuxfoundation.org/LSB_1.3.0/gLSB/gLSB/libutil-getopt-3.html) and commandlineParser follow this standard

See this example that is based in your usecase:
		 
			  -ab --metadata  title=title   comment=comment  
		 
		 void Main(string[] args)
			{						 
					  var  result = Parser.Default.ParseArguments<Options>(args);			
						result.WithParsed(opts => Run(opts))
						 .WithNotParsed(err=>Console.WriteLine(err));
					 
			}
			
		 void Run(Options options)
			{
				Console.WriteLine(options.FlagA);
				Console.WriteLine(options.FlagB);
				options.MetaData.ToList().ForEach(x=>Console.WriteLine(x));
			}
				
		public class Options
		{
			[Option('a', "flag-a", HelpText = "flag a")]
			public bool FlagA { get; set; }			
		         [Option('b', "flag-b", HelpText = "flag b")]
			public bool FlagB { get; set; }
			[Option('m', "metadata",Separator=' ', HelpText = "MetaData")]   
			public IEnumerable<string> MetaData { get; set; }
			 
		}
