### ISSUE TITLE
--version does not print a new line at the end

### ISSUE THREAD

**Issue by Inventitech** [commandlineparser/commandline#418]
Using 2.4.3 on linux, I get the following behavior when calling `--version` (using the auto-generated help text):

```
$ dotnet run --version
strans 0.0.2$
```

The output does not terminate in a line break. This looks very ugly. Instead, it should be:

```
$ dotnet run --version
strans 0.0.2
$
```

All other commands nicely finish in a newline.

**Comment by Inventitech** [comment]
This might (or might not) be related to #399.

**Comment by Inventitech** [comment]
My workaround is to check whether the version is requested, and if so, append a newline:

```C#
return Parser.Default.ParseArguments<Options>(args)
                .MapResult(
                    options => run(options),
                    errors => handleErrors(errors));

...

static int handleErrors(IEnumerable<Error> errors)
{
      if(errors.Any(l => l.GetType() == typeof(VersionRequestedError))) {
           Console.Out.WriteLine();
       }
            
      return 0;
}
```

**Comment by natalie-o-perret** [comment]
Also having this issue.

@Inventitech thanks for the workaround!

**Comment by moh-hassan** [comment]
Hi @Inventitech , @ehouarn-perret 

Can you check the nuget package  [CommandLineParser.2.5.35-djrfsvwt.nupkg](https://ci.appveyor.com/api/buildjobs/4592rr5j87aif827/artifacts/src%2FCommandLine%2Fbin%2FRelease%2FCommandLineParser.2.5.35-djrfsvwt.nupkg)
Let me know if It resolved your issue.

**Comment by Inventitech** [comment]
This does the trick, good work!

**Comment by twaalewijn** [comment]
Edit: Never mind, even echo gives its result back like that so I guess it is just the way ```cmd``` does it.
I guess I just never noticed it before.

Don't know if it is a problem but thought I'd mention it anyway.
The output, using the package above, running from a ```cmd``` prompt on Windows looks like this now:

```
>dotnet run --version
strans 0.0.2

>
```

Running from a ```powershell``` prompt seems unaffected though so maybe this is just how it was always supposed to look in ```cmd```.
