### ISSUE TITLE
Support for "switch" style arguments

### ISSUE THREAD

**Issue by 0x15e** [commandlineparser/commandline#421]
Forgive me if this is already supported but I couldn't see how to use it if it is.

I'd like the ability to use options with boolean values that, when specified on the command line, become the opposite of their default values (without specifying a value).

E.g.,

```
[Option("with-some-feature", Default: false)]
public bool WithSomeFeature { get; set; }

[Option("without-other-feature", Default: true)]
public bool WithoutOtherFeature { get; set; }
```

```
$ foo.exe (option WithSomeFeature would be false, WithoutOtherFeature would be true)
$ foo.exe --with-some-feature --without-other-feature (option WithSomeFeature would be true, WithoutOtherFeature would be false)
```

**Comment by 0x15e** [comment]
Also, if a main contributor can confirm that this definitely isn't supported right now, I may just start building it myself and make a PR.

**Comment by obuobuobu** [comment]
@0x15e Do you mean only one of them required in this case? I need this too!

**Comment by RedX2501** [comment]
I think this is the same as #290?

**Comment by moh-hassan** [comment]
Mutual Exclusive options can do this out of the box, see this example:

          class  Options
		{
			[Option("with-some-feature", SetName = "enable")]
		  public  bool WithSomeFeature { get; set; }

			[Option("without-other-feature", SetName = "disable")]
		 public   bool  WithoutOtherFeature { get; set; }
		}

Only, you pass either `--with-some-feature`  or `--without-other-feature` ,  not both together.

The result of the command:

		--with-some-feature

		WithSomeFeature = True
		WithoutOtherFeature = False
		
The result of the command

		--without-other-feature

		WithSomeFeature = False
		WithoutOtherFeature = True

As you see, they changes values automatic without setting a default value, exclusive to each other.
Note: Mutually exclusive options need to have a different `SetName`.

Try online [Demo](https://dotnetfiddle.net/6gzxVD)

**Comment by 0x15e** [comment]
@moh-hassan Thanks! That does what I need. Not sure why I was having such a hard time getting my head around it but the functionality is definitely there already.

Edit: To be clear for anyone else that finds this, the value-inverting functionality from the initial post isn't there but it really doesn't need to be. The desired effect can be had using the example code.

**Comment by moh-hassan** [comment]
Thanks Murray  (@0x15e)  for feedback.
Also, You can add `Required=true' , if it should pass either one option.

**Comment by rzippo** [comment]
I am not conviced the Mutual Exclusive options solve the issue, at least not in a general sense.

> Only, you pass either `--with-some-feature` or `--without-other-feature`, not both together.

I have `some-feature` and `other-feature` which are independent, and it makes semantic sense to have `some` default to `false` and `other` default to `true`. Why should the user be forced to either enable one or disable the other, and not both at the same time? How would this scale with more switch-style arguments?

This seems like an unnecessary burden derived by adapting mutual exclusive options to an use case they were not designed for.
