### ISSUE TITLE
How does dashdash work in 2.x?

### ISSUE THREAD

**Issue by RedX2501** [commandlineparser/commandline#422]
i want to have a command line as:

    exe -g -- filename1 filename2

So I tried

     exe -g -- filename1

```
class Opts a
  [Option('g')]
  bool Generate {get; set;}
  [Value(0)]
  string Filename {get; set;}
}

var p = new Parser(settings => settings.EnableDashDash = true);
p.ParseArguments<Opts>(args);
```

I get the error:

> ERROR(S):
>   Error setting value to option 'unknownarguments': Property set method not 
found.

So what's the correct way of doing this in 2.x?

**Comment by moh-hassan** [comment]
To use double dash, you define options with longName, like

           [Option('g',"generate")]
             bool Generate {get; set;}

Then, to use

             exe    --generate  filename
No space between -- and the option

Filename is a free option without singlee /or double dash.
For more details, read the [Wiki](https://github.com/commandlineparser/commandline/wiki/Getting-Started)

**Comment by RedX2501** [comment]
Is DashDash not an option to enable the end of options delimiter? Or does command line always do that?

```
[Option('g')]
bool someFlag

[Value(0)]
string filename
```

Usage

```
exe -g -- -g
```

then `-g` is on and `filename` will also contain `-g` preventing it from being recognized as the option `-g`.

See https://www.in-ulm.de/~mascheck/bourne/set-.html

**Comment by moh-hassan** [comment]
>Is DashDash not an option to enable the end of options delimiter?

 DashDash enable the end of options delimiter in the custom Parser as you did.
I wasn't thinking that you mean using DashDash  as an end of option :D 

See this answer by [@nemec ](https://github.com/commandlineparser/commandline/issues/270#issuecomment-378970594) with example

I test your example with minor modification, and it's working with DashDash support

These are working

                -g -- -g 
		-g -- filename1
		-g -- -filename1
Try it [online](https://dotnetfiddle.net/6gzxVD	)

**Comment by RedX2501** [comment]
I thought it was broke due to https://github.com/commandlineparser/commandline/issues/156

I tried

```
exe -g -- expected unexpected
```

and got no error.

Since dashdash is working I can close this.
