### ISSUE TITLE
WithNotParsed() not being called during test

### ISSUE THREAD

**Issue by shyassure** [commandlineparser/commandline#424]
When running a test and command line parser inside a unit test, the HandleParseError function is never being called. I created a gist with a test and a class showing the example.

If I execute the class using regular F5 debugging inside Visual Studio, the HandleParseError function will be called.

https://gist.github.com/shyassure/78fcb2e5a497d2d266f44f579e0c37d3

**Comment by moh-hassan** [comment]
This is expected to happen in net4x (Full framework projects) because of the null attribute assemblies of the `ExcecutingAssemply`, for details review this [discussion](https://github.com/commandlineparser/commandline/issues/389#issuecomment-455914655)

In netcoreapp2.x it's working fine.
To resolve your issue, let the `'MailAndSmsWarningSenderTests'` [inherit from the](https://github.com/commandlineparser/commandline/issues/389#issuecomment-455914655)  BaseTest:

                    MailAndSmsWarningSenderTests: BaseTest
                    {
                    }


               public class BaseTest
		   {
			   public BaseTest()  
			  {  
			//in  Full Framework NET4x only,   because no appdomain in netcore			
			#if NET45|NET461|NET472      
				/* Preparing test start */  
				Assembly assembly = Assembly.GetCallingAssembly();  

				AppDomainManager manager = new AppDomainManager();  
				FieldInfo entryAssemblyfield = manager.GetType().GetField("m_entryAssembly", BindingFlags.Instance | BindingFlags.NonPublic);  
				entryAssemblyfield.SetValue(manager, assembly);  

				AppDomain domain = AppDomain.CurrentDomain;  
				FieldInfo domainManagerField = domain.GetType().GetField("_domainManager", BindingFlags.Instance | BindingFlags.NonPublic);  
				domainManagerField.SetValue(domain, manager);  
				/* Preparing test end */  
			#endif
			} 
		  }

**Comment by moh-hassan** [comment]
I created a vs2017 Test project as multi-target in net461 and netcoreapp2.1 using your test cases and used commanslineparser v2.4.3

I modified the code of `ParseArgumentsAndRun` by removing the try .. catch as given below:


          public void ParseArgumentsAndRun(string[] args)
            {             
                Parser.Default.ParseArguments<Options>(args)
                    .WithParsed(ExecuteTaskWithOptions)
                    .WithNotParsed(HandleParseError);            
           }

The HandleParseError function is called in both net461 and netcoreapp2.1 and raise the exception:
>System.NotImplementedException : The method or operation is not implemented

The try ..catch in the method `'ParseArgumentsAndRun'` catched the exception before  'HandleParseError ' function catch it.

Try it and let me know if it's not working as you expect.

**Comment by moh-hassan** [comment]
@shyassure 
This  issue is resolved in v2.5.0?

**Comment by shyassure** [comment]
@moh-hassan Sorry I haven't replied or tried without try catch. I've been working on other projects that doesn't use this library meanwhile. I will let you know if the issue is resolved.

**Comment by shyassure** [comment]
Doesn't seem like v2.5.0 solves the issue.

**Comment by moh-hassan** [comment]
When you catch the Exception in `DisplayErrorMessage`:

			private void DisplayErrorMessage(Exception ex)
				{        
					Console.WriteLine($"DisplayErrorMessage Exception {ex}");
				}
You get the following exception:

>DisplayErrorMessage Exception System.NotImplementedException: ++thrown by HandleParseError
   at MailAndSmsWarningSender.HandleParseError(IEnumerable`1 errs) in F:\github_issues\commandline424\Mstest\class1.cs:line 40
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at MailAndSmsWarningSender.ParseArgumentsAndRun(String[] args) in F:\github_issues\commandline424\Mstest\class1.cs:line 28	

So, WithNotParsed exception is fired  and catched by try .. catch

To catch the NotImplementedException Exception of in HandleParseError , remove try ..catch and run the test:

             [TestMethod]
             [ExpectedException(typeof(System.NotImplementedException))]
           public void SendSmsOnWarning()
           {
            _sut.ParseArgumentsAndRun(new []{"--task", "MailAndSmsWarningSender", "--test", "hejtest"});            
           }
    }

And the test pass successfully
So, there is no  issue in `CommandLineParser and WithNotParsed` is fired in unit test.
