### ISSUE TITLE
Handle null Assembly.GetEntryAssembly in ReflectionHelper.GetExecutingOrEntryAssembly

### ISSUE THREAD

**Issue by ohadschn** [commandlineparser/commandline#434]
`ReflectionHelper.GetExecutingOrEntryAssembly` is implemented like this:
https://github.com/commandlineparser/commandline/blob/a9243e96820fba2d5b36a59e300bd5e2c0728211/src/CommandLine/Infrastructure/ReflectionHelper.cs#L96

However, going by its name it should actually be implemented like this:
```cs
private static Assembly GetExecutingOrEntryAssembly()
{
    return Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();
}
```

Specifically, it would solve the failure of the current implementation when called from MSTest (for background see [here](https://social.msdn.microsoft.com/Forums/en-US/7ff8caae-56c6-4baa-94c9-7224f69dbd17/assemblygetentryassembly-returns-nothing-when-running-from-a-unit-test?forum=vststest)):
```
Assert.Fail failed. Exception of type System.ArgumentException thrown as expected, but the provided predicate rejected it: System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](Assembly element)
   at CommandLine.Infrastructure.ReflectionHelper.GetAttribute[TAttribute]()
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Int32 maxDisplayWidth)
```

**Comment by moh-hassan** [comment]
The PR #430  which rebased from #387 have a correction to this problem with other approach using  `Assembly.GetCallingAssembly`
The source code is [here](https://github.com/moh-hassan/commandline/blob/net40-net45/src/CommandLine/Infrastructure/ReflectionHelper.cs#L103).

			private static Assembly GetExecutingOrEntryAssembly()
					{
						//resolve issues of null EntryAssembly in Xunit Test #392,424,389
						//return Assembly.GetEntryAssembly();
						return Assembly.GetEntryAssembly()??Assembly.GetCallingAssembly();
			}

The problem has two sides:
- The null of GetEntryAssembly in net4x in test framework(it's resolved in netcore2.x)
- The assembly attributes of Copyright, company,... may be null 

This Proposal discuss the problem in [detail  ](https://github.com/commandlineparser/commandline/issues/403)


Currently, the `Assembly.GetCallingAssembly` is used in a separate class that inject it for net4x if it's null and help to resolve this [problem](https://github.com/commandlineparser/commandline/issues/389#issuecomment-455914655).

The [Assembly.GetCallingAssembly](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getcallingassembly?view=netframework-4.8) Method returns the Assembly of the method that invoked the currently executing method.

The GetExecutingAssembly is still used by test suit and so the assembly attributes may be null and cause the same issue.

The test framework don't modify the GetCallingAssembly .

The PR applied this solution of GetCallingAssembly and pass all unit test.

**Comment by ohadschn** [comment]
Thank you, I guess this means this issue is a duplicate - closing in favor of https://github.com/commandlineparser/commandline/issues/403.
