### ISSUE TITLE
Auto help question

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#44]
<a href="https://github.com/AndrewSav"><img src="https://avatars0.githubusercontent.com/u/658865?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AndrewSav](https://github.com/AndrewSav)**
_Tuesday Sep 22, 2015 at 22:37 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/242_

----

This is regarding 2.0
1) Is it possible to suppress displaying version/copyright stuff (I can display them myself, thank you very much) but retain the rest?
2) If I remove AssemblyCopyright attribute CommandLine just crashes. I'm not sure if it's intended behaviour?

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Sep 24, 2015 at 13:13 GMT_

----

> > 1) Is it possible to suppress displaying version/copyright stuff (I can display them myself, thank you very much) but retain the rest?

You can handle help screen completely on your own, just create a parser with a `ParserSettings` that lacks a value for `HelpWriter` property.

> > 2) If I remove AssemblyCopyright attribute CommandLine just crashes. I'm not sure if it's intended behaviour?
- If with crash you mean an exception not generated by the library, it's always something that should be fixed.
- In any case if you leave the automatic help generation, you can't remove `AssemblyCopyright`, but if you **generate the help screen manually** everything will be under your control.

But probably you want just use the **automatic generation** and tell it to not print copyright info removing `AssemblyCopyright`? Am I right?

**Comment by ericnewton76** [comment]
<a href="https://github.com/AndrewSav"><img src="https://avatars0.githubusercontent.com/u/658865?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AndrewSav](https://github.com/AndrewSav)**
_Thursday Sep 24, 2015 at 19:39 GMT_

----

> > But probably you want just use the automatic generation and tell it to not print copyright info removing AssemblyCopyright? Am I right?

Yes! As I said, I want it to print the help, as it is doing very good job with that. It would be a downer to re-implement it again, when the library already implements it. I just want to suppress displaying version/copyright but retain the rest of the help info generated. Is this possible? I might be reading it wrong but it seems that your response does not address this question?

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Monday Oct 05, 2015 at 22:41 GMT_

----

:paperclip: Please read: #250. Thanks for collaboration and patience! :sweat_smile:
Giacomo
_P.S.: valid only for me, if a main contrib. is available he's obviously free to support devs/users of the project._

**Comment by ericnewton76** [comment]
<a href="https://github.com/AndrewSav"><img src="https://avatars0.githubusercontent.com/u/658865?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AndrewSav](https://github.com/AndrewSav)**
_Monday Apr 18, 2016 at 09:45 GMT_

----

Just pinging, in case there is a status update. Cheers!

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Monday Apr 18, 2016 at 17:54 GMT_

----

Nothing yet. @gsscoder is tied up in work and I don't have time to actively develop a fix. If you want to dig in, I think the best approach would be to expose the AutoBuild pipeline (which currently depends on internal types, see #286 #281) and add a flag to the constructor allowing you to turn on/off version and copyright.

**Comment by ericnewton76** [comment]
<a href="https://github.com/ChristianIvicevic"><img src="https://avatars3.githubusercontent.com/u/651408?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChristianIvicevic](https://github.com/ChristianIvicevic)**
_Saturday Sep 16, 2017 at 10:46 GMT_

----

I noticed this behavior and reported it in #481 and it's a shame nothing has been introduced to remove the default version/copyright output. Since this hasn't been fixed in over two years I will be looking into alternative libraries.

**Comment by ericnewton76** [comment]
<a href="https://github.com/AndrewSav"><img src="https://avatars0.githubusercontent.com/u/658865?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AndrewSav](https://github.com/AndrewSav)**
_Saturday Sep 16, 2017 at 21:20 GMT_

----

@ChristianIvicevic at this stage this is the most reasonable thing to do.

**Comment by ericnewton76** [comment]
<a href="https://github.com/ChristianIvicevic"><img src="https://avatars3.githubusercontent.com/u/651408?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChristianIvicevic](https://github.com/ChristianIvicevic)**
_Saturday Sep 16, 2017 at 21:22 GMT_

----

@AndrewSav I moved to [System.CommandLine](https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/README.md) now. Unfortunately it is dependant on NETStandard which downloads 100 DLLs into the binary folder but the library itself is pretty nice.

**Comment by moh-hassan** [comment]
Resolved
