### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dmytro-gokun** [commandlineparser/commandline#440]
Hi,

first of all, thanks a lot for the great library (Y)

I can see that a new version have been recently released - v2.5.0. The question - how do I know what exactly has been changed in this version compared to the previous one? Are there any breaking changes to take care of while upgrading? What are the new APIs added?

Thanks in advance

**Comment by moh-hassan** [comment]
Thanks @dmytro-gokun  for your suggestion for Changelog that can track changes in versions and breaking changes.

Changelog will be added to the project with a new PR.
There is no Breaking change in v2.5.0. Current projects net40,net45 (net4x) and netstadard2.0/netcoreapp2.x  can upgrade to this version without breaking change.
The test is done in multi target framework.

2.5.0 (2019-04-29)
**Bug Fixes**
* Fix  the null EntryAssembly Exception in  unit test net4x projects ( issue: #389 )
* Fix  the test case 'Add unit tests for Issue #389 and #392 
* Fix CSC error CS7027: Error signing output with public key from file 'CommandLine.snk' -- Invalid public key in appveyor CI.  
* Fix the error CS0234: The type or namespace name 'FSharp' for net40 Framework.
* Fix Mis-typed CommandLine.BaseAttribute.Default results in ArgumentException: Object of type 'X' cannot be converted to type 'Y' (issue #189)


**Features**
* Add support for net40 and net45 without breaking change of the netstandard2.0 project for CSharp and Fsharp projects. 
* Commandline project is becoming multi-target Framework net40,net45,net461 and netstandard2.0.
* Commandline.Test project is becoming multi-target Framework net461 and netcoreapp2.0.
* Enhance the CSharp demo project to support  multi-target Framework net40; net45; netcoreapp2.0, netcoreapp2.1

**Comment by cosmoKenney** [comment]
@moh-hassan 
Hi, I just upgraded from a rather old version to 2.5.0 and ParserState attribute, HelpOption attribute, IParserState are no longer available. And HelpText.AutoBuild has a new signature.
Where can I find a migration path?

**Comment by moh-hassan** [comment]
@cosmoKenney ,
What the version you upgraded from?

**Comment by moh-hassan** [comment]
If you are upgrading from v1.x to v2.x, there is a major change

This [post](https://github.com/commandlineparser/commandline/issues/318) may help but it isn't complete.
Have a look to  [this ](https://github.com/commandlineparser/commandline/issues/219)  and https://github.com/commandlineparser/commandline/issues/225

**Comment by cosmoKenney** [comment]
@moh-hassan 
Hmm... this is killing me. I just need to make some simple changes to this project. I may need to roll back to 1.9. The new version is way overkill for what I need. 

ParseArgumentsStrict used to return boolean indicating success or fail. But now there is a result object from the generic ParseArguments. How do I get parse status from the ParserResult?

**Comment by moh-hassan** [comment]
Try reading getting start in the [readme ](https://github.com/commandlineparser/commandline) or [wiki ](https://github.com/commandlineparser/commandline/wiki)

>How do I get parse status from the ParserResult?

Have a look to this demo [online](https://dotnetfiddle.net/wrcAxr)

Just know how to call parser and how to return result and modify the options.
I will try to complete the document of [migration ](https://github.com/commandlineparser/commandline/issues/318).

V2.x have many valuable features.

**Comment by moh-hassan** [comment]
I migrated an online  demo application in [v1.9](https://dotnetfiddle.net/YjTb9L)
To version [2.5](https://dotnetfiddle.net/NpCLX6)

with comments in the [source code ](https://dotnetfiddle.net/NpCLX6) how to be converted

It 's simple steps.

[Wiki: Upgrading from previous v1.9](https://github.com/commandlineparser/commandline/wiki/Upgrading-from-previous-v1.9)

**Comment by sm-g** [comment]
@moh-hassan This issue still not ready?

**Comment by moh-hassan** [comment]
@sm-g 
 [CHANGELOG.md ](https://github.com/commandlineparser/commandline/blob/master/CHANGELOG.md) is added in v2.6.0
What do you mean by "not ready"?

**Comment by sm-g** [comment]
I mean "why this issue still open".

**Comment by moh-hassan** [comment]
@sm-g 
Thanks for reminding :)
Closed.
