### ISSUE TITLE
RunOptionsAndReturnExitCode does not return exit code. Always exit with 0 as it's void

### ISSUE THREAD

**Issue by xprite** [commandlineparser/commandline#441]
There is no possibility to return a value from your code as the RunOptionsAndReturnExitCode is of type Action which returns void. RunOptionsAndReturnExitCode should be at least renamed so it doesn't confuse users with the "AndReturnExitCode" in its name.

**Comment by moh-hassan** [comment]
You can return a value (exit code) from `RunOptionsAndReturnExitCode` as a function return value not Action when you use `MapResult` method.

Example:

		CommandLine.Parser.Default.ParseArguments<Options>(args)
			.MapResult(
			  (opts) => RunOptionsAndReturnExitCode(opts),	 
			  errs => HandleParseError(errs));
			  
	  
		 int  RunOptionsAndReturnExitCode(Options o)
			{
			  // do your stuff here and return Exitcode based on the program logic
			  var exitCode=0;
			  //exit code values 
			  //0 normal use
			  // -1 for offset >10
			  // -2 for offset <5
			  if (o.Offset >10)  exitCode= -1;
			  if (o.Offset <5)  exitCode= -2;
			 
			  return exitCode;
			}

Also, you can use async/await 	with MapResult.

`RunOptionsAndReturnExitCode` is not part of the Codebase of the library but a user defined method(function).

Online [Demo](https://dotnetfiddle.net/wrcAxr)

**Comment by moh-hassan** [comment]
Is it clear the usage of `RunOptionsAndReturnExitCode`?

**Comment by xprite** [comment]
Thank you for a detailed example @moh-hassan. For other readers interested in the Online Demo https://dotnetfiddle.net/wrcAxr just update your main function to return int and return the parserResult from Main
