### ISSUE TITLE
Documentation does not explain difference between Option and Value

### ISSUE THREAD

**Issue by rossng** [commandlineparser/commandline#442]
I can't see any information in the documentation on the difference between an `Option` and a `Value`. They are compared to constructs in previous versions of the library, but I haven't used those previous versions.

**Comment by moh-hassan** [comment]
This [document ](https://github.com/commandlineparser/commandline/wiki/Upgrading-from-previous-v1.9)may help

**Comment by levicki** [comment]
Sadly it doesn't explain how to migrate code which used `HelpText` class as well as `[HelpOption]` and `[HelpVerbOption]` attributes. I have never seen a project change their API this much without providing clear upgrade explanation for all removed or changed features.

**Comment by Logopher** [comment]
@levicki Did you ever find how to replace `[HelpOption]`?

**Comment by levicki** [comment]
> @levicki Did you ever find how to replace `[HelpOption]`?

No, I gave up on this library and I am just writing my own command line parsers when needed.
