### ISSUE TITLE
Parse custom classes as parameter

### ISSUE THREAD

**Issue by sommafa** [commandlineparser/commandline#448]
```
public class Options
{
    [Option('f', "files", Default = true)]
    public IEnumerable<FileConn> Files { get; set; }
}

public class FileConn
{
    public FileConn(string datasource, string catalog, string userid, string password, string provider, string isEncrypted)
    {
        this.DataSource = datasource;
        this.Catalog = catalog;
        this.UserId = userid;
        this.Password = password;
        this.Provider = provider;

        bool wBool;
        bool.TryParse(isEncrypted, out wBool);
        this.IsEncrypted = wBool;
    }

    public string Provider { get; set; }
    public string DataSource { get; set; }
    public string Catalog { get; set; }
    public string UserId { get; set; }
    public string Password { get; set; }
    public string Language { get; set; }
    public bool IsEncrypted { get; set; }
}
```

I'd like to pass in, as arguments, a list of values to build the FileConn class. 
Something like:
`-f servername1 catalog1 user1 password1 provider true`

and, since it's a collection, also something like this:
`-f servername1 catalog1 user1 password1 provider true -f servername2 catalog2 user2 password2 provider true`

How can i do that?

**Comment by moh-hassan** [comment]
You  can't use  custom classes as a parameter.

Use the following code:
        
          public class Options
        {
            [Option('f', "files")]
            public IEnumerable<string> Files { get; set; }
        }
         static void Main(string[] args)
        {
            CommandLine.Parser.Default.ParseArguments<Options>(args)
                .WithParsed(RunOptions)
                .WithNotParsed(HandleParseError);
        }
        
        private static void RunOptions(Options opts)
        {
            var files=opts.Files.ToArray();
         var fileConn=   new FileConn(files[0],files[1],files[2],files[3],files[4],files[5]);
        //rest of code
        }
        private static void HandleParseError(IEnumerable<Error> errs)
        {
            //do stuff
        }

**Comment by sommafa** [comment]
Thank you,
I solved using a Files option, just like yours (`IEnumerable<string>`), containing already all the infos I need. Like this:
`DATASOURCE=SERVER;CATALOG=CAT1;USERID=USER;PASSWORD=PSWD`

So, my command line is something like:
`myApp.exe -f DATASOURCE=SERVER;CATALOG=CAT1;USERID=USER;PASSWORD=PSWD`

and for multiple files it becomes:

`myApp.exe -f DATASOURCE=SERVER;CATALOG=CAT1;USERID=USER;PASSWORD=PSWD DATASOURCE=SERVER2;CATALOG=CAT2;USERID=USER2;PASSWORD=PSWD2`

In this way, in a second step, I can process al the strings in the collection and parse them to consume them without the need to know the order of the elements but just using tags (DATASOURCE, CATALOG, etc..)
