### ISSUE TITLE
Options that are Enums are not displayed in help.

### ISSUE THREAD

**Issue by reflectedobject** [commandlineparser/commandline#449]
Simple patch to default enable.

e.g.
        [Option('F', "Formats", Required = false, HelpText = "List of output formats to generate.", Default = TableOutPutTemplate.SchemaInfo)]
        public TableOutPutTemplate Format { get; set; }
Where TableOutPutTemplate  is an enum.

[0001-Default-the-display-of-Enum-values-to-the-help-outpu.txt](https://github.com/commandlineparser/commandline/files/3217230/0001-Default-the-display-of-Enum-values-to-the-help-outpu.txt)

**Comment by moh-hassan** [comment]
The option:

                 addEnumValuesToHelpText = true;
Can be used in the custom help.
Setting this option by default cause  some test cases to fail.

             CommandLine.Tests.Unit.Text.HelpTextTests.Create_instance_with_options_and_values [FAIL]
            CommandLine.Tests.Unit.Text.HelpTextTests.Create_instance_with_enum_options_disabled [FAIL]


@ericnewton76
