### ISSUE TITLE
Defining sets of valid option values

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#45]
<a href="https://github.com/bergbria"><img src="https://avatars3.githubusercontent.com/u/2791113?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bergbria](https://github.com/bergbria)**
_Monday Sep 28, 2015 at 17:27 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/245_

----

I'd like to create an option where there is a known, restricted set of valid values which cannot be expressed in C# as the name of an enum. For example, the set might look like {8.0, 8.1, 9.0}. Is there any way to express this using this library?

If not, what would be the best way to add support for this? A custom attribute for enum fields, another parameter for the Option attribute?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Saturday Apr 23, 2016 at 21:34 GMT_

----

Hi @bergbria, there is no way to support that today.

Since floating point numbers will never be valid enum values, I think it would make sense to add the ability to restrict valid values of any arbitrary option (like `double Version {get;set;}`)

One option (like [Powershell](http://stackoverflow.com/questions/25177744/powershell-validateset)):

``` csharp
class Option
{
    [Option('v', HelpText="Version Selector")]
    [RestrictedValues("8.0", "8.1", "9.0")]
    public double Version { get; set; }
}
```

It has a number of negatives, like case sensitivity and being "stringly typed", but attributes only allow compile time constants and arrays, so you're very limited in what you can do.

Another option that offers a bit more flexibility could be a companion property:

``` csharp
class Option
{
    [ValueRestrictions("Version")]
    public static VersionRestrictions[] = { 9.0, 8.1 }

    [Option('v', HelpText="Version Selector")]
    public double Version { get; set; }
}
```

But it leads to clutter in your option class.

**Comment by thnk2wn** [comment]
I like option 1. I think it's quite common to have arguments that only support a limited set of fixed values. As it stands I can't see an easy way to simply display usage text if I detect a parameter value isn't valid - HelpText.AutoBuild seems to want a not parsed instance. Ideally I'd be able to define restricted values and it'd do it for me but if I need to further validate values manually it'd be nice to easily display help text for valid parsing but invalid values, just like it does when I pass an invalid command line argument.

**Comment by thnk2wn** [comment]
I guess something like this works, using a different overload of AutoBuild

    parseResult
        .WithParsed(options => {
            var mode = options.Mode.Substring(0, 1).ToLowerInvariant();

            if (modeMap.ContainsKey(mode)) 
            {
                modeMap[mode](serviceProvider);
            }
            else 
            {
                Console.Error.WriteLine(HelpText.AutoBuild(parseResult, null, null));
            }
        })
        .WithNotParsed(errors => {
            Console.Error.WriteLine("Error parsing command line");
        });
