### ISSUE TITLE
How can I specify a List to be parsed from the command line?

### ISSUE THREAD

**Issue by gatsbys** [commandlineparser/commandline#459]
Hi,

I have the following option : 

```
 [Option('c', "countries", Required = true)]
 public IEnumerable<string> Countries { get; set; }
```
But I don't know how to fill the command from the command line arguments, I have tied : 

-c ES;CO
-c ES -c CO
-c ES CO

Any help here, please :) ?

Thanks you!

**Comment by brifly** [comment]
Specifying a Separator worked for me, e.g. 
[Option('c', "format", Required = true, Separator = ',')]
public IEnumerable<string> Countries { get; set; }

and then:
-c ES,CO
