### ISSUE TITLE
Parser doesn't warn/throw if multiple options with same name

### ISSUE THREAD

**Issue by NeilMacMullen** [commandlineparser/commandline#468]
For the code below, the helptext is quite happy to list both "abc" options.  It would be desirable to generate a run-time warning error.

```
public class CommonOptions 
{
  [Option("abc")]
  public string X {get;set;}
}

public class DerivedOptions :CommonOptions
{
    [Option("abc")]
    public string Y {get;set;}
}
```

**Comment by moh-hassan** [comment]
Good idea.
PR is welcome.
Have a look to this [discussion ](https://github.com/commandlineparser/commandline/issues/357)for handling repeated options.

**Comment by moh-hassan** [comment]
multiple options are allowed starting v2.9
