### ISSUE TITLE
Helptext doesn't display verb summary when 'help' called

### ISSUE THREAD

**Issue by NeilMacMullen** [commandlineparser/commandline#470]
Invoking foo.exe produces 

> 
> foo.exe
> ERROR(S)
> ... 
>   someverb    this command does interesting stuff

Invoking **foo.exe help somerverb** just lists the options without the summary.  This seems odd - I invoked help to get more information about the command, not just to list the options.

**Comment by moh-hassan** [comment]
Can you show what is supposed to be displayed and the actual display of the help by example.
It's nice if you can provide a working example.

**Comment by tkouba** [comment]
Are you using static parser or your own? Try `config.HelpWriter = Console.Out;` in parser initialization.

                Parser parser = new Parser(config =>
                {
                    config.HelpWriter = Console.Out;
                });

                var result = parser.ParseArguments<ArgumentOffline, ArgumentPing>(args);

**Comment by 123rajneesh** [comment]
Hi, I am facing same issue in my dotnet application,I used CommandLine 2.7.82.0  &  running command like below

**>DotNetCLI help CreateAsset**

current output is below:
![image](https://user-images.githubusercontent.com/5788173/75321217-48ec3600-5896-11ea-8e6a-fc8045238252.png)

Expecting that It should show "**Verb**" Summary.
 
Please assist me to get the **"verb**" summary ASP.

**Comment by hatton** [comment]
> Can you show what is supposed to be displayed and the actual display of the help by example.
It's nice if you can provide a working example.

```c#
	[Verb("spreadsheetExport", HelpText = "Export a book to an Excel spreadsheet (xslx).")]
	public class SpreadsheetExportParameters
	{
		[Value(0, MetaName = "path", HelpText = "Path to the book (htm file) to export.", Required = true)]
		public string BookPath { get; set; }

		[Option('o', "output", HelpText = "The (xlsx) file where the output will be written", Required = true)]
		public string OutputPath { get; set; }

		[Option('p', "params", HelpText = "Path to a file containing parameters for the export", Required = false)]
		public string ParamsPath { get; set; }
	}
```
	
Then 

```
c:\temp>
c:\temp>bloom spreadsheetExport --help

c:\temp>Bloom 5.1.000.0
c SIL International 2012-2020

  -o, --output     Required. The (xlsx) file where the output will be written

  -p, --params     Path to a file containing parameters for the export

  --help           Display this help screen.

  --version        Display version information.

  path (pos. 0)    Required. Path to the book (htm file) to export.

```

The unexpected part here is that we don't see the `Export a book to an Excel spreadsheet (xslx).` at all. Can you see what we're doing wrong?

Thanks!
