### ISSUE TITLE
Verbs are not working? [internal properties are not working]

### ISSUE THREAD

**Issue by igadmg** [commandlineparser/commandline#480]
This code and calling it with arguments "add test1 test2"

	[Verb("add", HelpText = "Add repository to the group.")]
	internal class AddVerb
	{
		[Value(0, Required = true)]
		internal string RepositoryPath { get; set; }

		[Value(1, Required = true)]
		internal string GroupName { get; set; }
	}

	Parser.Default.ParseArguments<AddVerb, object>(args)
				.WithParsed<AddVerb>(v => AddRepositoryToGroup(v));

calls AddRepositoryToGroup but all v members are null.

If I add option

	[Verb("add", HelpText = "Add repository to the group.")]
	internal class AddVerb
	{
		[Option]
		internal string Opt { get; set; }

		[Value(0, Required = true)]
		internal string RepositoryPath { get; set; }

		[Value(1, Required = true)]
		internal string GroupName { get; set; }
	}

	Parser.Default.ParseArguments<AddVerb, object>(args)
				.WithParsed<AddVerb>(v => AddRepositoryToGroup(v));

and call it with arguments "add --Opt asdf test1 test2"
i get option Opt is unknown.

**Comment by igadmg** [comment]
Figured out, internal properties are not working for some reason.

**Comment by moh-hassan** [comment]
Properties should be public to be set by Parser during Reflection.  Internal Properties are not supported.

**Comment by igadmg** [comment]
> Properties should be public to be set by Parser during Reflection. Internal Properties are not supported.

Maybe that should be specially stated in the documentation, because at first I had a wtf moment...
Internal classes work, internal properties do not.

**Comment by moh-hassan** [comment]
Wiki [Documentation ](https://github.com/commandlineparser/commandline/wiki)are updated  to state public properties.
