### ISSUE TITLE
Many class for same verb

### ISSUE THREAD

**Issue by b3b00** [commandlineparser/commandline#481]
Hi,

Is there a way to specify many option set for the same verb ?
I have a command line tool that accept a verb "copy" which may act differently according to the parameters (Value) number .
My code : 
```c#
 public class BaseOptions
    {
        private string root = null;
        private string output = null;

        [Option('r',"root", HelpText = "root dir", Required = true)]
        public string RootDirectory { get { return root; } set { root = value; } }



        [Option('o',"output", HelpText = "output dir", Required = false)]
        public string OutputDirectory { get { return output ?? RootDirectory; } set { output = value; } }
    }


    [Verb("copy")]
    public class CopyRubriqueInPlaceOptions : BaseOptions
    {
        [Value(0)]
        public string Model { get; set; }
        [Value(1)]
        public string SourceRubrique { get; set; }
        [Value(2)]
        public string TargetRubrique { get; set; }
    }

    [Verb("copy")]
    public class CopyRubriqueModelToModelOptions : BaseOptions
    {
        [Value(0)]
        public string SourceModel { get; set; }
        [Value(1)]
        public string SourceItem { get; set; }
        [Value(2)]
        public string TargetModel { get; set; }
        [Value(3)]
        public string TArgetItem { get; set; }
    }
```
Here you can see I have 2 Option class that map the same verb "copy".
Is that possible ? 
Or do I have to manage this case by hand using a more generic CopyOptions as this : 
```c#
 [Verb("copy")]
    public class CopyRubriqueModelToModelOptions : BaseOptions
    {
        [Value(0)]
        public List<string> copyParameters { get; set; }
    }
```

**Comment by moh-hassan** [comment]
Many class for the same verb can't be used.

I think it's better to use different meaningful name for the verbs. e.g:

     [Verb("copy-in-place")]
      public class CopyRubriqueInPlaceOptions : BaseOptions
      {
        //....rest of code
      }
      
       [Verb("copy-to-model")]
      public class CopyRubriqueModelToModelOptions : BaseOptions
      {
       //....rest of code
      }

So help can describe the usage as you intend.

The usage:

          myapp  copy-in-place root moel source target
          myapp  copy-to-model root  SourceModel  ....

**Comment by b3b00** [comment]
@moh-assan your answer is sensible. i will rethink my design. issue closed

**Comment by b3b00** [comment]
@moh-hassan your answer is sensible. i will rethink my design. issue closed
