### ISSUE TITLE
Order of option order in help text

### ISSUE THREAD

**Issue by tehkyle** [commandlineparser/commandline#482]
Appologies if this is already possible or answered somewhere, I couldn't find details in the docs or searching existing issues.

Could the Help Text generator take an order for the listed options, such as by Required first, then Alphabetical?

We have a set of available verbs that have some shared options so have built our option classes to be inherited. Currently the help builder lists these options in inherited order, but we would like to at least collect required options at the top.

**Comment by moh-hassan** [comment]
The feature is not available.
PR is welcome.

**Comment by b3b00** [comment]
I take the issue. PR will come in some days may be hours.
So the solution will be : order option by

1. required than optional
2. alphabetical order.

Would you like a way (C# attribute or some param on HelpTExt.AutoBuild(...)) to enable it ?
I would go for an lambda that specify the desired order with a static lambdas for

- actual ordering
- your desired ordering (required than alpha)
- maybe others like just alpha

**Comment by b3b00** [comment]
I made some dev and finally reworked it.
Coming PR allow to redefine order using a ```Comparison<ComparableOption>``` function. 
I choose to create a ComparableOption from the Specification class to not break existing visibility rules.
To redefine order you then have to provide de Comparison object as a static value of HelpText class before calling AutoBuild :

```c#
HelpText.OptionComparison = HelpText.RequiredThenAlphaComparison;
var helpMessage = HelpText.AutoBuild(parseResult,...) 
```

Maybe not the perfect solution but it works well.
PR comes with the  order that @tehkyle proposed.
When no comparison is provided before calling AutoBuild then it defaults to the current behavior (declaration order)
