### ISSUE TITLE
Command Line Parser - Options that use arrays triggers exception that “Sequence contains no elements”

### ISSUE THREAD

**Issue by donnyv** [commandlineparser/commandline#487]
Had the same issue and this solved it. For some reason it has to have default values of option arrays. Also you can't use a List<>.
https://stackoverflow.com/questions/51198995/command-line-parser-options-that-use-arrays-triggers-exception-that-sequence

**Comment by moh-hassan** [comment]
In version 2, all sequence are becoming `IEnumerable<T>` 
From [Documentation](https://github.com/commandlineparser/commandline/wiki/Getting-Started):

>Option works much like in previous versions, but it can be applied to scalar or sequence values (IEnumerable<T>).

>When applied to sequences you can also define Min and Max properties to specify a range of values.

change `string[]` to `IEnumerable<string>` as given below:

      public class MyOptions
      {
        [Option('h', "sayhello")]
        public string HelloMessage { get; set; }

        [Option('v', "versioninfo")]
        public string VersionInfo { get; set; }

        [Option('c', "changenode")]
        //public string[] ChangeNode { get; set; }
        public IEnumerable<string> ChangeNode { get; set; }

        [Option('g', "getnode")]
        //public string[] GetNode { get; set; }
        public IEnumerable<string> GetNode { get; set; }
    }
