### ISSUE TITLE
Parsing argument Multiple times

### ISSUE THREAD

**Issue by shengzhizhou** [commandlineparser/commandline#489]
Hi,
Can I parsing certain argument multiple times? There is one requirement for my project that required substitute strings in text file with input string, cmd like this "-v var1:val1 -v var2:val2". So that all instances  of $var1$ and $var2$ can substitute with val1 and val2.

**Comment by moh-hassan** [comment]
>Can I parsing certain argument multiple times?

No, but:

You can use sequence argument  `IEnumerable<string>` and separate every pair with semicolon   separator   like:

       myapp -v var1:val1;var2:val2

Decalre Options classs as:

        public class Options
        {
            [Option('v',  Required = true, Separator=';', HelpText = "Input vars")]
            public IEnumerable<string> Data { get; set; }			
		  
	}

Then split every pair with `':'`

Try it [online](https://dotnetfiddle.net/HhnpqT)

**Comment by shengzhizhou** [comment]
Thank you! I just found out that if I declare a option like this
```
[Option('v', "sub", Required = false, HelpText = "Subtitute Variable")]
public IList<string> SubsituteList { get; set; }
```
I can ignore the separator, just use space to separate each variable 
so my argument like this will work:
```
--sub var1:test var2:test2
```
Is this the correct way to implement it without using separator?

**Comment by moh-hassan** [comment]
>Is this the correct way to implement it without using separator?

Yes, It's correct to use space as argument separator and ignore the separator in `OptionAttribute` as you did .

Although IList<string>  may work , the library use  `IEnumerable<T>` for all collections: Array, List, IList,..

           [Option('v', "sub",  HelpText = "Subtitute Variable")]      //Required = false by default
            public IEnumerable<string> SubsituteList { get; set; }

Modified [code ](https://dotnetfiddle.net/UrcGru)without separator
