### ISSUE TITLE
Immutable options type ctor not seen

### ISSUE THREAD

**Issue by JGCreator** [commandlineparser/commandline#499]
```
class Program
    {
        static void Main(string[] args)
        {
            Parser.Default.ParseArguments<CmdOptions>(args)
                  .WithNotParsed(e => Environment.Exit(e.Count()))
                  .WithParsed(WriteReportData);
        }
    }

    public class CmdOptions
    {
        public CmdOptions(string user, string token, int releaseId, int buildId)
        {
            User = user;
            Token = token;
            ReleaseId = releaseId;
            BuildId = buildId;
        }

        [Option('b', "buildid", Required = true, HelpText = "The build id associated with the release")]
        public int BuildId { get; }

        [Option('r', "releaseid", Required = true, HelpText = "The release id for fetching")]
        public int ReleaseId { get; }

        [Option('t', "token", Required = true, HelpText = "The authentication token (agent oAuth or user PAT)")]
        public string Token { get; }

        [Option('u', "user", Required = false, Default = "", HelpText = "Username value to send when using basic authentication with a PAT")]
        public string User { get; }
    }
```

Arguments debugged:
`-u userFirstName -r 123 -b 4567 -t someToken`

Exception thrown:
![image](https://user-images.githubusercontent.com/5280734/62829454-5c1e0980-bbc3-11e9-89d3-c5c44e3d1345.png)

**Comment by moh-hassan** [comment]
It seems that Immutable Options work fine if the constructor parameters have the same order as the Properties of the class  and their names match the corresponding properties (case insensitive).

As a workaround solution, modify the constructor  parameters to be:

    public CmdOptions(int buildId, int releaseId, string token,string user )
        {
          ...
        }
 

A working [demo ](https://dotnetfiddle.net/v9Fv5T)

This limitation of Immutable class may be fixed in PR.

**Comment by moh-hassan** [comment]
PR is welcome.

**Comment by moh-hassan** [comment]
If the constructor parameters are not valid as described in [wiki ](https://github.com/commandlineparser/commandline/wiki/Immutable-Options-Type), it raise this exception.
You can generate valid constructor as described in wiki and avoid this exception.
The exception is expected.
.
