### ISSUE TITLE
Ability to use HelpText.AutoBuild() without parser results

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#5]
<a href="https://github.com/zii-dmg"><img src="https://avatars2.githubusercontent.com/u/2846896?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zii-dmg](https://github.com/zii-dmg)**
_Thursday Jun 20, 2013 at 07:27 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/88_

----

Using commit e00dd9f086.

Sometimes Parser.ParseArguments throws exceptions (for example, InvalidOperationException: "Sequence contains more than one matching element") and ParseResult doesn't created, but I still need to show help usage to user. Without ParserResult I can't do this easily.

Or maybe I doesn't understand how to use help usage auto generation on exceptions.

**Comment by ericnewton76** [comment]
<a href="https://github.com/mystcreater"><img src="https://avatars1.githubusercontent.com/u/230587?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mystcreater](https://github.com/mystcreater)**
_Wednesday Jun 17, 2015 at 17:55 GMT_

----

Today, I had this exception because I tried to use an options class which inherit from another options class. Seems the library doesn't support inheritance.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Wednesday Jun 17, 2015 at 18:52 GMT_

----

As you can see, @mystcreater, FSharp façade API as been moved to specific branch (this was not the case when @zii-dmg posted).

Since the work on pre-release 2.0 has been halted for a while (but as you can see from GitHub activity I'm really back to work hard on the project), as now I prefer to invest time in stabilizing library C# kernel.

I've added a very simple F# example as [fsharp script](https://github.com/gsscoder/commandline/blob/master/fsxdemo/cmdlinelib.fsx).

Once 2.0 stabilizes (or if some developer want to help) and there's interest in: I'll be very glad to continue development of an F# surface API (`CommandLine.FSharp.dll`).

For the moment I suggest to use directly `CommandLine.dll` directly (since issues are closed every day, I suggest you compile from sources -- when a 2.0.x-pre is released in NuGet, I'll ping it via Twitter).

I'm too currently using 2.0.x-pre from F# for a little project I plan to open in next weeks, so if possible, I ask you to post the these types (so discussion can continue).

_Please note that 2.0 is still pre-release quality software: also if very latest source are (as said) each day more stable..._

**Comment by moh-hassan** [comment]
Resolved.
To show help, call: `myapp --help`
