### ISSUE TITLE
First two characters in flag are accepted regardless of what follows

### ISSUE THREAD

**Issue by jcakmn** [commandlineparser/commandline#501]
`    [Verb ("payments-match", HelpText = "Match unsolicited payments to Wbs")]
    public class MatchPaymentsCommand : Command {
​
        [Option ('f', "file", Required = true, HelpText = "The path of the Wbs file")]
        public string File { get; set; }
​
        [Option ('s', "submit", Required = false, Default = false, HelpText = "Set to true to create transfers")]
        public bool Submit { get; set; } = false;
​
        [Option ('p', "password", Required = false, HelpText = "The password of the WBS file")]
        public string Password { get; set; }
...
​
}`

If I enter -submit, it will recognised `-s` but not the following characters, I would expect it to error/throw in this scenario.

**Comment by moh-hassan** [comment]
`submit` should be prefixe by double dash "--"
This is working:

         myapp payments-match --submit  -f wbs_file
         myapp payments-match  -s  -f wbs_file
