### ISSUE TITLE
Verb without options?

### ISSUE THREAD

**Issue by FedericoBinda** [commandlineparser/commandline#504]
Hi!

Is it possible to have a verb that runs without additional options? I tried the following (F#):

```
[<Verb("test", HelpText = "Generic test mode.")>]
type TestOptions = {
    Placeholder : string
}
```

However it is not elegant and, most most importantly, it does not work.

**Comment by FedericoBinda** [comment]
Update: I already found that decorating the "Placeholder" with a value attribute works. However, it is still not elegant. Is there a more elegant way to do it?
```
[<Value(0, MetaName="Placeholder", Required = false, HelpText = "Placeholder")>] 
Placeholder : string
```

**Comment by moh-hassan** [comment]
>Is it possible to have a verb that runs without additional options?

It can be, and you process parser result based on the verb.
>Is there a more elegant way to do it?

yes, as you did and arguments can be:
```
myapp test my_place-holder
```
Have a look to this F# [demo](https://github.com/commandlineparser/commandline/blob/master/demo/fsharp-demo.fsx)
