### ISSUE TITLE
Which version should be used by default for new projects? 2.6.0 or 1.9.71.2 ?

### ISSUE THREAD

**Issue by mthgr** [commandlineparser/commandline#505]
I've been using 1.9.71.2 for quite a while now (I like it a lot) and I'm considering upgrading to 2.6.0.

This link:

https://github.com/gsscoder/commandline/wiki/Latest-Version

says that 2.6.0 is still in Alpha?

I saw another section that says that version 2 was promoted to Beta.

Is this accurate? Should 1.9.71.2 still be used by default for new projects? Is 2.6.0 considered ready for production?

Thanks!

**Comment by moh-hassan** [comment]
Thanks @mthgr  for using CommandLineParser library.

The link  says: Version 2.0.9-alpha
The [original  project v1.x ](https://github.com/gsscoder/commandline) has moved to this repo.
version [2.6.0](https://www.nuget.org/packages/commandlineparser) is stable and support net4x and netstandard2.0 and have new features.
You can migrate to v2.6.0

For Migration guideline read [here](https://github.com/commandlineparser/commandline/issues/318) and [here](https://github.com/commandlineparser/commandline/wiki/Upgrading-from-previous-v1.9)
How to use: read readme and [wiki](https://github.com/commandlineparser/commandline/wiki)
Try the [demo](https://github.com/commandlineparser/commandline/tree/master/demo)

[Onlin Demo](https://dotnetfiddle.net/YjTb9L) v1.9
[Online Demo](https://dotnetfiddle.net/NpCLX6) migrated from v1.9  to v2.6
