### ISSUE TITLE
Allow to modify the parser settings after initialization

### ISSUE THREAD

**Issue by TristanApc** [commandlineparser/commandline#506]
At the moment, changing the settings of a Parser object throws an exception. This prevent to run clean code like:

```csharp
var command = default(RootCommand);

using (var parser = new Parser())
{
   // The parser didn't parse the arguments yet, I should be able to change any settings.
   parser.Settings.CaseInsensitiveEnumValues = true;

   var parserResult = parser.ParseArguments<RootCommand>(args);
}
```

**Comment by moh-hassan** [comment]
Parser.Settings is **readonly**  and has only **Get** without Set as shown [here ](https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/Parser.cs#L72). 
It should be only configured via the the constructor of the Lazy Parser class.


          using (var parser = new CommandLine.Parser(o=>{
	                                                     o.HelpWriter=null;
	                                                  }))
	{
	   
	   var parserResult = parser.ParseArguments<RootCommand>(args);
            //...
	}
Note: CaseInsensitiveEnumValues  is not a property for the Parser but used for HepText
