### ISSUE TITLE
aliases like git?

### ISSUE THREAD

**Issue by furesoft** [commandlineparser/commandline#507]
can i make alias commands like in git?

**Comment by moh-hassan** [comment]
GIT is an application use C language and create aliases as show in the source code [here ](https://github.com/git/git/blob/master/alias.c). 
It parses the options based on the standard short/long commandline option names.

Aliases are used to create shorter commands that map to longer commands and it's outside the scope of the library.

You can create your own alias for your application  using a configuration file that store your alias  and pre-process the Main arguments and replace the alias with its corresponding text  in the configuration file, then pass the result to the Parser.
