### ISSUE TITLE
Wiki of badly outdated - please update it.

### ISSUE THREAD

**Issue by ns88ns** [commandlineparser/commandline#508]
Wiki of the project is badly outdated.

Today checked for updated of the project - VS reported the latest stable version of the project is 2.6.0. However, Wiki reports that 2.0 is still alpha. How should I understand it? Is 2.0 only still alpla or are 2.* alpha or are 2.* .* alpha? This isn't clear.

Backward compatibility. Actually it is very good thing - just try to implement it and you will be excited. In 2.6.0, verb DefaultValue has been changed to ... ? Yes! To Default. What I should do? It is correct - I have to modify other code. I re-learned all the project's Wiki and found nothing about this change. Just imagine: no any actial info in the project's Wiki! How, do you think, I should get actual data about changes in the project? Wiki? Yes, but it is badly outdated!

This is actually serious bug. Please fix it. As software developer, who publish its software for wide usage in public - you must keep documentation actual.

Thank you so much in advance for respecting of end-users.

**Comment by ns88ns** [comment]
Also missed options:

- OptionList
- HelpOption

Any examples how to migrate out from these options?

Francly speacking, this update is actually good way to get a lot of stupid re-code work on empty place... Do I actually need it? It looks as the best way is don't use this project in own code... Now I have to waste several hours to re-code my solutions... I'm not sure it is what I dreamt about.

**Comment by illnyang** [comment]
Honestly, I found myself skimming through the issue tracker more often than the actual wiki.

**Comment by moh-hassan** [comment]
Wiki show the current version [here](https://github.com/commandlineparser/commandline/wiki)
The text

               CommandLine 2.0.201-alpha
is a sample of an output of a demo application version in the generated help text, not an indication of the library version.
It's Corrected to:

       yourapp 2.0.201-alpha

**Note**: Wiki can be corrected by contributors as suggested [here](https://github.com/commandlineparser/commandline/issues/486)
