### ISSUE TITLE
Customizing options help text

### ISSUE THREAD

**Issue by michmela44** [commandlineparser/commandline#509]
I am custom handling the error text as advised in the help because I needed to customize a couple things.

I was able to use the helpers in CommandLine.Text namespace to recreate most of the things I needed to, but I don't see how I can recreate the help text for the options in the same format as they print by default?

Is there that can get the prebuilt options help string for me in the same format?

**Comment by moh-hassan** [comment]
This code generate help string like default help.

             var parser=new CommandLine.Parser(x=>{x.HelpWriter=null;});		
		var parserResult=	parser.ParseArguments<Options>(args);		
		parserResult.WithParsed<Options>(o => { Console.WriteLine("parsed"); })
			   .WithNotParsed(errs => 
						{
						    var helpText = HelpText.AutoBuild(parserResult, h =>h,e =>e);
						   Console.WriteLine(helpText);
						});
