### ISSUE TITLE
Using IEnumerable for Option is always 'Required'

### ISSUE THREAD

**Issue by sunssd** [commandlineparser/commandline#510]
[Option('a', "aa", Required = false, Separator = ',')]
        public IEnumerable<string> A { get; set; }
[Option('b', "bb", Required = false)]
        public string B { get; set; }
[Value(0, Required = true)]
        public string C { get; set; }

For some reasons, if I only specify Option A and C, I will get the following error:

ERROR(S):
  A required value not bound to option name is missing.
  Error setting value to option 'a, aa': Check if Option or Value attribute values are set properly for the given type.

**Comment by moh-hassan** [comment]
This issue is similar to the bug #454.
Named Sequence option followed by a value option causes an error.

       myapp     vv -a xyz    //working: option value before named sequence option.
      myapp     -a xyz   vv // raise Exception:  named sequence option followed by a value option.

Have a look to this [demo](https://dotnetfiddle.net/UrcGru)

**Comment by rmunn** [comment]
This will be fixed by #684 once it's merged in.
