### ISSUE TITLE
MutuallyExclusiveSet Migration from 1.9.71.2 to SetName in 2.6 issues 

### ISSUE THREAD

**Issue by mthgr** [commandlineparser/commandline#514]
I'm trying to migrate multiple projects from 1.9.71.2 to 2.6

These projects have more than 2 MutuallyExclusiveSet () and I can't find a straightforward way to migrate them to use the new SetName.

Do I understand correctly that for all end and purposes in 2.6 we can't have more than 2 different SetName?

Here is an example in from 1.9.71.2: 

        [Option("french", Required = false, MutuallyExclusiveSet = "language", HelpText = "")]
        public bool French { get; set; }
        
        [Option("english", Required = false, MutuallyExclusiveSet = "language", HelpText = "")]
        public bool English { get; set; }

        [Option("currentday", Required = false, MutuallyExclusiveSet = "day", HelpText = "")]
        public bool CurrentDay { get; set; }
        
        [Option("previousday", Required = false, MutuallyExclusiveSet = "day", HelpText = "")]
        public bool PreviousDay { get; set; }

	[Option("insidetimerange", MutuallyExclusiveSet = "timerange", HelpText = "")]
        public bool InsideTimeRange { get; set; }

        [Option("outsidetimerange", MutuallyExclusiveSet = "timerange",  HelpText = "")]
        public bool OutsideTimeRange { get; set; }

        [Option("notimerange", MutuallyExclusiveSet = "timerange",  HelpText = "")]
        public bool NoTimeRange { get; set; }

How can I got about migrating this...? I realize this could be refactored to get rid of some Set (like Language could obviously be converted to a string value instead of having 2 bool for different language) but we made extensive use of MutuallyExclusiveSet and I have some scenarios where refactoring is not that straightforward or desirable.

From the documentation, I understand that this isn't supported in 2.6.

Any pointers will be much appreciated.

**Comment by moh-hassan** [comment]
MutuallyExclusive is supported in v2.x, but its usgae is different than v1.x, so wiki of v1.x is not valid.
Have a look to this SO [answer](https://stackoverflow.com/a/10774994/3142139) and [here ](https://github.com/commandlineparser/commandline/issues/246#issuecomment-376872194) and [here ](https://github.com/commandlineparser/commandline/issues/419)
 
In v1.x all options sharing the same SetName would be mutually exclusive. 
**In version 2.x SetName defines (sets of) options that** **belong together**, so MutuallyExclusiveSet  options now need to have a different **SetName**.

I think you may need to re-arrange your options as groups of one SetName.

**Comment by moh-hassan** [comment]
**Migration Example:**
I have divided your options to two groups(SetName): group1 and group2 and modify Language option to string as you suggested.

MutuallyExclusiveSet  is obsolete, use SetName 

    class Options
    {
       [Option("lang", Required = false,  HelpText = "")]
        public string Language { get; set; }
        

        [Option("currentday", Required = false, SetName = "group1", HelpText = "")]
        public bool CurrentDay { get; set; }
        
        [Option("previousday", Required = false, SetName = "group2", HelpText = "")]
        public bool PreviousDay { get; set; }

        [Option("insidetimerange", SetName = "group1", HelpText = "")]
        public bool InsideTimeRange { get; set; }

        [Option("outsidetimerange", SetName = "group2",  HelpText = "")]
        public bool OutsideTimeRange { get; set; }

        [Option("notimerange", SetName = "group2",  HelpText = "")]
        public bool NoTimeRange { get; set; }
    }

In this example, you use either group1 options or group2 options. Mix is not allowed.
Language option can be used with any group.

**This is valid commandline:**
       
         --Lang english  --CurrentDay --InsideTimeRange 
        --Lang french --PreviousDay --OutsideTimeRange 

**This is invalid commandline:**

 //mix options between two exclusive groups:
      
         --Lang english  --CurrentDay --OutsideTimeRange          
        --Lang french --PreviousDay --InsideTimeRange

**Comment by mthgr** [comment]
Thank you for taking the time to explain.

I will refactor and consolidated the grouping.

It would have been nice to keep the old MutuallyExclusiveSet side by side with the new SetName and implement a check to make sure either SetName or MutuallyExclusiveSet is used in a project (not both at the same time). 

Maybe this way it would not have been a breaking change and the flexibility of the old MutuallyExclusiveSet could have been preserved with minimal effort...?
