### ISSUE TITLE
Improvement: short form for verbs 

### ISSUE THREAD

**Issue by yuryskaletskiy** [commandlineparser/commandline#517]
We need to have some way to specify short version of the verb string, like

[Verb("inventory", alias="inv" HelpText="Show the Inventory")]
class ....

**Comment by moh-hassan** [comment]
It's planned to add this feature.

**Comment by moh-hassan** [comment]
It is done in pr [636](https://github.com/commandlineparser/commandline/pull/636)

**Comment by Khaos66** [comment]
So why ist this still an open issue?

**Comment by johnjaylward** [comment]
@yuryskaletskiy or @ericnewton76 , can you close this issue?

**Comment by yuryskaletskiy** [comment]
Great, closing that.
