### ISSUE TITLE
Get "the rest" of the arguments?

### ISSUE THREAD

**Issue by Ams627** [commandlineparser/commandline#518]
I may be missing something here, but does the parser consume all of the arguments?

Let's say I have a verb "add" which has an optional -r argument (-r in my case means replace existing). The after the verb I have a long list of names - how to I get that list of names?

Example commands would be:

```
myprog add fred jim sheila
myprog add -r harry sally angela bert
```

In the first case I want an array or list containing fred jim sheila - in the second I want an array or list containg harry sally angela bert.

**Comment by moh-hassan** [comment]
>does the parser consume all of the arguments?

Yes, if the argument has a corresponding Property in the option class.


For the command:

        myprog add -r harry sally angela bert

You can define option as:

         [Verb("add")]
        class AddOptions
        {
            [Option('r')]		  
            public IEnumerable<string> Replace { get; set; }
        }

For the command:

        myprog add fred jim sheila

You can define option as:    
   
         [Verb("add")]
        class AddOptions
        {         
		         [Value(0)]
            public IEnumerable<string> Replace { get; set; }
        }
