### ISSUE TITLE
more than one set throws errors.

### ISSUE THREAD

**Issue by rethabile-dev** [commandlineparser/commandline#519]
commandline version=2.6.0.0

Having more than one set throws errors.

    class Options
    {
        [Option('m', "opta", HelpText = "Option A", SetName = "myset1")]
        public bool? IsSelected { get; set; }

        [Option('r', "optb", HelpText = "Option B", SetName = "myset1")]
        public IEnumerable<string> Items { get; set; }
		
        [Option('i', "warmup", HelpText = "Warmup test.", SetName = "warmup")]
        public bool IsWarmUp { get; set; }

        [Option('l', "limit", HelpText = "warm up limit", SetName = "warmup", Default = 100)]
        public int Limit { get; set; }
    }

Running the following spit up the error:
    dotnet run -m true -r all -i true -l 2

ERROR(S):
Options: 'm, opta', 'r, optb' are not compatible with: 'i, warmup', 'l, limit'.
Options: 'i, warmup', 'l, limit' are not compatible with: 'm, optq', 'r, optab'.

Is the behavour intented or am i missing something?

**Comment by moh-hassan** [comment]
**MutuallyExclusiveSet  in v2 support One and Only One set at a time**

**This is valid:**

           dotnet run -m true -r all       //     only SetName = "myset1"
           dotnet run -i true -l 2         //       only SetName = "warmup"

**This is not valid:**

               dotnet run -m true -r all -i true -l 2  //two sets  at a time

**Comment by rethabile-dev** [comment]
Thanks for clarifying that @moh-hassan

**Comment by moh-hassan** [comment]
A [help ](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)page with demos is added to wiki.
