### ISSUE TITLE
[2.0] InvalidOperationException when duplicate option is set on inherited class

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#52]
<a href="https://github.com/tpluscode"><img src="https://avatars0.githubusercontent.com/u/588128?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tpluscode](https://github.com/tpluscode)**
_Wednesday Nov 18, 2015 at 10:07 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/266_

----

I've made a mistake and declared an option with same short name on both base and inherited class. 
Here's the stack trace tip and sample code below

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommandLine.Core.TypeLookup.FindTypeDescriptorAndSibling(String name, IEnumerable`1 specifications, StringComparer comparer)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__8(String name)
```

```
public abstract class BaseOptions
{
    [Option('d', "devSeeds", HelpText = "Seed database with sample data")]
    public bool IncludeDeveloperSeeds { get; set; }
}

[Verb("local", HelpText = "Updates local database")]
public class LocalOptions : BaseOptions
{
    [Option('d', "database", HelpText = "Database to upgrade")]
    public string DatabaseName { get; set; }
}
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Nov 18, 2015 at 20:11 GMT_

----

What behavior do you expect to see here? Just a more helpful error message?

**Comment by ericnewton76** [comment]
<a href="https://github.com/tpluscode"><img src="https://avatars0.githubusercontent.com/u/588128?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tpluscode](https://github.com/tpluscode)**
_Wednesday Nov 18, 2015 at 21:55 GMT_

----

That would be nice. `Sequence contains more than one matching element` doesn't tell much and I didn't spot the mistake at first

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Nov 18, 2015 at 22:13 GMT_

----

Got it. I'll make sure the `result.Errors` property contains details about which name is duplicated. Make sure to check there for any errors as the parser will (most likely) no longer throw an exception when you make this mistake.

**Comment by ericnewton76** [comment]
<a href="https://github.com/Mizipzor"><img src="https://avatars1.githubusercontent.com/u/139879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mizipzor](https://github.com/Mizipzor)**
_Friday Jan 29, 2016 at 22:32 GMT_

----

@nemec did you ever get around to do this and just forgot to close, or is this still open?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Saturday Jan 30, 2016 at 02:17 GMT_

----

No, I haven't had a chance to get to it.

**Comment by tomzo** [comment]
I've another case when this unhelpful error is thrown.
When type arguments are not unique in extension method `ParseArguments`.
E.g. `PackOptions` repeated like below:
```
CommandLine.Parser.Default.ParseArguments<VersionOptions,PackOptions,SmokeOptions, PackOptions>(args)
```

**Comment by ericnewton76** [comment]
@tomzo interesting catch.  Your scenario is fairly easier to catch then the above one.  Can you create another issue for your specific problem so we can track it separately?
