### ISSUE TITLE
Wiki: Now include complete API documentation for v2.6.0

### ISSUE THREAD

**Issue by moh-hassan** [commandlineparser/commandline#520]
Wiki have been updated to:
- Include API documentation for Version [2.6.0](https://github.com/commandlineparser/commandline/wiki/API-V2.6.0)
- Help page for [Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options) with online demo.

**Comment by garyng** [comment]
The indentations are all messed up though...

https://github.com/commandlineparser/commandline/wiki/Getting-Started:
![image](https://user-images.githubusercontent.com/4453664/67728988-51d51400-fa2a-11e9-8776-abe6e336bf0f.png)

https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options:
![image](https://user-images.githubusercontent.com/4453664/67728941-22bea280-fa2a-11e9-8424-491ccc0daccb.png)

https://github.com/commandlineparser/commandline/wiki/How-To:
![image](https://user-images.githubusercontent.com/4453664/67729039-82b54900-fa2a-11e9-84c3-144394b74368.png)

**Comment by moh-hassan** [comment]
Thanks @garyng  for reviewing wiki and your suggestions.
The indentations are done.
