### ISSUE TITLE
Multiple input parameters

### ISSUE THREAD

**Issue by HolyOne** [commandlineparser/commandline#522]
Does commandline support multiple input parameters such as?

combine.exe -i file1.txt -i file2.txt -i file3.txt -o all.txt

I can do this with IEnumerable and Seperator parameter of Option Attribute but I need multiple options with same name.

**Comment by moh-hassan** [comment]
No,  it doesn't support multiple input parameters with the same name.
It's planned to add this feature.

**Comment by josesimoes** [comment]
I believe this is a duplicate of #357...

**Comment by rmunn** [comment]
PR #594 would implement this feature; most of the work was done by @tydunkel, I just rebased his work onto the current state of the `develop` branch and created the PR.

**Comment by josesimoes** [comment]
Awesome!! Thank you!! 👏 🎉 😃
