### ISSUE TITLE
Issue with IgnoreUnknownArguments and duplicate values

### ISSUE THREAD

**Issue by kostasvl** [commandlineparser/commandline#525]
I was affected by the issue described here: https://stackoverflow.com/questions/35829775/assigning-the-same-value-to-2-different-properties-using-commandline-parser-nuge, and I did a quick search here and I don't think there's an open issue for it.

Basically, with IgnoreUnknownArguments=true, if some options happen to have the exact same value, you get an error.

The ugly workaround I mention here would work: https://github.com/commandlineparser/commandline/issues/243#issuecomment-541818479

**Comment by moh-hassan** [comment]
>if some options happen to have the exact same value, you get an error.

Can you give an example for the commandline args to explain , and what is supposed for the filter to do.

**Comment by kostasvl** [comment]
Here's an example:

```
public class MyOptions
{
	[Option("Option1", Required = true)]
	public string Option1 { get; set; }
}

Parser myParser = new Parser(settings => settings.IgnoreUnknownArguments = true);

bool result = myParser.ParseArguments<MyOptions>(arguments).MapResult(
	options => true,
	errors => false
);
```

This returns false with arguments like "_--Option1="**123**" --**Unknown**Option="**123**"_"

The errors are a pair of MissingValueOptionError and MissingRequiredOptionError, both related to "Option1". If I remove Required=true, I just get the MissingValueOptionError.

Conclusion: It's triggered by having an unknown option with the same value as a known option.

Thanks for taking an interest!

**Comment by moh-hassan** [comment]
This is a special case and it doesn't matter for the parser.
`IgnoreUnknownArguments' is considered as a filter to neglect Unknown Arguments or fire an error based on the setting of 'IgnoreUnknownArguments' and has zero performance issue.

The filter done [in issue 243](https://github.com/commandlineparser/commandline/issues/243#issuecomment-541818479) should be applied with care because the parser apply different rules
based on the type of token the next token and others.

**Comment by kostasvl** [comment]
Thanks. I'm not sure what you mean by "_it doesn't matter for the parser_". The values of some options can make the parsing operation fail. This seems strange to me.

I'd really like to replace that filtering hack with an actual fix :)

**Comment by moh-hassan** [comment]
I mean by "it doesn't matter for the parser" that parser don't check for duplicated Value tokens like  '123' but check for duplicated named tokens that start with - or --.
It  check the token against the specs which is defined in Options class and fire errors to user what is wrong in the arguments.
In real cases, equal values for options may be exist.

**Comment by kostasvl** [comment]
I see. Yes, agreed. At least it's an easy repro. I am using 2.6.0, but the SO post in the above link is from 2016, so this isn't new.

If it weren't for that "easy" hack, I'd try to convince my team to let me investigate a proper fix. For now, I just opened this issue :). Thanks again!

**Comment by martyvona** [comment]
I think this is biting me too.  Let me try to restate the problem.  Say --foo is a known argument and --bar is an unknown argument, and you are parsing with IgnoreUnknownArguments=true.

A command line with arguments like "--foo=1 --bar=2" is parsed fine, as it should be.

But just changing the value to which the unknown argument --bar is assigned to match the value to which known argument --foo is assigned , i.e., "--foo=1 --bar=1" results in an error.  It should not matter what value is assigned to --bar, it should be ignored because it's an unknown argument.

**Comment by AlexanderButs** [comment]
I'm experiencing such issue too. Any workarounds, guys?

**Comment by martyvona** [comment]
all I'm doing is manually filtering out unknown arguments before I pass them in.  The code I use to this is hacky and makes various assumptions so I hesitate to post it here.

**Comment by kostasvl** [comment]
I had already posted my hack for solving issue 243, so here it is again, slightly cleaner.

NOTE: This assumes the arguments are in the form "--longName=value". Modify accordingly if not.  **There are no guarantees**! Watch out for the stuff Moh said above (https://github.com/commandlineparser/commandline/issues/525#issuecomment-547662021): "_...should be applied with care because the parser apply different rules based on the type of token the next token and others._"

```
public static bool ParseOptionsIgnoringUnknowns<OptionsType>(IEnumerable<string> arguments, out OptionsType options_to_assign)
	where OptionsType : class
{
	// We could have used a custom parser with IgnoreUnknownArguments=true, but that can throw an error.
	// See https://github.com/commandlineparser/commandline/issues/525.
	// Hence we are filtering the arguments here to only include the ones that the Options class will want to parse.
	// We do this by walking the Options' members, and looking for the [Option] attribute. The long name of the
	// option should be present in the arguments, usually in the form "--longName=value".
	IEnumerable<string> known_arguments = arguments.Where(argument => typeof(OptionsType).GetMembers().Any(member =>
	{
		OptionAttribute option_attribute =
			member.GetCustomAttributes(typeof(OptionAttribute), true).Cast<OptionAttribute>().SingleOrDefault();

		return option_attribute != null && argument.Contains(option_attribute.LongName);
	}));

	OptionsType parsed_options = null;

	bool result = Parser.Default.ParseArguments<OptionsType>(known_arguments).MapResult(
		options => { parsed_options = options; return true; },
		errors => false
	);

	options_to_assign = parsed_options;

	return result;
}
```

**Comment by AlexanderButs** [comment]
Thanks guys. I've already found workaround in linked issue. Waiting for proper fix from library author.
