### ISSUE TITLE
How to Only Supply the Value without the Parameter Name?

### ISSUE THREAD

**Issue by erlange** [commandlineparser/commandline#526]
I might have missed something along the docs, but how do I tell the parser to treat the first value (being, in my case, the only required value) without having to supply the parameter name?

Instead of this:
`Myapp --f fileToOpen.docx --readonly --lock`
or
`Myapp -f fileToOpen.docx -r -l`

I want to achieve this:
`Myapp fileToOpen.docx --readonly --lock`
or just
`Myapp fileToOpen.docx -r -l`

I need to omit the the `-f` or `--file` parameter name and supply just the value.

Thanks in advance

**Comment by moh-hassan** [comment]
You use ValueAttribute instead of OptionAttribute:

```
class Options
	   {
	        [Value(0) ]		//positional argument   
		   public string FileName { get; set; }
		   
		   [Option('l',"lock"  ) ]		   
		   public bool Lock { get; set; }		   
		    [Option('r',"readonly"  ) ]		   
		   public bool ReadOnly { get; set; }   		  
	   }
```
You can pass the command as:

               Myapp fileToOpen.docx -r -l
or

         Myapp -r -l  fileToOpen.docx 
For more details see [wiki ](https://github.com/commandlineparser/commandline/wiki/Getting-Started)

**Comment by erlange** [comment]
Thanks for your prompt response @moh-hassan
