### ISSUE TITLE
Is there a way to customize the string returned by --version?

### ISSUE THREAD

**Issue by Xorcist77** [commandlineparser/commandline#527]
I use semantic versioning and would like to be able to add more detail to my versions, for example:

v1.2.3-alpha.1
v1.2.3-beta.2
v1.2.3-rc.3
v1.2.3
etc...

is there a way to override this functionality or customize it in some way.

**Comment by moh-hassan** [comment]
in the project file .csproj set the version to the value you need or provide it during build:
```
 <PropertyGroup>
          .....
           <Version>1.2.3-alpha.1</Version>
 </PropertyGroup>
```
when you run
```
           myapp --version
```
it'll display
```
        myapp 1.2.3-alpha.1
```

**Comment by Xorcist77** [comment]
I added the line, but it didn't change anything, I think that may only work for .NET Core applications? It still seems to be pulling my version info from my AssemblyInfo.cs (this is a .NET 4.7 application).

**Comment by moh-hassan** [comment]
This applied to the new style SDK projects, in vs2017 + ,  
AssemblyInfo is not used by default, and msbuild generate AssemblyInfo  during build with the corresponding elements of the csproj file.
I test this in net461 and it's working fine.

If you are using assemplyinfo:
In assemplyinfo.cs, add this line

                 [assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.2.3-alpha.1")]

Add this line to the project

               <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

Note:   AssemblyVersion , AssemblyFileVersion are not used for version.

**Comment by Xorcist77** [comment]
That did the trick! Thanks!

**Comment by moh-hassan** [comment]
Glad that you resolved your issue.
A new wiki [page ](https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration#setting-assemplyinfo-attributes) is added to show setting AssemplyInfo Attributes
