### ISSUE TITLE
If one option is set, require another?

### ISSUE THREAD

**Issue by claym** [commandlineparser/commandline#532]
I'm trying to identify if it's possible to base the requirement of one option upon the usage of another option.

For example, if a user provides the "start" option, I'd like that to require the "end" option. And vice-versa.

However, if "start" is not provided, "end" is not required.

Thanks!

**Comment by moh-hassan** [comment]
Configure both start and end options as one Mutual Exclusive SetName=a , both options required =true
Configure the other options as another Mutual Exclusive SetName=b, at least one option is required

Only one Mutual Exclusive group can be used at a time. (either a or b. Mix is not allowed)

Example:
```csharp
class Options
{ 
 //----- group a-----	
     [Option('s',"start", Required=true, SetName="a")]
    public string Start { get; set; }
	   [Option('e', "end",Required=true, SetName="a")]
    public string End { get; set; }
	
	//----- group b-----
    [Option('t', Required=true, SetName="b")]
    public string outputfile { get; set; }	 
	  [Option('i', Required=false, SetName="b")]
    public string inputfile { get; set; }
}
```
Summary of result:

```
------- Args= --start abc
ERROR(S):
  Required option 'e, end' is missing.

 
------- Args= --end abc

ERROR(S):
  Required option 's, start' is missing.

 
------- Args= --start xyz --end abc
Parsed

------- Args= -t abc
Parsed



 ```
 For more information read [Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
 
[Try it online](https://dotnetfiddle.net/hBL0aJ)

**Edit:**
The solution of Mutual exclusive commands may not applicable  especially when there is only one SetName.
The alternative solution is validating the result of the values of start/end options after parsing and firing an error message and stop processing.

**Comment by claym** [comment]
I had 2 sets, so this worked. Thanks!
