### ISSUE TITLE
Specifying a String option with default value doesn't work.

### ISSUE THREAD

**Issue by Xorcist77** [commandlineparser/commandline#534]
I've tried a variety of things, none of which work, but here is what I would expect:

```
[Option('s', "sync", Required = false, Default = "All", HelpText = "Processes the synchronization queue immediately (optionally specifying a repository to sync")]
public String Sync { get; set; }
```

If I run my app with like this myapp -s I would expect it to be assigned a default value of "All", but if I ran it with myapp -s "myrepo" I would expect it to be assigned "myrepo". While the latter works, the former results in:

```
ERROR(S):
  Option 's, sync' has no value.
```

Maybe I am just misunderstanding how it works. What is the proper way to implement an option that can have zero or more strings associated with it. In my case I want -s to sync all my repos, and -s "myrepo" to sync just that individual repo.

**Comment by moh-hassan** [comment]
>If I run my app with like this myapp -s I would expect it to be assigned a default value of "All

The Default is applicable when you don't pass the argument.

                 myapp          //without -s, Default will be applied on Sync  argument.

Any scalar or sequence argument should have a value otherwise you get an error like: 'Option 's, sync' has no value.'.
>What is the proper way to implement an option that can have zero or more strings associated with it.

Remove the Default, and when you don't pass the argument it will be equal to: `default(T)` (null for string).
