### ISSUE TITLE
Wiki: Fix some styling issues

### ISSUE THREAD

**Issue by garyng** [commandlineparser/commandline#535]
Attached is the zip file of the patch:
[fix-docs-styling.zip](https://github.com/commandlineparser/commandline/files/3786803/fix-docs-styling.zip)

Some suggestions going forward:

1. the original authors seems to use indentation of **2 space**, so I used a `vscode` extension [Indent 4-to-2](https://marketplace.visualstudio.com/items?itemName=Compulim.indent4to2) to convert all tabs/4-spaces indentation to 2 spaces.
1. `dotnetfiddle` has a **Tidy Up** button, I used that to reformat most of the code snippets. Some of them are reformatted using Visual Studio
    ![image](https://user-images.githubusercontent.com/4453664/67827105-bf0ba680-fb09-11e9-81b4-9122fccc7076.png)
1. I also used another `vscode` extension [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to try to get as consistent across all docs as possible
1. remove all trailing whitespaces as possible

Some styling suggestions:
1. use backtick (`) as code fences instead of indenting four spaces (https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)
![image](https://user-images.githubusercontent.com/4453664/67827343-ab147480-fb0a-11e9-968c-66601d8f3991.png)
1. use `#` for heading instead of `**`, and avoid appending `#` at the end of the heading
![image](https://user-images.githubusercontent.com/4453664/67827372-ca130680-fb0a-11e9-836c-0b7b8d0e0bce.png)
1. use `1.` for all numbered items, markdown will automatically increment the number
![image](https://user-images.githubusercontent.com/4453664/67827368-bff10800-fb0a-11e9-97ae-b49966a98857.png)

**Comment by moh-hassan** [comment]
Thanks @garyng  for wiki contribution and your suggestions.
I merged your patch successfully.
Your suggestions will be followed for any wiki update.

**Comment by garyng** [comment]
Thanks for merging!
Should I close this issue?

**Comment by moh-hassan** [comment]
yes, you can close :)
