### ISSUE TITLE
Separator does not override Space

### ISSUE THREAD

**Issue by Xorcist77** [commandlineparser/commandline#537]
So the standard separator for IEnumerable options is the space, if another separator is specified, say for example a common (i.e .Separator = ','), space it still treated as a separator, for instance passing:

`app.exe -p key1=value1,key2=value2`

results in two items:

```
[0] key1=value1
[1] key2=value2
```

which is expected, but passing:

`app.exe -p key1 = value1, key2 = value2`

note the spaces... results in five items:

```
[0] key1
[1] =
[2] value1,
[3] key2
[4] =
[5] value2
```

This behavior is a bit undesired, and confusing, everything up until the the next option (i.e. starts with an option prefix - or --) should only be separated by the separator character specified.

**Comment by moh-hassan** [comment]
>note the spaces... results in five items:

These args are the interpreting result  of OS parser(windows/linux/..)
These 6 arguments is not valid arguments for CommandLineParser.

The Grammer rules:
```
--LongName=value    //spaces are not allowed
--LongName value    //spaces are allowed
--LongName="quoted value with spaces"  //value including space should be double quoted.
--LongName "quoted value with spaces" 
```
The valid arguments are:
```
app.exe -p "key1 = value1, key2 = value2"
```
which result in args[]:

[0] -p
[1] key1 = value1, key2 = value2

arg[1] is considered as one unit string (Not IEnumerable)
You can, from within your application, interpret it by splitting with comma separator)

**Comment by Xorcist77** [comment]
So basically what you are saying is that the separator only operates on the first argument after an option, and will split that argument on the specified character, but any arguments after the first (as designated by the original args array, despite being enumerated against the option) will all be delimited by space, so an option defined as such:

```
[Option('p', "parameters", Required = false, Separator = ',')]
public IEnumerable<String> Parameters { get; set; }
```

when called with:

`app.exe -p one,two,three, four,five,six,seven,eight, nine`

currently results in Parameters being enumerated as such:

```
[0] one
[1] two
[2] three
[3]
[4] four,five,six,seven,eight,
[5] nine
```

That just seems wrong to me. I would expect the CommandLineParser logic to be such that it will combine all args after the option up until the next specified delimiter (and or option), which given an original args array of:

```
args[0] = -p
args[1] = one,two,three,
args[2] = four,five,six,seven,eight,
args[3] = nine
```

should "parse" it into the Parameter enumerable as such:

```
[0] one
[1] two
[2] three
[3] four
[4] five
[5] six
[6] seven
[7] eight
[8] nine
```

Doesn't that seem more logical? Is there any reason it shouldn't be implemented in that way?

**Comment by moh-hassan** [comment]
>the separator only operates on the first argument after an option, and will split that argument on the specified character

Yes, That is correct.

>I would expect the CommandLineParser logic to be such that it will combine all args after the option up until the next specified delimiter (and or option), which given an original args array 

Yes, that is correct. Parser combine all args after 'p' until the next specified delimiter.

If the commandline args  are separated by space(s) like:
```
-p one two three four     five six seven     eight  nine   
```

The result is is array :
```
one 
two 
three 
four 
five 
six 
seven 
eight 
nine 
```
So, the solution If there is space spread with comma, quote the string as:

```
-p "one,two,three, four,five,six,seven,eight, nine"
```
otherwise it will consider only the first continuous string after p.

in this case, the result of Parameters option is:

```
one 
two 
three 
 four 
five 
six 
seven 
eight 
 nine 
```
Note the space before four and nine.

**Can Separator override Space?**
Parser receive args[] from OS and every arg is a unit and space(s) are swallowed by OS interpreter except the space between  quoted string.
Parser respect the space if the string is quoted as explained above.

So, simply, 
User provide string to input console and Parser receive args[] from the OS interpreter.
Parser is not aware of spaces (because they aren't exist) to replace it with comma :)

**Comment by Xorcist77** [comment]
I think you missed my point, without a quoted string, given what I have already stated, the current enumeration of:

`app.exe -p one,two,three, four,five,six,seven,eight, nine`

currently results in the Parameter option of:

```
[0] one
[1] two
[2] three
[3]
[4] four,five,six,seven,eight,
[5] nine
```

Which should be considered incorrect if a comma separator is specified. Why... because with no separator specified, the default separator is space, and an enumeration of

`app.exe -p one two three  four five six seven eight  nine`

results in the Parameter option of:

```
[0] one
[1] two
[2] three
[3] four
[4] five
[5] six
[6] seven
[7] eight
[9] nine
```

The two are not equivalent. In this case any and all extra spaces are ignored and each item (no matter how many spaces are in-between) is it's own item. This should 100% hold true for any other separator. So once again, given that the args array of:

`app.exe -p one,two,three, four,five,six,seven,eight, nine`

will be:

```
args[0] = -p
args[1] = one,two,three,
args[2] = four,five,six,seven,eight,
args[3] = nine
```

And the CommandLineParser parses those args, starting with -p, all the following arguments that are not another option (i.e. an argument starting with - or --), should be combined, creating a single variable which can then be split on the specified separator. Which would then result in a proper enumeration of:

`app.exe -p one,two,three, four,five,six,seven,eight, nine`

into

```
[0] one
[1] two
[2] three
[3] four
[4] five
[5] six
[6] seven
[7] eight
[9] nine
```

It seems illogical to provide a separator which does not override the default separator, but instead only works as an additional sub-separator on the first argument of the option, when the default separator works differently.

I'm simply saying that a specified separator should follow the same logic as the default separator.

**Comment by Xorcist77** [comment]
Just to clarify I would expect all these to return the same enumerated list:

Default Separator
```
app.exe -p one two thee four five
app.exe -p one  two  thee  four  five
app.exe -p one   two   thee   four   five
app.exe -p one two  thee   four    five
```

Separator=','
```
app.exe -p one,two,thee,four,five
app.exe -p one, two, thee, four, five
app.exe -p one,  two,  thee,  four,  five
app.exe -p one, two,  thee,   four,    five
```

Should all result in the same enumerated list:
```
[0] one
[1] two
[2] three
[3] four
[4] five
```

But presently they do not, and that is the issue I am trying to resolve here.

**Comment by Xorcist77** [comment]
Well until this is addressed, I'll just pre-process the args before passing them to the CommandLineParser.

For anyone wanting to do something similar, this is the method I am presently using:

Option Specification
```
[Option('p', "parameters", Required = false, Separator = ',')]
public IEnumerable<String> Parameters { get; set; }
```

Pre-Processing call in Main
`args = ConsolidateArgs(args, new[] { "-p", "--parameters" });`

Argument Consolidation Method
```
    private static String[] ConsolidateArgs(String[] args, String[] opts) {
      List<String> newargs = new List<String>();
      Boolean consolidate = false;
      String tmparg = String.Empty;
      for (UInt32 i = 0; i < args.Length; i++) {
        if (consolidate) {
          if (args[i].StartsWith("-", StringComparison.InvariantCultureIgnoreCase) || args[i].StartsWith("--", StringComparison.InvariantCultureIgnoreCase)) {
            consolidate = false;
            newargs.Add(tmparg);
            tmparg = String.Empty;
            i--;
          } else {
            tmparg = $"{tmparg}{args[i]}";
          }
        } else {
          if (opts.Contains(args[i])) {
            consolidate = true;
          }
          newargs.Add(args[i]);
        }
      }
      if (!String.IsNullOrEmpty(tmparg)) {
        newargs.Add(tmparg);
      }
      return newargs.ToArray();
    }
```

**Comment by moh-hassan** [comment]
> until this is addressed, I'll just pre-process the args before passing them to the CommandLineParser.

I think a pre-process action before passing Args to the parser is a good solution for such cases.
I suppose a Utility  class that do such pre-processing action may be add to the parser.
It need to be generalized.

Example

```cs
public class ArgExtensions
{
 public  string[] ConsolidateArgs (this string[] args ,string token)
  {
   // Consolidate all Args  after token and before next dash/doubledash
  }
//... other methods to filter /transform /modify/.. args
}

//usage:
args =args.ConsolidateArgs ("-p");
```

**Comment by captaindjango** [comment]
I know this is old and closed but the example by @Xorcist77 above:

```
    private static String[] ConsolidateArgs(String[] args, String[] opts) {
      List<String> newargs = new List<String>();
      Boolean consolidate = false;
      String tmparg = String.Empty;
      for (UInt32 i = 0; i < args.Length; i++) {
        if (consolidate) {
          if (args[i].StartsWith("-", StringComparison.InvariantCultureIgnoreCase) || args[i].StartsWith("--", StringComparison.InvariantCultureIgnoreCase)) {
            consolidate = false;
            newargs.Add(tmparg);
            tmparg = String.Empty;
            i--;
          } else {
            tmparg = $"{tmparg}{args[i]}";
          }
        } else {
          if (opts.Contains(args[i])) {
            consolidate = true;
          }
          newargs.Add(args[i]);
        }
      }
      if (!String.IsNullOrEmpty(tmparg)) {
        newargs.Add(tmparg);
      }
      return newargs.ToArray();
    }
```

helped me come up with a solution for my own similar issue. My whitespaced arguments weren't treated as a single string. I am leaving this sample here in case someone comes along and finds it useful

```
    public static string[] ConsolidateArgs(string[] args)
    {
        List<string> _processedArgs = new List<string> { args[0] };// Initialised with CLI invoker
        string whiteSpacedArg = string.Empty;
        
        for (uint i = 1; i < args.Length; i++)
        {
            if (args[i].StartsWith("-", StringComparison.InvariantCultureIgnoreCase) ||
                args[i].StartsWith("--", StringComparison.InvariantCultureIgnoreCase))
            {
                if (!string.IsNullOrEmpty(whiteSpacedArg))
                {
                    _processedArgs.Add(whiteSpacedArg);
                }
                _processedArgs.Add(args[i]);
                whiteSpacedArg = string.Empty;
            }
            else
            {
                whiteSpacedArg = !string.IsNullOrEmpty(whiteSpacedArg) ? $"{whiteSpacedArg} {args[i]}" : args[i];
            }
        }

        if (!string.IsNullOrEmpty(whiteSpacedArg))
        {
            _processedArgs.Add(whiteSpacedArg);
        }

        return _processedArgs.ToArray();
    }
```

and I used it like this:

```
ArgsExtensions.ConsolidateArgs(Console.ReadLine()?.Split(" "))
```

or

```
ArgsExtensions.ConsolidateArgs(args)
```
