### ISSUE TITLE
Help Text for positional arguments

### ISSUE THREAD

**Issue by friedrich-brunzema** [commandlineparser/commandline#538]
```[Verb("upload", HelpText = "Upload file or folder to storage.")]
    public class UploadOptions
    {
       // positional argument -- how to add help?
        [Value(0)]
        public string InputPath { get; set; }

        [Value(1)]
        [Option(HelpText="help!")]  // setting this makes it a named option!
        public string OutputPath { get; set; }
   }
   ```
In the above example, it would seem that one cannot have positional arguments that have help text -- or am I stupidly missing something really obvious?

**Comment by moh-hassan** [comment]
you can define help text for positional arguments like named options.
See an example in wiki documentation [How to define Help Text for positional arguments](https://github.com/commandlineparser/commandline/wiki/How-To#q5)

**Comment by friedrich-brunzema** [comment]
Wow, it works!  Thanks so much -- better look in the docs next time.
