### ISSUE TITLE
How to print help on an exception

### ISSUE THREAD

**Issue by iaanlouw** [commandlineparser/commandline#539]
Hi, 
I could not find another place to ask this question.   I have use the command line parser but during my program the input parameter was not valid (for instance I expect a input optionwith exactly 8 characters as input.   
At this point I want to generate an error and print the help screen.  How do I go back to generate a help screen?

        private static void Run(Options opts)
        {
            //Run a report for so many days back
            if (opts.ReportDays != 0)
            {
                Global.log.Info(string.Format("Running report for the past {0} days (ingoring all other functions)", opts.ReportDays.ToString()));
                return; 
            }
            //The user has set a specific process date.   Now try to parse this
            if (opts.ProcessDate != null)
            {
                if (opts.ProcessDate.Length != 8)
                {
                    Global.log.Error("Not a valid process date!");
                    
                    //Print the help Screen here..
                    return;
                }

            }

**Comment by moh-hassan** [comment]
You can generate custom help using HelpText class
```cs
var helptext=HelpText.AutoBuild(parserResult, h =>h,e=>e);
```
Find a complete solution in wiki:
[How to Print Help Screen when the Parser Success from within WithParsed Method?](https://github.com/commandlineparser/commandline/wiki/How-To#q6)


[Try it online](https://dotnetfiddle.net/ovpkf1)

**Comment by moh-hassan** [comment]
@iaanlouw 
Can you feedback if your issue is resolved?
Thanks

**Comment by iaanlouw** [comment]
Yes thanks - working fine.
