### ISSUE TITLE
Ability to have switches with optional values 

### ISSUE THREAD

**Issue by AdamHess** [commandlineparser/commandline#542]
desired ability to have a nullable value that when the switch is provided it will go to the `default(obj)` value, but if the user provides an option it will parse it. 

Reasoning: 
want the ability to have default values when the user turns on the switch, but give them the option to set the value. 

```
[Option('p', "parallel")]
public int? Parallelism { get;  set;}

MyProgram.exe  -p


if (Options.Parallelism != null && Option.Parallelism == default(int)) {
     var parallelism = Environment.ProcessorCount;
}


alternatively:

MyProgram.exe -p 8

```

**Comment by moh-hassan** [comment]
Integer values are scalar tokens not  switches (true/false).

If  argument is passed, it has a value, like:

        MyProgram.exe -p 8
    
If the argument is not passed, it has the default value 0.

         MyProgram.exe   //option p isn't passed, so it has the default value.

`MyProgram.exe  -p` is not allowed and Parser raise an error.

Note: for Nullable int the default value = null
