### ISSUE TITLE
Could two or more options be marked as 'at least one is required'?

### ISSUE THREAD

**Issue by hadzhiyski** [commandlineparser/commandline#546]
Hello,

This is not particularly an issue. I was wondering could I make two or more options to act like at least one of them is required, but if none is provided I will get a required error?

``` c#
[Verb("rename")]
public sealed class RenameOptions
{
    [Option("prefix", HelpText = "Prefix to append to file name", SetName = "rename", Required = true)]
    public string Prefix { get; set; }

    [Option("suffix", HelpText = "Suffix to append to file name", SetName = "rename", Required = true)]
    public string Suffix { get; set; }
}
```
This works if both options are included. Could I make them to work separately or together, but always one should be provided?

**Comment by moh-hassan** [comment]
You can use  Mutually  Exclusive Options.
Set every option in a separate `SetName`  and only one option at a time is allowed.

```cs
[Verb("rename")]
public sealed class RenameOptions
{
    [Option("prefix", HelpText = "Prefix to append to file name", SetName = "prefix", Required = true)]
    public string Prefix { get; set; }

    [Option("suffix", HelpText = "Suffix to append to file name", SetName = "suffix", Required = true)]
    public string Suffix { get; set; }
}
```

This is working:
```
myapp  rename   --prefix aaa   //Ok, --suffix not allowed here
myapp  rename   --suffix bbb   //Ok, --prefix not allowed here
```

This is not  working
```
myapp  rename    //Error:  MissingRequiredOptionError , at least one prefix/or suffix is needed
myapp  rename   --suffix bbb  --prefix aaa  //both options are not allowed, they are mutually Exclusive
```
For more details about  Mutually Exclusive Options see [wiki](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)

**Comment by hadzhiyski** [comment]
Hello,

I actually am trying to do the following

```
myapp rename --prefix aaa // OK
myapp rename --suffix bbb // OK
myapp rename --prefix aaa --suffix bbb // OK
my app rename // Required error - Either prefix or suffix must be available
```

I hope this makes sense.

**Comment by moh-hassan** [comment]
> myapp rename --prefix aaa --suffix bbb // OK

it should not  work.
Do you renamed the `SetName` as I showed [above](https://github.com/commandlineparser/commandline/issues/546#issuecomment-561160805)

**Comment by hadzhiyski** [comment]
I removed the SetName completely. I am trying to make it work like the example from my previous comment

**Comment by hadzhiyski** [comment]
I created a PR #552 which solves this issue. It is still "work in progress" so I am open to any suggestions about it.

**Comment by hadzhiyski** [comment]
@moh-hassan please close this issue

**Comment by moh-hassan** [comment]
Thanks, closed
