### ISSUE TITLE
Api wiki documentation missing icons.

### ISSUE THREAD

**Issue by henrik-jensen** [commandlineparser/commandline#547]
[Api documentation](https://github.com/commandlineparser/commandline/wiki/API-V2.6.0) icons (pubclass.gif, pubmethod.gif ...) are not in wiki/media, but cloning the wiki there is a folder 'wiki/Help-260/media/' with the missing icons.

This is how it displays in Chrome on my system:

[![CommandLine Namespace documentation showing the missing icons](https://user-images.githubusercontent.com/9413242/70188163-4d1e1280-16f0-11ea-9771-af918d569a30.png)](https://github.com/commandlineparser/commandline/wiki/API-V2.6.0)

**Comment by moh-hassan** [comment]
Thanks for reporting wiki/media issue.
The icons are  copied to media folder.
I can see  [Api documentation](https://github.com/commandlineparser/commandline/wiki/API-V2.6.0) correctly with icons using internet explorer.

**Comment by henrik-jensen** [comment]
Icons seams to show now, except `media/pubclass.gif` and `media/pubmethod.gif` but I think this is some caching problem between my system and github.com, because opening [medie/pubclass.gif](https://raw.githubusercontent.com/wiki/commandlineparser/commandline/media/pubclass.gif) directly **do** open the icon in normal size.
In Firefox and Edge these two icons also behaves weirdly, showing as very small icons hardly visible on the page (unlike Chrome where there's only empty space), but normal size directly.

Firefox example of [T_CommandLine_Error](https://github.com/commandlineparser/commandline/wiki/T_CommandLine_Error):

![547_02](https://user-images.githubusercontent.com/9413242/70232921-c30c9300-175d-11ea-8444-854f1a6bada4.png)

Here `privextension.gif` ![privextension.gif](https://raw.githubusercontent.com/wiki/commandlineparser/commandline/media/privextension.gif),  shows fine ( `IsEmpty`, `NormalizeValue`), but `pubmethod.gif` ![pubmethod.gif](https://raw.githubusercontent.com/wiki/commandlineparser/commandline/media/pubmethod.gif),  are very small ( `GetType`, `MemberwiseClone`, `ToString`).

But unless others have the same problem I guess it might be some local problem on my side.
