### ISSUE TITLE
Invalid Resource Type Error

### ISSUE THREAD

**Issue by K6TJO** [commandlineparser/commandline#553]
The resource file I created for localization strings is not found.  I can see the error in the LocalizableAtrtributerProperty.GetLocalizationValue method but I am not sure what the problem is. 

In my example the Option is configured like so:
[[Option(longName:"filename", shortName:'f', HelpText = "HelpText", ResourceType = typeof(ROLStrings))]
        public string FileName { get; set; }
](url)

The Parser statement in my Main method is: 

[int returnInt = CommandLine.Parser.Default.ParseArguments<LogOptions>(args)
              .MapResult(
                (LogOptions opts) => RunLogOptionsAndReturnExitCode(opts),
                errs => 1);
](url)

The errors shows:

> $exception | {"Invalid resource type (Parameter 'HelpText')"} | System.ArgumentException
> StackTrace | "   at CommandLine.Infrastructure.LocalizableAttributeProperty.GetLocalizedValue() in \\src\\CommandLine\\Infrastructure\\LocalizableAttributeProperty.cs:line 49\r\n   at CommandLine.Infrastructure.LocalizableAttributeProperty.get_Value() in \\src\\CommandLine\\Infrastructure\\LocalizableAttributeProperty.cs:line 23\r\n   at CommandLine.BaseAttribute.get_HelpText() in \\src\\CommandLine\\BaseAttribute.cs:line 95\r\n   at CommandLine.Core.OptionSpecification.FromAttribute(OptionAttribute attribute, Type conversionType, IEnumerable`1 enumValues) in \\src\\CommandLine\\Core\\OptionSpecification.cs:line 30\r\n   at CommandLine.Core.Specification.FromProperty(PropertyInfo property) in \\src\\CommandLine\\Core\\Specification.cs:line 118\r\n   at CommandLine.Core.InstanceBuilder.<>c__0`1.<Build>b__0_1(PropertyInfo pi) in \\src\\CommandLine\\Core\\InstanceBuilder.cs:line 29\r\n   at CommandLine.Core.ReflectionExtensions.<>c__DisplayClass0_0`1.<GetSpecifications>b__5(IGrouping`2 g) in \\src\\CommandLine\\Core\\ReflectionExtensions.cs:line 25\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at CSharpx.EnumerableExtensions.Memorize[T](IEnumerable`1 source) in src\\CommandLine\\Infrastructure\\EnumerableExtensions.cs:line 377\r\n   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsingCulture, Boolean autoHelp, Boolean autoVersion, IEnumerable`1 nonFatalErrors) in \\src\\CommandLine\\Core\\InstanceBuilder.cs:line 29\r\n   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args) in \\src\\CommandLine\\Parser.cs:line 94\r\n   at Program.Main(String[] args) in \\Program.cs:line 41" | string
> 
> 
> 
> 
> 
>

**Comment by K6TJO** [comment]
#solved,  Resource file needs to be marked "Public"

**Comment by moh-hassan** [comment]
Yes, Resource file needs to be marked "Public".
You can close the issue.
