### ISSUE TITLE
Immutable option class with verb calls ctor with default parameters

### ISSUE THREAD

**Issue by olivermue** [commandlineparser/commandline#564]
Within my project I have an immutable option class that validates its parameters within the constructor and this worked fine so far by using this call:
```
public static void Main(string[] args)
{
    Parser.Default.ParseArguments<FirstOptions>(args)
        .WithParsed(ConvertFile);
}
```

In the next phase we added another functionality to the tool and separated them by using another option class and use Verbs to distinguish between them. The new call is this:
```
public static void Main(string[] args)
{
    Parser.Default.ParseArguments<FirstOptions, SecondOptions>(args)
        .MapResult(
            (FirstOptions options) => ConvertFile(options),
            (SecondOptions options) => Convert2File(options),
            errors => 1);
}
```

Unfortunately the behavior between both calls is different, cause the new version creates an instance of the immutable class with all parameters set to default, while the first doesn't. This can be quite annoying if you do some parameter checks within the constructor of your options class, cause they will fail. Here is an example:
```
public class IssueImmutableClassTest
{
    [Fact]
    public void ImmutableClass_will_not_default_created()
    {
        var result = Parser.Default.ParseArguments<ImmutableOptions, Other>(new[] { "immutable", "--id", "1", "--name", "Foo" })
            .MapResult((ImmutableOptions options) => 1, (Other options) => 2, errors => 3);

        result.Should().Be(1);
    }
}

[Verb("other")]
internal class Other
{
    [Option("name", Required = true)]
    public string Name { get; set; }
}

[Verb("immutable")]
internal class ImmutableOptions
{
    [Option("id", Required = true)]
    public int Id { get; }
    [Option("name", Required = true)]
    public string Name { get; }

    public ImmutableOptions(int id, string name)
    {
        Id = id;
        Name = name;

        if (id == default || name == default)
            throw new InvalidOperationException();
    }
}
```

**Comment by moh-hassan** [comment]
>the behavior between both calls is different,

You are correct.

In non-verb case, Parser is aware of the type and create the Immutable object using the  constructor with actual  parameter values.
In the verb case, Parser take an extra step and use Reflection to get the type of the verb, and in this case create Instance using the constructor with the default parameter values (based on their type). 

So, Constructor is not the right way to validate the object. There are different guidelines for the validation using the constructor, one discourage firing exceptions in Ctor and only initialize object to get stable state ( [NEVER allow an object to exist in an inconsistent state](https://softwareengineering.stackexchange.com/a/51072/241186)). Validation using Ctor may be applicable if you are the only creator and initializer of the object.

I suggest you move the validation part in a separate method /class that can manage the validation and throw exceptions as needed.

Have a look for this validation [discussion](https://github.com/commandlineparser/commandline/issues/146#issuecomment-523514501)
