### ISSUE TITLE
WithParsed documention incorrectly describes async option

### ISSUE THREAD

**Issue by andrew-hampton** [commandlineparser/commandline#567]
The Getting Started documentation includes an example for using WithParsed with async/await. This scenario does not properly work and should be removed from the documentation to avoid causing confusion.

https://github.com/commandlineparser/commandline/wiki/Getting-Started#using-withparsed-in-asyncawait

**Comment by rrector** [comment]
Issue #332 does a good job describing the problem.

**Comment by moh-hassan** [comment]
Thanks @andrew-hampton , @rrector  for correction.
I removed the example of WithParsed.

**Comment by andrew-hampton** [comment]
Thanks for the quick turnaround. Closing the issue

**Comment by moh-hassan** [comment]
@andrew-hampton , @rrector
V 2.8.0 include a new feature `WithParsedAsync / WithNotParsedAsync` to support `async/await`
