### ISSUE TITLE
Display Help With No Parse Issue

### ISSUE THREAD

**Issue by Axemasta** [commandlineparser/commandline#569]
Hello

I have a mutually exclusive set (set) of commands. If these commands aren't present I wish to show the help window.

my options class:
```csharp
[Option('a', "all", HelpText = "Run all integration tests", SetName = "ab")]
public bool All { get; set; }

[Option('t', "tests", HelpText = "The tests you wish to perform", SetName = "ab")]
public IEnumerable<string> Tests { get; set; }
```

If neither parameter is present, I would want to display the usage information in the help screen to the user. 

Is this possible? I could try writing it manually, but the help screen it too pretty!!

Consider the following example

```csharp
static void Main(string[] args)
{
    var wrapper = new AsyncWrapper();


    var parser = new CommandLine.Parser();

    var parserResult = parser.ParseArguments<CmdlineOptions>(args);

    parserResult
        .WithParsed<CmdlineOptions>(options => Run(options))
        .WithNotParsed(errs => DisplayHelp(parserResult, errs));

    Console.WriteLine($"Press <ENTER> to exit...");
    Console.ReadLine();
}

private static void Run(CmdlineOptions options)
{
    //do stuff
}

static void DisplayHelp<T>(ParserResult<T> result, IEnumerable<Error> errs)
{
    var helpText = HelpText.AutoBuild(result, h =>
    {
        h.AdditionalNewLineAfterOption = false;
        h.Heading = "Myapp 2.0.0-beta"; //change header
        h.Copyright = "Copyright (c) 2019 Global.com"; //change copyright text
        return HelpText.DefaultParsingErrorsHandler(result, h);
    }, e => e);
    Console.WriteLine(helpText);
}
```

In this example with no cmdline arguments, only the WithParsed method will fire, I cannot display the help page.

**Comment by Axemasta** [comment]
I've come up with the ultimate bodge, but i'd expect a way to call it within the parser...

```csharp
if (args.Count() == 0)
{
    Main(new string[] { "--help" });
}
```

**Comment by moh-hassan** [comment]
There is a new AutoBuild in v2.7.82 that simplify the help.
Also, you need not to pass Errs.
I find that  you use only one SetName. 
You should have at least two different setname to use mutual exclusive option effectively.
See [wiki- Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
There is no Required option, therefore you expect no errors.

```cs
//this is working in v2.7.82
static void DisplayHelp<T>(ParserResult<T> result)
{
    var helpText = HelpText.AutoBuild(result, h =>
    {
        h.AdditionalNewLineAfterOption = false;
        h.Heading = "Myapp 2.0.0-beta"; //change header
        h.Copyright = "Copyright (c) 2019 Global.com"; //change copyright text
        return h; 
    });
    Console.WriteLine(helpText);
}
```

The next is working

```cs
//two different setnames, so at least one should be passed(if required=true).
//in this case, help is fired when args are empty.

I'm not sure if this what you want.

class CmdlineOptions
{
[Option('a', "all", HelpText = "Run all integration tests", SetName = "ab",Required=true)]
public bool All { get; set; }

[Option('t', "tests", HelpText = "The tests you wish to perform", SetName = "ab2",Required=true)]
public IEnumerable<string> Tests { get; set; }
}
```

**Comment by Saqo1995s** [comment]
> There is a new AutoBuild in v2.7.82 that simplify the help.
> Also, you need not to pass Errs.
> I find that you use only one SetName.
> You should have at least two different setname to use mutual exclusive option effectively.
> See [wiki- Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
> There is no Required option, therefore you expect no errors.
> 
> ```cs
> //this is working in v2.7.82
> static void DisplayHelp<T>(ParserResult<T> result)
> {
>     var helpText = HelpText.AutoBuild(result, h =>
>     {
>         h.AdditionalNewLineAfterOption = false;
>         h.Heading = "Myapp 2.0.0-beta"; //change header
>         h.Copyright = "Copyright (c) 2019 Global.com"; //change copyright text
>         return h; 
>     });
>     Console.WriteLine(helpText);
> }
> ```
> 
> The next is working
> 
> ```cs
> //two different setnames, so at least one should be passed(if required=true).
> //in this case, help is fired when args are empty.
> 
> I'm not sure if this what you want.
> 
> class CmdlineOptions
> {
> [Option('a', "all", HelpText = "Run all integration tests", SetName = "ab",Required=true)]
> public bool All { get; set; }
> 
> [Option('t', "tests", HelpText = "The tests you wish to perform", SetName = "ab2",Required=true)]
> public IEnumerable<string> Tests { get; set; }
> }
> ```

he wants to show help message from parser like Parser.DisplayHelp(...).
