### ISSUE TITLE
Example of Mutually exclusive options

### ISSUE THREAD

**Issue by i308** [commandlineparser/commandline#570]
Is there a latest demo code the handles mutually exclusive options?

**Comment by moh-hassan** [comment]
You can find a demo example in wiki [Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)
You may be  interested to try a new [Group feature](https://github.com/commandlineparser/commandline/wiki/Option-Groups)
