### ISSUE TITLE
How can the HelpText localized?

### ISSUE THREAD

**Issue by LokiMidgard** [commandlineparser/commandline#571]
Since the HelpText is set in Attributes and parameter of Attributes need to be const, how can I localize this text?

**Comment by moh-hassan** [comment]
HelpText is localized starting v2.6+
Read wiki [Help Localization](https://github.com/commandlineparser/commandline/wiki/Help-Localization) and try the demo.

**Comment by LokiMidgard** [comment]
Thank you.
