### ISSUE TITLE
IgnoreUnknownArguments not working

### ISSUE THREAD

**Issue by n-raga** [commandlineparser/commandline#573]
Hello,

I have problem with IgnoreUnknownArguments = true with v.2.7.82.

If i have the unknown parameter as last parameter it seems that the parse failed with ParserResultType.NotParsed.
It works correctly if I have the unkown parameter at start or between correct parameters.

`
    public class CommandLineOptions
    {
        [Option("env", Required = true, HelpText = "Specify the environment")]
        public string Environment { get; set; }

        [Option("address", Required = false, Default = new string[] { "localhost","1883" }, Separator =':', Min =2, Max =2, HelpText = "Host address and port")]
        public IEnumerable<string> Address { get; set; }

        [Option("console", Required = false, Default = false, HelpText = "Show console with logs")]
        public bool ShowConsole { get; set; }

        [Option("loglevel",  Required = false, Default = "INFO", HelpText = "Livello del log")]
        // Livelli accettati:
        //   FATAL    // più alto, logga solo FATAL
        //   ERROR
        //   WARN
        //   INFO     // valore di default
        //   DEBUG    // più basso, logga tutto
        //   OFF      // log disabilitato
        public string LogLevel { get; set; }
    }

static void Main(string[] args)
{
	var parser = new Parser(with =>
	{
		with.IgnoreUnknownArguments = true;
	});

	var result = parser.ParseArguments<CommandLineOptions>(args);

	if (result.Tag == ParserResultType.NotParsed)
	{
		var errors = ((NotParsed<CommandLineOptions>)result).Errors;
		throw new Exception("Unable to parse command line.");
	}

	var parsedValue = ((Parsed<CommandLineOptions>)result).Value;
}
`

commandline: --env=car --address=localhost:1883 -log

Error: {CommandLine.SequenceOutOfRangeError}

**Comment by moh-hassan** [comment]
This is working by using --log (double dash) instead of -log (single dash).
```
-l zz --env=car --address=localhost --log   
```
**Why failed?**
-log is parsed as:
**-l**        //one char because you use single dash
**og**   is interpreted as Value token and will be added to the sequence
you limit the sequence to 2 , and now sequence is 3 items: localhost, 1883, og
So, Parser raise an error: CommandLine.SequenceOutOfRangeError
If you omit max=2, no error is fired.

So, Parser option `IgnoreUnknownArguments`' is working as expected and ignore unknown options.

**Comment by n-raga** [comment]
I got it. Thank you.
I thought it will remove the unknown argument and the whole character until the next - or --.
So I thought it would remove -l and og because it's considered part of the unknown argument.

It happens in case of a typo, I wanted to prevent this type of mistake.
Is there a way to get what I want?
