### ISSUE TITLE
What is the correct way to parse an argument with value -

### ISSUE THREAD

**Issue by tevoinea** [commandlineparser/commandline#574]
I have a program that I would like to execute like so:

`./myprogram --someArg 2 --thisFails - --anotherArg 3`

Where the value of `thisFails` should be set to `-`

I've also tried: `"-"` to no avail

The error I'm getting is:

```
ERROR(S):
  Option 'thisFails' has no value.
```

**Comment by moh-hassan** [comment]
Use **triple quote** to quote "-" in the commandline, , then it will passed to the parser with Single Quote:

 --somearg 2 --thisfails """-""" --anotherarg 3

**Comment by tevoinea** [comment]
In my testing, the triple quote returned a value of `"-"` not `-` but that's ok, we can work around that.

Thanks!

**Comment by moh-hassan** [comment]
To avoid tripple quote, merging options with single dash as a value is allowed:
```
./myprogram --someArg 2 --thisSuccess=- --anotherArg 3  #merge longname with dash using '=' e.g `--thisSuccess=-`
./myprogram --someArg 2   -s- --anotherArg 3  #merge shortname with dash: `-s-`
```

**Comment by moh-hassan** [comment]
Single dash will be considered as a value in the next release
