### ISSUE TITLE
Change parameters requirements for some cases.

### ISSUE THREAD

**Issue by sargis-tovmasyan** [commandlineparser/commandline#576]
Hey. Have an application with CLI and GUI modes, switching modes via command-line argument.
I mean "-c" existing indicating that application gonna be run in CLI mode, but in that case, I need some other option to be required. How can I do that?

**Comment by moh-hassan** [comment]
I suppose you run CLI with a set of parameters and GUI with other set and you may have common options for both CLI and GUI.
Based on this assumption, you can use [Mutually Exclusive Options](https://github.com/commandlineparser/commandline/wiki/Mutually-Exclusive-Options)

```cs
 public class Options
    {


//set gui
	   [Option('g', Required = true,SetName="gui")]  
       public bool Gui { get; set; }

//----- set cli	   
        [Option('c', Required = true,SetName="cli")]  
       public bool Cli { get; set; }
	    [Option('p', "parameter", Required = true,SetName="cli")]  
       public string Parameter { get; set; }
//-- common arguments wihou setName
    }
```

you command can be:
```
myapp -g --other-options //gui mode
# or
myapp -c -p xyz    # CLI mode
```
You may add more details for the usage of the other arguments if this assumption don't match your case.

**Comment by sargis-tovmasyan** [comment]
> I suppose you run CLI with a set of parameters and GUI with other set and you may have common options for both CLI and GUI.

Yes, you right, I found a temporary solution I try this method later.
Thanks!
