### ISSUE TITLE
Multiple sets for one option

### ISSUE THREAD

**Issue by VirtualEvan** [commandlineparser/commandline#577]
I am controlling a service and I would like to have an option that can be used together with one of some mutually exclusive options, but not with the rest, an example of what I expect below:

```CSharp
[Option("install", SetName = "install")]
public Boolean Install { get; set; }

[Option("start", SetName = "start")]
public Boolean Start { get; set; }

[Option("stop", SetName = "stop")]
public Boolean Stop { get; set; }

// Note that there is more than one set specified in this one
[Option("config", SetName = "install, start")]
public string Config { get; set; }
```

So with this configuration I should be able to execute:
```cmd
app --install --config sampleConfig
app --start --config sampleConfig
```
but not
```cmd
app --stop --config sampleConfig
app --install --start --config sampleConfig
```
Is there some way I could achieve this?
I have been looking into the issues and found some similar ones, but could not find any answer regarding this functionality.

**Comment by moh-hassan** [comment]
Multiple sets for one option aren't supported.
As you are passing the  arguments for a service (silent mode), In the method of processing the argument you can ignore the config argument even if it's passed on the commandLine.
You,also. can use the [Group ](https://github.com/commandlineparser/commandline/wiki/Option-Groups)(v2.7.82) if you run only one option at a time
```cs
[Option("install", group = "g1")]
public Boolean Install { get; set; }

[Option("start", group = "g1")]
public Boolean Start { get; set; }

[Option("stop", group = "g1")]
public Boolean Stop { get; set; }

[Option("config")] //shared with group
public string Config { get; set; }
```

This is valid
```
app --install --config sampleConfig
app --start --config sampleConfig
app --install --start --config sampleConfig   # using two options of the same group are allowed
app --stop   --config sampleConfig  # processing method can ignore config
app --stop                         # processing method can ignore config
```

**Comment by VirtualEvan** [comment]
Thanks for your help, it worked fine.
I saw in the  documentation you linked that Groups are not compatible with SetNames, but it worked for me blocking options like 
```cmd
app --stop --start
```
I will keep testing to see if I find some other problem with this configuration.

By the way, is there any way to suppress the `(Group: <GroupName>)` from the help text? I do not think it is useful for the user if they do not know what a Group of options represents, in my opinion the error text specifying the "required" options is enough.
> At least one option from group 'Service control' (install, uninstall, start, stop, restart, status) is required.

**Comment by moh-hassan** [comment]
> Groups are not compatible with SetNames

Groups /   SetNames can't be used on the same time. Both apply different rules.

>is there any way to suppress the (Group: <GroupName>) from the help text? I do not think it is useful for the user if they do not know what a Group of options represents, in my opinion the error text specifying the "required" options is enough.

I'll investigate your suggestion and the side effect.

/cc @hadzhiyski

**Comment by moh-hassan** [comment]
@VirtualEvan 
Groups is like Required (at least one option is required per group), so it's needed to be visible in help.

**Comment by VirtualEvan** [comment]
I understand, but just putting visible `(Group: <group name>)` might make sense to the developer of the app, but not to an end user who is not familiar with this library and does not know that at least one of those options is required.

**Comment by moh-hassan** [comment]
I think that the End user also should be aware of the group to pass the correct options. May be a pre-options text can be added to the help to use the application effectively. e.g "at least one option of the group g1 is required".

**Comment by feltrite** [comment]
Recently Ive come to face this issue aswell, sadly this solution is not sufficient. 

> Multiple sets for one option aren't supported.
> As you are passing the arguments for a service (silent mode), In the method of processing the argument you can ignore the config argument even if it's passed on the commandLine.
> You,also. can use the [Group ](https://github.com/commandlineparser/commandline/wiki/Option-Groups)(v2.7.82) if you run only one option at a time
> 
> ```cs
> [Option("install", group = "g1")]
> public Boolean Install { get; set; }
> 
> [Option("start", group = "g1")]
> public Boolean Start { get; set; }
> 
> [Option("stop", group = "g1")]
> public Boolean Stop { get; set; }
> 
> [Option("config")] //shared with group
> public string Config { get; set; }
> ```
> 
> This is valid
> 
> ```
> app --install --config sampleConfig
> app --start --config sampleConfig
> app --install --start --config sampleConfig   # using two options of the same group are allowed
> app --stop   --config sampleConfig  # processing method can ignore config
> app --stop                         # processing method can ignore config
> ```

In some situations (like my own) you could run "app --config sampleConfig"
But when running --start, you want to make --config a mandatory requirement.

making --config a member of a few sets.

**Comment by moh-hassan** [comment]
Multi sets cause complexity in the validation logic and help and cause a great confusion for the user to know which set of options are valid.
see this simple table for options
```
            common    set1    set2    set3
option1                 x        x
option2
option3                  x                  x


option n                          x          x
```
how the user mange N Options x M sets
