### ISSUE TITLE
Reporting standalone arguments?

### ISSUE THREAD

**Issue by astrowalker** [commandlineparser/commandline#578]
Question

Let's say I defined one option "--foo". When I have such execution line:

    program.exe first second --foo value

"first" and "second" are not reported as parsed or not-parsed. They are transparent in some sense for the parser.

  Is there some third "feed" such arguments are reported by parser? I am asking because handling this manually is not so trivial. If those 2 first parameters are fixed I could cut them out manually, but then if I make a mistake and call:

    program.exe first --foo value

I would cut out "--foo" with "first", leaving "value" undetected (my manual handler would ignore it, because I assumed 2 fixed arguments) and parser would ignore it because it is not a defined option.

Am I missing something or parser is simply not prepared for handling (reporting) standalone arguments?

**Comment by moh-hassan** [comment]
The arguments `first , second` are parsed as **Value tokens** and are ignored by default if they haven't a corresponding `ValueAttributes` . For more details, see [[Value] Attribute](https://github.com/commandlineparser/commandline/wiki/Getting-Started#value-attribute).
