### ISSUE TITLE
Dynamically loading verbs (plugins)

### ISSUE THREAD

**Issue by Tobias-08** [commandlineparser/commandline#581]
Hi,
I am trying to implement a CLI that is able to load new verbs ("plugins") from separate dlls dynamically. 

I have an IVerb interface:

`public interface IVerb
{
int Run();
}`

and several Verb-classes that implement this interface.

In the CLI I thought of having something like:

`Parser.Default.ParseArguments(args, typeof(...), ...).WithParsed<IVerb(verb => verb.Run())`

But this does not seem to work.

What am I missing?

Thanks

**Comment by Tobias-08** [comment]
This seems to work now:

`Parser.Default.ParseArguments(args, verbTypes.ToArray())
.MapResult(
(IVerb verb) => verb.Run()`

**Comment by moh-hassan** [comment]
You can also use `WithParsed `  with the Plugin Verbs:

```cs
   CommandLine.Parser.Default.ParseArguments(args, verbTypes.ToArray())
	   .WithParsed ((IVerb verb) => verb.Run());
```
The overload method  [ParseArguments](https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/Parser.cs#L151) has Type as an array `Type[]`:
```cs
public ParserResult<object> ParseArguments(IEnumerable<string> args, params Type[] types)
```

**Comment by moh-hassan** [comment]
@Tobias-Gr 
Do you tried using `WithParsed `  and is working like `MapResult`?

**Comment by Tobias-08** [comment]
Yes, thanks for the support.

**Comment by Tobias-08** [comment]
Regarding the plugins we now have plugins with individual dependencies. In order to load these correctly we need an [AssemblyLoadContext](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#load-plugins) (at least in my understanding). Currently I am not able to make the dynamic loading of the verbs (see above) work with the AssemblyLoadContext.

Does anyone have an advice?

Thanks!

**Comment by Tobias-08** [comment]
It seems that I found a solution:

It seems to work with the help of [McMaster.NETCore.Plugins](https://github.com/natemcmaster/DotNetCorePlugins). In the PluginLoader it is important to configure the correct shared types:

`sharedTypes: new[] { typeof(IVerb), typeof(VerbAttribute) }`
