### ISSUE TITLE
Enum with flags that can be combined

### ISSUE THREAD

**Issue by dfhwze** [commandlineparser/commandline#582]
Is it possible to have flagged enum options?

For instance, I would like to be able to combine which categories I would like to log in my tool.

command-line:
> mytool -l Admin -l Status

enum used in options:
> [Flags]
    public enum Logging: uint
    {
        None = 0,
        Admin = 1 << 0,
        Status = 1 << 1,
        Progress = 1 << 2,
        All = 0xFFFFFFFF,
    }

**Comment by moh-hassan** [comment]
You can use `IEnumerable<Logging>` for multiple options and use separator '|' like c#:
```cs
 public class Options
    {
       [Option('l',  Separator='|')]  
       public IEnumerable<Logging> Log { get; set; }
    }
```

commandline can be:
```
mytool -l Admin|Status|Progress 
```

Then Evaluate the multi log values.

**Comment by moh-hassan** [comment]
@dfhwze 
Can you feedback if you resolved your issue.
