### ISSUE TITLE
Are there any code breaking changes between 2.6.0 and 2.7.82?

### ISSUE THREAD

**Issue by ajtruckle** [commandlineparser/commandline#583]
Also, is there a change log of the changes made in each version that you release?

Thank you.

**Comment by moh-hassan** [comment]
Welcome @ajtruckle 
>Is there a change log of the changes made in each version that you release

There is [CHANGELOG.md](https://github.com/commandlineparser/commandline/blob/master/CHANGELOG.md) that track changes in every release: added features/changes/bug-fix/Breaking changes. All notable changes to this project will be documented in this file.

There is no Binary breaking changes between 2.6.0 and 2.7.82.

**Comment by ajtruckle** [comment]
Thanks for the conformation!

________________________________
