### ISSUE TITLE
Multiple commands on resource

### ISSUE THREAD

**Issue by psclkhoury** [commandlineparser/commandline#587]
I'm trying out commandLineParser but i'm having some difficulties getting working as I want.

I want to be able to achieve something like:
```
app resource --download
app resource --delete
app resource --list

(download, delete, list would be even better than --download, --delete, --list)
```

and for each action (download, delete, list) I want to have separate options, and maybe share a few common options.

I can make it work by having a verb (resource) and then adding a bunch of options to it for all the actions, but i am not able to clearly separate the options for each action.

This is an example of what I need.
```
app resource --download --meta           // should not work, it needs a label. meta is optional
app resource --delete --label some-label // should work
app resource --download --foo foo        // should not work, foo is only for --list
app resource --list                      // okay
app resource --list  --meta              // should not work. Meta only for download/delete
app resource --list --foo foo --bar bar  // okay
```

```c#
[Verb("cache", HelpText = "List, download, and delete caches.")]
public class CacheCommandOptions
{
  [Option('d', "download", HelpText = "download")]
  public bool Download { get; set; }

  [Option('d', "delete", HelpText = "delete")]
  public bool Delete { get; set; }

  [Option('l', "list", HelpText = "list")]
  public bool List { get; set; }

  // only for list (optional)
  [Option('f', "foo")]
  public string Foo{ get; set; }

  // only for list (optional)
  [Option('b', "bar")]
  public string Bar{ get; set; }

  // only for download and delete (required)
  [Option('l', "label", HelpText = "label to download.")]
  public string Label { get; set; }

  // only for download and delete (optional)
  [Option('m', "meta", Default = false, HelpText = "Get metadata?")]
  public bool Meta { get; set; }
}
```

**Comment by moh-hassan** [comment]
You can use an enum as a subCommand.
Then, do a validation based on the values of Foo,Bar, Label and Meta and take required action:

```cs
public enum SubCommand
{
  download, 
  delete, 
  list
}

[Verb("cache", HelpText = "List, download, and delete caches.")]
public class CacheCommandOptions
{

  [Value(0, Required=true, HelpText="Run sub command")]
  public SubCommand SubCommand { get; set; }

  // only for list (optional)
  [Option('f', "foo")]
  public string Foo{ get; set; }

  // only for list (optional)
  [Option('b', "bar")]
  public string Bar{ get; set; }

  // only for download and delete (required)
  [Option('l', "label", HelpText = "label to download.")]
  public string Label { get; set; }

  // only for download and delete (optional)
  [Option('m', "meta", Default = false, HelpText = "Get metadata?")]
  public bool Meta { get; set; }
  			
 public bool Validate()
  {
    //do validation based on the values of Foo,Bar, Label and Meta and take required action
    
  }
}
```

the use example:

```
app cache delete --label some-label
app cache list
```

**Comment by psclkhoury** [comment]
@moh-hassan using your example I get errors.

```
app cache list or app cache --help -> 
  ERROR(S):
    A value not bound to option name is defined with a bad format.
    A required value not bound to option name is missing.
```

For the `Validate` function, how would I return the help text if something is missing? Or is it something that the library calls?

For the helptext (maybe I should open another issue for that?) when I override the `HelpText` as shown in the wiki to remove the new lines after option, it works when there is an error but doesn't work when I explicitly call `--help`. Maybe a parameter should be added to the `Autobuild` function to pass in the `HelpText` properties.

```
//new lines 
app --help
  -f, --foo

  -l, --label    label to download.

  --help         Display this help screen.

  --version      Display version information.



app --foo

// no new lines
ERROR(S):
  Option 'f, foo' has no value.

  -f, --foo
  -l, --label    label to download.
  --help         Display this help screen.
  --version      Display version information.
```

**Comment by moh-hassan** [comment]
If you are using one verb, add object as a dummy verb. At least two verbs are needed. see the remark in [verbs](https://github.com/commandlineparser/commandline/wiki/Verbs).
In this case the command is working fine, otherwise remove the `VerbAttribute` and the command can be:
```
app delete --label some-label    # remove cache verb 
app list
```
>For the Validate function, how would I return the help text if something is missing?

Help is displayed only when --help command is issued or parser errors.
The validation method is not related to the library, but a simple way to apply the validation logic and print messages on the console to show the errors to the user.

You can generate help as a text and show it to the user by creating another instance of parser and call "--help", for details read [wiki](https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration).
