### ISSUE TITLE
Display version info on startup?

### ISSUE THREAD

**Issue by BaconTentacles** [commandlineparser/commandline#592]
Been digging through the wiki as well as general googling, and I haven't found a definitive way to do this, so I figured I'd ask here.  

Is there a way to display the equivalent of the --version flag output, while running normally (instead of just displaying and exiting)?  

I could, of course, pull the info from the assembly and do it manually, but I figured I would try and avoid reinventing the wheel, if at all possible.

**Comment by moh-hassan** [comment]
>Is there a way to display the equivalent of the --version flag output , while running normally (instead of just displaying and exiting)?

yes, you can get it from the API.

An update to wiki is done:
-  [How to Display version information on Application startup?](https://github.com/commandlineparser/commandline/wiki/How-To#q7)
- [How to Display Copyright information on Application startup?](https://github.com/commandlineparser/commandline/wiki/How-To#q8)

You can add this wrapper class to your application:
```cs
class ApplicationInfo
{
   public static string Version   =>HeadingInfo.Default;
   public static string Copyright =>CopyrightInfo.Default;
   public static void ShowIntro()
   {
      Console.WriteLine(Version);
      Console.WriteLine(Copyright);
   }
}
```

**Comment by BaconTentacles** [comment]
Fantastic.  That was exactly what I was looking for.  Thank you very much! 

One of my coworkers was recommending that I switch to using FluentCommandLineParser or some such, but this was so easy to learn and use (only started playing with it yesterday), that I think I will stay right here, thank you very much.
