### ISSUE TITLE
Unit tests fail if terminal window is not exactly 80 characters wide

### ISSUE THREAD

**Issue by rmunn** [commandlineparser/commandline#593]
https://github.com/commandlineparser/commandline/pull/589 adds a check for `sut.Settings.MaximumDisplayWidth.Should().Be(80)`, but that will fail if you run `dotnet test` in a Linux terminal window that's a different size.

### To Reproduce:

1. Clone the repo
1. Open a Linux terminal window and don't resize it, so it's 80x24 (the usual default)
1. Run `dotnet test`. It works.
1. Resize the terminal window so it's one character wider
1. Run `dotnet test`. It fails with "Expected sut.Settings.MaximumDisplayWidth to be 80, but found 81."

Note that on my dev laptop, I habitually run terminal windows at maximum screen width, so for me the exception was "Expected sut.Settings.MaximumDisplayWidth to be 80, but found 272."

### Solution:

Don't assume any particular value for MaximumDisplayWidth; just check that it's greater than 1.

**Comment by rmunn** [comment]
The problem line is [this one](https://github.com/commandlineparser/commandline/blob/19e2c95c68636efaa0d7196c5da1872aa1783592/tests/CommandLine.Tests/Unit/ParserTests.cs#L905), BTW.

**Comment by moh-hassan** [comment]
Thanks @rmunn 
I fixed the issue with a PR .

**Comment by moh-hassan** [comment]
Linux is [added ](https://github.com/commandlineparser/commandline/pull/598) as other CI and all tests passed in [Ubuntu 18.04](https://ci.appveyor.com/project/commandlineparser/commandline/builds/31430440/job/y8rugef5n3xavvi8)

**Comment by rmunn** [comment]
I can verify that #597 fixes this issue on my development laptop.
