### ISSUE TITLE
Verb aliases

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#6]
<a href="https://github.com/kirillkovalenko"><img src="https://avatars0.githubusercontent.com/u/3592194?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kirillkovalenko](https://github.com/kirillkovalenko)**
_Tuesday Aug 20, 2013 at 17:19 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/90_

----

I suggest implementing verb aliases. For example: hg rename, hg move, hg mv is the same command.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Aug 21, 2013 at 05:37 GMT_

----

This can be trivially fixed in the short term by setting `AllowMultiple` to true on the VerbAttribute.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Jul 09, 2015 at 17:40 GMT_

----

@kirillkovalenko, this is a nice idea! :+1: Thansk!

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Thursday Jul 09, 2015 at 17:41 GMT_

----

@nemec, an example?

**Comment by ericnewton76** [comment]
<a href="https://github.com/kirillkovalenko"><img src="https://avatars0.githubusercontent.com/u/3592194?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kirillkovalenko](https://github.com/kirillkovalenko)**
_Friday Jul 10, 2015 at 09:01 GMT_

----

@gsscoder are you really back? the issue is almost 2 y.o. now.

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Friday Jul 10, 2015 at 11:04 GMT_

----

@kirillkovalenko, check the project activity

this is the **state of art** of Command Line Parser Library 2.0.x-alpha: https://github.com/gsscoder/commandline/wiki/Latest-Version

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Friday Jul 10, 2015 at 11:08 GMT_

----

![commandlineactivity](https://cloud.githubusercontent.com/assets/1194228/8617485/97e40134-2704-11e5-9f5d-1407211538dc.png)

![githubactivity](https://cloud.githubusercontent.com/assets/1194228/8617507/be9ff184-2704-11e5-9f47-7db2b395ad0a.png)

**Comment by ericnewton76** [comment]
<a href="https://github.com/kirillkovalenko"><img src="https://avatars0.githubusercontent.com/u/3592194?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kirillkovalenko](https://github.com/kirillkovalenko)**
_Friday Jul 10, 2015 at 13:05 GMT_

----

There could be even more sugar. Many tools allow using a shorter form of a verb or command (e.g. 'hg o' instead of 'hg out') provided that this shorter form is not ambiguous, and if it is ambiguous a nice hint is provided in the error message, e.g. 'hg: command 'a' is ambiguous: add addremove annotate archive'

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Friday Jul 10, 2015 at 15:36 GMT_

----

@kirillkovalenko, this alias is implicit like:

``` csharp
[Verb("add")] class AddOptions { }
[Verb("commit")] class CommitOptions { }
```

Will allow `a`, `c` or explicitly defined:

``` csharp
[Verb("add", Alias=new[] {"a"})] class AddOptions { }
[Verb("commit", Alias=new[] {"cm", "cmt"})] class CommitOptions { }
```

?

**Comment by ericnewton76** [comment]
<a href="https://github.com/rmunn"><img src="https://avatars2.githubusercontent.com/u/90762?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rmunn](https://github.com/rmunn)**
_Thursday Sep 10, 2015 at 08:18 GMT_

----

:+1: from me for this feature. I could use verb aliases in my current project, if they were available.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Friday Sep 18, 2015 at 19:02 GMT_

----

@gsscoder what I meant was allowing the following:

```
[Verb("ci")]
[Verb("commit")] 
class CommitOptions { }
```

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Saturday Sep 26, 2015 at 06:43 GMT_

----

@nemec, it's another vaiable solution... :)

Anyway as announced in #213 this is an _enhancement_ and will be the implementation is in any case post poned after 2.0.\* gains `stable` status.

**Comment by Rohansi** [comment]
Was this issue forgotten? Still doesn't seem to be supported in any way.

**Comment by moh-hassan** [comment]
PR is welcome to support Verb aliases.
