### ISSUE TITLE
Feature for exclusive verbs

### ISSUE THREAD

**Issue by xas** [commandlineparser/commandline#604]
Hi, I'm new with the lib, so maybe my question show some lack of knowledge about how to use it, sorry for that.

What I'm trying to achieve is to be able to create verbs, and set them mutually exclusive.
What I was thinking, was some code like this :

```
public abstract CommonClass {
  [Option]
  public string common {get;set;}
}

[Verb("create"), Unique = true]
public class CreationAction : CommonClass {
}

[Verb("delete"), Unique = true]
public class DeleteAction : CommonClass {
}
```

So I could run my app like :
```
myApp.exe create --common "yes" // No error
myApp.exe delete --common "yes" // No error
myApp.exe create delete --common "no" // error => verbs "create" and "delete" exclusive
```
I don't think I have already saw an issue about it, but I can understand actually it is not possible when I read this [comment](https://github.com/commandlineparser/commandline/issues/291#issuecomment-390055079)

I suppose this kind of features has been already discussed ?

**Comment by rmunn** [comment]
Each command line can have only one verb; that's what the comment you linked to means. In other words, all verbs are already mutually exclusive.

**Comment by xas** [comment]
For what I understand, when you parse, the first _verb class_ found is filled. So in the command
`myApp.exe create delete --common "no"`, the verb _create_ is done, and _delete_ ignored
The same for `myApp.exe delete create --common "no"`, where the verb _delete_ would be done and _create_ ignored.

I was thinking of an option to be able to raise an event, a warning or an error when 2 or more verbs are found when parsing instead of silently take the first one only

**Comment by rmunn** [comment]
What would your desired feature do if a user wanted to create something called `delete`? I.e., if you would normally run "myApp.exe create foo" to create a thing called `foo`, then the natural way to express creating a thing called `delete` would be to run "myApp.exe create delete". I could see maybe adding a warning "Hey, did you mean to use the "delete" verb here?", but making that an error would prevent anyone from creating a thing whose name matched one of your other verbs.

**Comment by xas** [comment]
Closed as resolved (for me)
