### ISSUE TITLE
Making a ValueAttribute optional?

### ISSUE THREAD

**Issue by informedcitizenry** [commandlineparser/commandline#613]
So I'm trying to configure my app to allow something like this:
`myapp file1 file2 file3 -o output`

While also having it allow something like this:
`myapp --config config.json`

My setup looks like this

```
class Options
{
	[Value(0, Required = false)]
	public IEnumerable<string> Inputs { get; set; }
	
	[Option('o', "Output", Required = false)]
	public string Output { get; set; }

	[Option(Required = false)]
	public string Config { get; set; }
}
```

I have success passing arguments of the first type, but for the second the parser throws an exception with the message `Specified argument was out of the range of valid values. (Parameter 'types')`

Is there a configuration I set against the ValueAttribute so the parser will optionally look for the inputs, and if not, proceed with parsing?

**Comment by markusr** [comment]
I have a similar problem.
@informedcitizenry  Did you find a solution?

 My current solution is to use verbs:
 ```myapp files file1.txt file2.txt file3.txt -o output ```
 ```myapp config config.json -o output ```

**Comment by informedcitizenry** [comment]
I didn't find a solution, no. I considered the same solution as you, but was hoping to avoid it.

**Comment by moh-hassan** [comment]
@informedcitizenry 
I test your option class with the two cases and it's working fine without errors.
```cs
var result = Parser.Default.ParseArguments<Options>(args);
```
The error message 'Specified argument was out of the range of valid values. (Parameter 'types')' is not related to your option class because there is no 'types parameter'
