### ISSUE TITLE
Order of commandline parameters parameters

### ISSUE THREAD

**Issue by ajtruckle** [commandlineparser/commandline#614]
Can you please confirm ....

Does it matter what order the user provides the switches / values on the command line?

Thanks.

**Comment by moh-hassan** [comment]
it doesn't matter   what the order the user provides the switches / values 
if v and o are switches and value1 and value2 are values, the next are valid:
```
-v -o value1 value2
value1  -v -o value2
value1 value2  -v -o 
value1 value2  -vo   #merging the switches
```
