### ISSUE TITLE
Display help when no option is specified

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#62]
<a href="https://github.com/nicolasr75"><img src="https://avatars3.githubusercontent.com/u/3595142?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nicolasr75](https://github.com/nicolasr75)**
_Friday Feb 05, 2016 at 14:55 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/286_

----

Using version 2.0:
When the user does not specify any option, I would like to display the same help screen that is automatically shown when the user specifies --help.
I have a very simple program and would like to use as much default behavior as possible. I am using only a few options and this is the code I am using for parsing:

```
var parserResult = Parser.Default.ParseArguments<CommandlineOptions>(args)

if (parserResult.Tag == ParserResultType.Parsed)
{
    CommandlineOptions options = ((Parsed<CommandlineOptions>)parserResult).Value;

    if(options....)
    {

    }
    ...
    else  //no options specified
    {
        Console.WriteLine(CommandLine.Text.HelpText.AutoBuild(parserResult)); //***
    }       
}
```

However, the line marked with **\* does not work because it expects a NotParsed instance. How could I generate the help output?

**Comment by ericnewton76** [comment]
<a href="https://github.com/Mizipzor"><img src="https://avatars1.githubusercontent.com/u/139879?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mizipzor](https://github.com/Mizipzor)**
_Saturday Feb 13, 2016 at 18:22 GMT_

----

Related to #281.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Mar 23, 2016 at 23:47 GMT_

----

@nicolasr75 see the related question for how to do it without needing a parserResult. Let me know if it works for you!

**Comment by ericnewton76** [comment]
<a href="https://github.com/nicolasr75"><img src="https://avatars3.githubusercontent.com/u/3595142?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nicolasr75](https://github.com/nicolasr75)**
_Thursday Mar 24, 2016 at 01:09 GMT_

----

I put your snippet into my code but it does not compile because of 
"TypeInfo does not contain a definition for 'Create'"
Any idea?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Mar 24, 2016 at 02:06 GMT_

----

Upon further investigation, the TypeInfo class is actually a custom (internal) class, not referring to System.Reflection.TypeInfo at all. Sorry, I guess that doesn't work.

**Comment by moh-hassan** [comment]
Closed for age.

**Comment by moh-hassan** [comment]
Wiki with lot of [examples](https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration)
