### ISSUE TITLE
Using CommandLineParser with third party injected command line arguments

### ISSUE THREAD

**Issue by KevinHagen** [commandlineparser/commandline#620]
Hey!

I am currently testing the command line parser and so far it looks like a great tool. However, I have encountered an issue that currently makes it unusable for me.

I am a Unity C# Developer and want to use the parser in order to parse my custom command line arguments for our build pipeline. However, since I work with the Unity-Engine, there are some arguments that I which are provided by the engine. 

Below is an excerpt of my command line arguments.

```Shell
-quit -batchmode -buildTarget ${BuildTargetGroup} -executeMethod THUtils.Editor.BuildPipeline.THBuildPipeline.JenkinsBuildGame --platformTarget ${BuildTarget} --buildTargetGroup ${BuildTargetGroup} --buildConfig ${BuildConfiguration} --revision ${RevisionNumber} --scenes ${SpecificScenes}
```

The following arguments are provided from unity and have to be used that way:

- quit
- batchmode
- buildTarget

It also automatically injects the following arguments:

- projectPath

The other arguments are provided by myself, passed in from a Jenkins job and handled in a options class:

```C#
	public class THBuildOptions
	{
		[Option("buildConfig")] public string BuildConfiguration { get; set; }
		[Option("buildTargetGroup")] public string BuildTargetGroup { get; set; }
		[Option("platformTarget")] public string BuildTarget { get; set; }
		[Option("revision")] public string RevisionNumber { get; set; }
		[Option("scenes")] public IEnumerable<string> SpecificScenes { get; set; }
		
		public override string ToString()
		{
			return $"BuildConfig = {BuildConfiguration}\r\n" +
			       $"BuildTargetGroup = {BuildTargetGroup}\r\n" +
			       $"PlatformTarget = {BuildTarget}\r\n" +
			       $"Revision = {RevisionNumber}\r\n" +
			       $"Scenes = {SpecificScenes}\r\n";
		}
	}
```

Whenever I run this, I receive UnknownOptionError for each argument provided by Unity. Is there a way to ignore these or work around it, so I can still use the parser to parse my arguments?
Also, Unity defines their "long" arguments with a single dash, while the CommandLineParser requires them to be a double dash. Is that a problem?

**Comment by moh-hassan** [comment]
You can add another option in	```THBuildOptions``` class like:
```cs
[Option("Unity")] public string UnityOptions { get; set; }
```

then Pass arguments of Unity as triple quote string, like:
```
# Use tripple quote """
--unity """-quit -batchmode -buildTarget ${BuildTargetGroup} -executeMethod THUtils.Editor.BuildPipeline.THBuildPipeline.JenkinsBuildGame""" --platformTarget ${BuildTarget} --buildTargetGroup ${BuildTargetGroup} --buildConfig ${BuildConfiguration} --revision ${RevisionNumber} --scenes ${SpecificScenes}
```
In this way Unity string pass to parser as one unit quoted string as a fixed value without processing.
Have a  look to this [discussion](https://github.com/commandlineparser/commandline/issues/622)

**Comment by moh-hassan** [comment]
@KevinHagen 
Can you feedback if the suggested solution is working with you or provide yours?

**Comment by KevinHagen** [comment]
@moh-hassan I will implement your suggestion by the end of this week and let you know if this fixes our issues, but it sounds good to me!

**Comment by KevinHagen** [comment]
@moh-hassan So I tried this out yesterday and unfortunately it doesn't work _in our case_.

Usually this seems to be a good solution: It does recognize and parse the options as one, when passed after `--unity`.

However, in conjuntion with unity this doesn't work. Unity can't parse their own arguments anymore if we do it like this. Here is the two different outputs:

With `--unity`
![chrome_OyVKoVJRs2](https://user-images.githubusercontent.com/14986696/81535375-f933eb80-9369-11ea-9df8-001db8f39c14.png)

Without `--unity`
![chrome_GyfI4BdFBo](https://user-images.githubusercontent.com/14986696/81535393-ff29cc80-9369-11ea-9334-7bfb968ec1a4.png)

My current solution is a pretty ugly workaround. The errors thrown always only recognize the first letter because Unity starts their options with a "-" so I decided to put some "ignored options" into our option class like so: 

```csharp
		[Option('p')] public string IgnoreMeP { get; set; }
		[Option('q')] public string IgnoreMeQ { get; set; }
		[Option('b')] public string IgnoreMeB { get; set; }
		[Option('e')] public string IgnoreMeE { get; set; }
```

It works but of course this limits us in our options as well, we can't define a -p option for example now. If there is a better solution I would gladly take it! 

I found the option to configure the parser to ignore unknown arguments, maybe this is a solution?

```csharp 
var parser = new Parser(with => with.IgnoreUnknownArguments = true);
```

If this indeed should ignore the arguments that are not known, then I didn't manage to set it up correctly. 

_**EDIT:**_ It already forced us to change our command line arguments: There is another argument `-buildTarget <name>` that we would like to use, but we can't because then CommandLineParser recognizes this as a duplicate, as `-batchmode` also starts with a _b_ .

Depending on what you'd want to automate, this might be even worse, here is a full list of command line arguments you can use with the Unity Engine:

https://docs.unity3d.com/Manual/CommandLineArguments.html

**Comment by moh-hassan** [comment]
@KevinHagen 
Can you trim quote from Unity option before passing arg to Unity engine
```cs
Unity = Unity.Trim("") // remove quote
```

**Comment by KevinHagen** [comment]
@moh-hassan I'm afraid I can't. 

My build scripts run inside of the Unity Engine (where I have my `THBuildOptions` class) and my build method is called by passing its name as a parameter into the CLI (the `-executeMethod` option). So I can't trim the arguments before they actually invoke reach Unity.

**Comment by moh-hassan** [comment]
@KevinHagen 
**Alternative solution**
As you pass through the arguments directly to Unity Engine, so we can also pass through these arguments to the parser and let the parser ignore the unknown arguments.

```cs
//use custom parser
var parser = new Parser(config =>
			  {
				  config.IgnoreUnknownArguments = true;
			  });			
			var result= parser.ParseArguments<THBuildOptions>(args);
			result.WithParsed(Run);
```
You need not to add option for Unity as we did in the first post (it pass through the argument".
Then pass unity  like:

```
-quit -batchmode -buildTarget ${BuildTargetGroup} -executeMethod THUtils.Editor.BuildPipeline.THBuildPipeline.JenkinsBuildGame --platformTarget ${BuildTarget} --buildTargetGroup ${BuildTargetGroup} --buildConfig ${BuildConfiguration} --revision ${RevisionNumber} --scenes ${SpecificScenes}
```
or single quote for unity option
```
"-quit -batchmode -buildTarget ${BuildTargetGroup} -executeMethod THUtils.Editor.BuildPipeline.THBuildPipeline.JenkinsBuildGame" --platformTarget ${BuildTarget} --buildTargetGroup ${BuildTargetGroup} --buildConfig ${BuildConfiguration} --revision ${RevisionNumber} --scenes ${SpecificScenes}
```
In this way the parser will ignore all unknown arguments(start with one dash and have no corresponding property)

Check this [Demo](https://dotnetfiddle.net/z0Z5xN)

**Comment by KevinHagen** [comment]
@moh-hassan thank you it seems to be working now!
Not sure why I didn't get this running initially, but it seems to be the solution after all.

Thank you for your patience and the helpfulness.
