### ISSUE TITLE
Passing command line arguments as a string argument?

### ISSUE THREAD

**Issue by derekantrican** [commandlineparser/commandline#622]
I'm trying to create a CLI app that calls another CLI app. So I'm passing in arguments like 

```
myapp.exe --secondaryargs "--arg1 test"
```
But whenever I try to parse the arguments it says `Option "arg1" is unknown`.

Is there a proper way to do this?

**Comment by moh-hassan** [comment]
The parser error is caused because the double dash is removed by OS parser and passed to CLP parser without double quote.
**Solution1: use tripple quote**
```
--secondaryargs """--arg1 test"""
or
--secondaryargs "\"--arg1 test\""
```


**Solution2: Use EnableDashDash =true**
 and catch all arguments after dashdash as ```IEnumerable<string>```
Commandline can be:
```
$ --secondaryargs -- --arg1 test
```

```cs
 internal class Options
        {
            [Option("secondaryargs")]           
            public IEnumerable<string> SecondaryArgs { get; set; }
        }
```

**Comment by derekantrican** [comment]
Thanks for those options!

**Comment by derekantrican** [comment]
Couple problems with these solutions. To expand the context of my situation: my CLI app actually serves to compare the results of two other CLI apps. So I actually have something like this:

```
myapp.exe --app1args "--arg1 test" --app2args "--arg1 test --arg2 test2"
```

**Problem with Solution 1:** in the example of `app2args` above, these will actually be encapsulated as `"\"--arg1 test --arg2 test2\""` which means that when the arguments get passed to "app2", they are passed as a single argument and not as individual arguments.

**Problem with Solution 2:** since I have two lists of arguments I need to handle, if I do something like the following:
```
myapp.exe --app1args -- --arg1 test --app2args -- --arg1 test --arg2 test2
```
then all arguments will be interpreted as arguments for "app1".

Do you have any other suggestions? Is it possible to suggest that dashdash could "catch all following arguments in `IEnumerable<string>` *UNTIL* a known argument is reached"?

(My only other thought is that I could use Solution 1 in addition to something like `.Replace("\"", "")` or something like that)

**Comment by moh-hassan** [comment]
> in the example of app2args above, these will actually be encapsulated as "\"--arg1 test --arg2 test2\"" which means that when the arguments get passed to "app2", they are passed as a single argument and not as individual arguments.

You can then split() the argument and get all tokens.

also, for solution2, if you pass all arguments after dash dash, you can take(2) as first cli arguments and then skip (2).take(4) as second cli argument. That is and idea for solution.

**Comment by derekantrican** [comment]
>You can then split() the argument and get all tokens.

Yes, this was similar to my idea of simply calling `.Replace("\"", "")` on the resulting argument string.

>also, for solution2, if you pass all arguments after dash dash, you can take(2) as first cli arguments and then skip (2).take(4) as second cli argument. That is and idea for solution.

Unfortunately, that will only work if I only ever have a set number of arguments for each app (2 & 4). That will not be the case.

Thanks for your help.

**Comment by moh-hassan** [comment]
you can pass arguments like this and redesign options:
```
myapp.exe --app1args arg1=test --app2args arg1=test;arg2=test2    (like docker options  :) )
```
and split the arguments based on = ;  with no quotation

**Comment by derekantrican** [comment]
Ah, yeah - that would be another option
