### ISSUE TITLE
Unparsing FileInfo and DirectoryInfo should add quotes to the path

### ISSUE THREAD

**Issue by kapsiR** [commandlineparser/commandline#626]
`FormatWithQuotesIfString` currently honors `DateTime`, `DateTimeOffset` and `string`, but I'm using `FileInfo` and `DirectoryInfo` as options as well.

These types should also be surrounded by quotation marks when unparsed.

[.NET Fiddle example](https://dotnetfiddle.net/6wwrHH)

Affected code:
https://github.com/commandlineparser/commandline/blob/24e2be23ce695d36316d921d2a52f9eb94cb0558/src/CommandLine/UnParserExtensions.cs#L205-L215

**Comment by moh-hassan** [comment]
To support any object that may be string with spaces, i think `FormatWithQuotesIfString` need to be re-written with minor change as:

```cs
 private static object FormatWithQuotesIfString(object value)
        {
           // if (value is DateTime || value is DateTimeOffset || value is FileInfo || value is DirectoryInfo) return $"\"{value}\"";
            var s = value.ToString();
            if (!string.IsNullOrEmpty(s) && !s.Contains("\"") && s.Contains(" "))
                return $"\"{s}\"";


            Func<string, string> doubQt = v
                => v.Contains("\"") ? v.Replace("\"", "\\\"") : v;

            return s.ToMaybe()
                .MapValueOrDefault(v => v.Contains(' ') || v.Contains("\"")
                    ? "\"".JoinTo(doubQt(v), "\"") : v, value);
        }
```
your test cases are passed using this func.

If you agree, you can modify PR and replace this code.

**Comment by kapsiR** [comment]
@moh-hassan Thanks! I changed the PR accordingly.
I hope there will be no case in the future where the simple `ToString()` will cause issues here 😉

**Comment by moh-hassan** [comment]
@kapsiR 
The method `ToString()` is implemented in base object of every Value Type or Reference type (all inherit from object) and it's override by most of built-in types like:  `DateTime, DateTimeOffset, FileInfo, DirectoryInfo, ...`.
          .

**Comment by kapsiR** [comment]
@moh-hassan Yeah, I'm aware of that and that's the reason why I mentioned it, because we are just looking for a whitespace. 
If there would be anyone who overrides a `ToString()` with a custom implemenation that has a whitespace, it would be treated the same. (maybe unintended)

[EDIT]
Of course, this shouldn't be a real issue here 😀

**Comment by moh-hassan** [comment]
Sure 😄
