### ISSUE TITLE
WithParsed() behaviour - command line vs window task scheduler

### ISSUE THREAD

**Issue by amthog** [commandlineparser/commandline#635]
Hi,

Sorry for the incomplete information in this post. 
I am posting mainly to see if there is anyone else who has experienced similar or an obvious explanation I am missing or possibly I am misunderstanding the WithParsed() method.
Will freely admit could be entirely my fault.
Happy to post more details if required. 

I am using v2.8.0 for some very simple command line parsing. 

Main is as follows:

       static void Main(string[] args)
        {
            Parser.Default.ParseArguments<CommandLineOptions>(args)
                .WithParsed(opts => Execute(opts));
        }

After deployment we found some strange behaviour which took as a while to track down. 
It seems like the number of times our Execute() function is called can vary depending on whether the executable is run from the command line or the windows task scheduler (??!) as follows: 

- Command line, one argument -> Execute called once
- Command line, two arguments -> Execute called once 
- Task scheduler, one argument -> Execute called once 
- Task scheduler, two argument -> Execute called twice (??!! - possibly in two threads ??) 

The last result is completely unexpected and creates problems as our code ends up in an unexpected battle with itself. 
Grateful for any advice. 

cheers

**Comment by moh-hassan** [comment]
It seems that scheduler pass  the argument to the app more than once.
Try to run the  scheduler using  a batch file including the parameters, and don't pass parameters from scheduler.
If you can provide a use case for the job, it help to fix.
**Edit**
Can you provide the option class to look what types you are using and the command with the two arguments.

**Comment by moh-hassan** [comment]
I did a test using a job in window scheduler with 7 arguments and it is working the same as  the executable is runing from the command line.
WithParsed is handling the option class and it's completely independent of the arguments.
If you are using async/await use WithParsedAsync, or  MapResult.
Can you reply on my previous comment.
