### ISSUE TITLE
Help not working for VERBS

### ISSUE THREAD

**Issue by DkAngelito** [commandlineparser/commandline#639]
#633 should not be considered a question but a bug

**Comment by moh-hassan** [comment]
Have a look to [633](https://github.com/commandlineparser/commandline/issues/633#issuecomment-637300934) answer.
Verbs are working fine.

**Comment by DkAngelito** [comment]
Sorry, you are rigth.
But then, the example of the FAQ section of the wiki should be fixed.
(https://dotnetfiddle.net/IbwLbX)
