### ISSUE TITLE
Announcement on Temporary Support Reduction (5)

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#64]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsscoder](https://github.com/gsscoder)**
_Thursday Feb 25, 2016 at 07:38 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/291_

----

My current work commitments prevent me from dealing with open source projects for another month.
Start date: Now
End date: (few day before/after) 1 April 2016

Again,
sorry for the inconvencience. I'm very confident this will be the last and maybe I can back to work on this and other open source projects also soon than said.

Regards,
Giacomo

PS:
I also apoligize for being slow in related and/or other kind of communcation (problems often arose from current commitement and contractual rules). Thanks for patience!

**Comment by ericnewton76** [comment]
<a href="https://github.com/gsscoder"><img src="https://avatars3.githubusercontent.com/u/1194228?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gsscoder](https://github.com/gsscoder)**
_Monday Apr 04, 2016 at 06:08 GMT_

----

Unfortunately to honor contractual commitments, I am forced to extend this period further until the day 5 June 2016.
I'm sorry,
Giacomo

**Comment by kenny-evitt** [comment]
This seems like it can be closed.
