### ISSUE TITLE
Options on Windows 8 doesn't pass through full argument if it contains a comma

### ISSUE THREAD

**Issue by gfs** [commandlineparser/commandline#640]
# Problem

If you specify an argument with a comma in it, on Windows 8 platforms you will only receive the text before the comma. 

## Actual Behavior

Windows 8 has the buggy behavior:

![image](https://user-images.githubusercontent.com/98900/83576444-b1c2fa00-a4e6-11ea-8af0-8b764d8c87e4.png)

## Expected Behavior

Windows 10 exhibits the expected behavior:

![image](https://user-images.githubusercontent.com/98900/83576548-dd45e480-a4e6-11ea-88cd-cfc1d312e42b.png)

## Workaround

Use the `Separator` and `IEnumerable<string>` construction to get all the content that was provided, and if you want an argument that has the commas still in it use `String.Join`.

If you wanted the values that were comma separated (like I did) the "Workaround" is actually better.

## Code Snippet
Here's the code:
```csharp

[Verb("TestOptions", HelpText = "Print out argument options before/after parsing them")]
    public class CommandOptions
    {
        [Option("comma-values", Required = false, HelpText = ", separated list of values")]
        public string CommaSeparatedValues { get; set; }
        [Option("caret-values", Required = false, HelpText = "^ separated list of values")]
        public string CaretSeparatedValues { get; set; }
        [Option("comma-values-list", Separator = ',', Required = false, HelpText = ", separated list of values")]
        public IEnumerable<string> CommaSeparatedValuesList { get; set; }
        [Option("caret-values-list", Separator = '^', Required = false, HelpText = "^ separated list of values")]
        public IEnumerable<string> CaretSeparatedValuesList { get; set; }

    }

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(JsonConvert.SerializeObject(args));
            var argsResult = Parser.Default.ParseArguments<CommandOptions>(args)
                            .MapResult(
                                (CommandOptions opts) => PrintOptions(opts),
                                errs => 1
                            );
        }

        private static object PrintOptions(CommandOptions opts)
        {
            Console.WriteLine("Caret values: " + opts.CaretSeparatedValues);
            Console.WriteLine("Comma values: " + opts.CommaSeparatedValues);
            Console.WriteLine("Caret list values: " + JsonConvert.SerializeObject(opts.CaretSeparatedValuesList));
            Console.WriteLine("Comma list values: " + JsonConvert.SerializeObject(opts.CommaSeparatedValuesList));
            return null;
        }
    }
```

## Repro
I'm attaching a super simple repro solution: 
[CommandLineParserW8Bug.zip](https://github.com/commandlineparser/commandline/files/4720020/CommandLineParserW8Bug.zip)

**Comment by moh-hassan** [comment]
Use quote:
```
testoptions --comma-values "one,two,three"
```
Also, you can use custom type like [here](https://github.com/commandlineparser/commandline/issues/619#issuecomment-636338572)

**Comment by gfs** [comment]
Thank you. That workaround works and the link is great.
