### ISSUE TITLE
How to show enum values in help text

### ISSUE THREAD

**Issue by DkAngelito** [commandlineparser/commandline#643]
I think this is trivial, but I haven't found an easy way to include the enum values in the help text. I found this property `AddEnumValuesToHelpText ` on the Help Class but I don't know how to use it.

Can someone please give an example of how to do this?
Thanks

**Comment by DkAngelito** [comment]
I think I found an example at issue #475 but I think this would be a nice feature to have on the default parser under a setting. I think that the deafult parser is really  basic, and you have to do a lot of things to change a simple behavior that could be achieved with just a param, for example this feature or redirect output to console just to mention a couple. Besides it is not well documented all the advanced posibilities of this library, Just the simplest use cases.

**Comment by DkAngelito** [comment]
I tried almost the exact same example on issue #475 but i'm not getting the help text for verbs. If I set the helpWriter to Console `with.HelpWriter = Console.Out;` I get two helps. The first one with the correct help but without the enum values for the option and the second one with just the list of verbs.
Here is what I got with the following command line
`poller help fetch`

```
poller 1.0.0
Copyright (C) 2020 CommandLine.EnumTest
USAGE:
Fetch CumulationInverterData collection and output to the console:
  poller fetch --collection CumulationInverterData

  -c, --collection    Required. Data collections to retrieve.

  -s, --store         Required. Where to save the data

  --help              Display this help screen.

  --version           Display version information.

poller 1.0.0
Copyright (C) 2020 CommandLine.EnumTest

  fetch      Retrieve data from the Solar API and save the response to a data
             store.

  help       Display more information on a specific command.

  version    Display version information.
```
If my arguments include invalid options I got the real help for the verb, but without the dashes before each option and without the description of the error. Again if I set the parser's HelpWriter to Console.Out I got 2 times the help text, the first one with the description of the error and with the list of options but without the values for the enums, and the second one (generated with the custom helptext) without the error description, without the usage section, and without the dashes as shown:

`poller fetch xyz`

```
poller 1.0.0
Copyright (C) 2020 CommandLine.EnumTest

ERROR(S):
  Required option 'c, collection' is missing.
  Required option 's, store' is missing.
USAGE:
Fetch CumulationInverterData collection and output to the console:
  poller fetch --collection CumulationInverterData

  -c, --collection    Required. Data collections to retrieve.

  -s, --store         Required. Where to save the data

  --help              Display this help screen.

  --version           Display version information.

poller 1.0.0
Copyright (C) 2020 CommandLine.EnumTest
USAGE:
Fetch CumulationInverterData collection and output to the console:
  poller fetch --collection CumulationInverterData

  c, collection    Required. Data collections to retrieve.

  s, store         Required. Where to save the data Valid values: Console, Csv,
                   Mssql

  help             Display more information on a specific command.

  version          Display version information.
```
Expected output:

```
poller 1.0.0
Copyright (C) 2020 CommandLine.EnumTest

ERROR(S):
  Required option 'c, collection' is missing.
  Required option 's, store' is missing.
USAGE:
Fetch CumulationInverterData collection and output to the console:
  poller fetch --collection CumulationInverterData --store Console

  -c, --collection    Required. Data collections to retrieve.

  -s, --store         Required. Where to save the data. Valid values: Console, Csv,
                   Mssql

  --help              Display this help screen.

  --version           Display version information.

```

Is this an issue, or I'm doing something wrong or missing something?

**Comment by moh-hassan** [comment]
Use custom help as described in [wiki](https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration) with `AddEnumValuesToHelpText=true`.

```cs
static void DisplayHelp<T>(ParserResult<T> result)
{
  var helpText = HelpText.AutoBuild(result, h =>
  {
    h.AddEnumValuesToHelpText =true);
    return h;
  });  //without the option e=>e
  Console.WriteLine(helpText);
}
```

**Comment by DkAngelito** [comment]
Thank you very much,

I was using this function.

```
static void DisplayHelp<T>(ParserResult<T> result, IEnumerable<Error> errs)
        {
            var helpText = HelpText.AutoBuild(result, h =>
            {
                h.AddEnumValuesToHelpText = true;
                return h;
            }, e => e, verbsIndex: true);
            Console.WriteLine(helpText);
        }
```

Now that you point to supress the option _`e=>e`_i realize that that was what omitting the errors information (still don't know why) and the verbindex was the property that was taking out the dashes. With your code works perfect for me, but I still insist that that should be a setting of the default parser.
