### ISSUE TITLE
[Question] detect verbs even if passed lowcase?

### ISSUE THREAD

**Issue by Sigurdur42** [commandlineparser/commandline#645]
Hi,
How can I pass a complete lowcase verb but still get it recognized? I want to enable my lazy users to type 

`app.exe checkout` as well as
`app.exe Checkout`

Thx
Michael

**Comment by Jonathan--V** [comment]
Parse the arguments like this: 

`new Parser(with => with.CaseInsensitiveEnumValues = true).ParseArguments<CommandLineOptions>(args)`

**Comment by twaalewijn** [comment]
I believe you can do this by setting `ParserSettings.CaseSensitive` to `false` while creating your `Parser`, like so:

```csharp
new Parser(settings => settings.CaseSensitive = false);
```

Do note that this will disable case sensitivity on option names as well.

**Comment by Sigurdur42** [comment]
Hi,

Thank you very much. This worked.
Cheers
Michael

Gesendet von Mail für Windows 10

Von: Tim Waalewijn
Gesendet: Sonntag, 14. Juni 2020 00:34
An: commandlineparser/commandline
Cc: Sigurdur42; Author
Betreff: Re: [commandlineparser/commandline] [Question] detect verbs even ifpassed lowcase? (#645)

I believe you can do this by setting ParserSettings.CaseSensitive to false while creating your Parser, like so:
new Parser(settings => settings.CaseSensitive = false);
Do note that this wil disable case sensitivity on option names as well.
