### ISSUE TITLE
Upgrading 2.7.82 to 2.8.0

### ISSUE THREAD

**Issue by ajtruckle** [commandlineparser/commandline#647]
I don't know if I am just looking in the wrong place but i can't find any documentation here on GitHub or a detailed Change Log.

Are there code breaking changes between 2.7.82 and 2.8.0? What has changed since 2.7.82?

Thank you.

**Comment by ajtruckle** [comment]
I found the documentation on the [Wiki ](https://github.com/commandlineparser/commandline/wiki)tab. I was looking for an overview readme file.

But I do not see a change log.

**Comment by twaalewijn** [comment]
There is a [CHANGELOG.md](https://github.com/commandlineparser/commandline/blob/master/CHANGELOG.md) markdown file in the root of the project.

I assume you can find what you need in there.
