### ISSUE TITLE
How to catch any verb

### ISSUE THREAD

**Issue by buddhikac96** [commandlineparser/commandline#648]
My command is like this.
`myapp install --config config.yml`

When user enter wrong command (Ex - isntall) I want to print `Unknown command isntall`. 

How I catch this wrong command ? Can I do that by creating a common verb class which can all the commands using something like regex?

**Comment by moh-hassan** [comment]
Parser raise error when verb is unknown.
See [wiki](https://github.com/commandlineparser/commandline/wiki/Verbs) for details.
