### ISSUE TITLE
How to process more than one verb

### ISSUE THREAD

**Issue by buddhikac96** [commandlineparser/commandline#649]
This is how my command looks like.

```app elevate install --installConf install.yml```

Both **install** and **elevate** are commands (verbs). **Install** has options. But elevate hasn't. How I can process both commands.

This is how my Run function should be arranged.

```C#
Run(object obj){
    if(obj is Elevated){
        elevate();
    }

    switch(obj){
        case Install i:
            install(i);
            return;
        case uninstall u:
            uninstall(u);
           return;
    }
}
```

I don't know how to pass more than one verb into Run. How can I do that?

**Comment by moh-hassan** [comment]
You can use only one verb at a time.
Your commandline can't work in this way.
Can you explain what you try to do.
See [wiki](https://github.com/commandlineparser/commandline/wiki/Verbs) for examples.

**Comment by buddhikac96** [comment]
@moh-hassan So is there any recommended way to do this. Is it allowed to feed two commands like `app command1 && command2` ?

**Comment by moh-hassan** [comment]
> Is it allowed to feed two commands like app command1 && command2 ?
 
In windows shell CMD,
1. Execute command2 after execution of command1 has finished, use &
```sh
app install --installConf install.yml  & app elevate
```
2. Execute command2 only if execution of command1 has finished successfully, use &&
```sh
app install --installConf install.yml  && app elevate
```
3.  Execute command2 only if execution of command1 has finished unsuccessfully, use ||
```
app install --installConf install.yml  || app elevate
```
