### ISSUE TITLE
Handle 0 arguments

### ISSUE THREAD

**Issue by buddhikac96** [commandlineparser/commandline#652]
```C#
Parser.Default.ParseArguments(args, types)
                    .WithParsed(RunParsed)
                    .WithNotParsed(HandleErrors);
```

When parser did not get any argument (array of 0 length) it calling `WithNotParsed`. I want to call `WithNotParsed` only if there is any parsing error and when there is no arguments I want to still call `WithParsed`. How can I do that?

**Comment by moh-hassan** [comment]
>when there is no arguments I want to still call WithParsed

As there is no missing required argument, all arguments have their default value and parser success you  still call WithParsed.

**Comment by buddhikac96** [comment]
> > when there is no arguments I want to still call WithParsed
> 
> As there is no missing required argument, all arguments have their default value and parser success you still call WithParsed.

Yeah. But I am talking about a scenario where no verb is called. Lets consider `git` command line. `git commit` will call `WithParsed` with a `commit` object and `git push` will call `WithParsed` with a `push` object. I want to call `WithParsed` when just `git` command called with some `defaul`t object.

**Comment by moh-hassan** [comment]
[Default verb](https://github.com/commandlineparser/commandline/wiki/Verbs#default-verb) may help.

**Comment by buddhikac96** [comment]
Default verb works
