### ISSUE TITLE
Option Has Not Value even with Default Value attribute 

### ISSUE THREAD

**Issue by Chiliyago** [commandlineparser/commandline#656]
I am using an immutable Options class where one of the members is defined as follows:

  ```
[Option(longName: "history",
           shortName: 'h',
           HelpText = Options_History",
           Default = 15,
           ResourceType = typeof(CommandLineOptions.OptionHelpStrings))]
[Value(0, Default=15)]
public int History { get; }

```
I am expecting the default to be 15 but when I run the program as follows I get a parse error saying:
```
App -h
...
ERROR(S):
  Option 'h, history' has no value.

```
Do you think this is a but or I am not configuring this correctly?

**Comment by moh-hassan** [comment]
Be sure that the immutable  Options have a constructor.
See Immutable Options Examples in  [wiki](https://github.com/commandlineparser/commandline/wiki/Immutable-Options-Type)

**Comment by Chiliyago** [comment]
I do have a constructor with arguments in the same order as the properties.  This new 'h' property was added after my Options class was already working successfully.

**Comment by moh-hassan** [comment]
It seems that you add two attributes to the property. That is not supported. Remove ValueAttribute.

**Comment by Chiliyago** [comment]
Even with the removal of the Value Attribute the same error message occurs.  Here is the updated property:

```
[Option(longName: "history",
           shortName: 'h',
           HelpText = "Options_History",
           Default = 15,
           ResourceType = typeof(CommandLineOptions.OptionHelpStrings))]
        public int History { get; }
```

**Comment by moh-hassan** [comment]
Here a test case [demo](https://dotnetfiddle.net/Ea0fCt) to show that Default is applicable.
Is it what you want?

**Comment by Chiliyago** [comment]
I have forked your sample and added more to similar to my implementation please check out: https://dotnetfiddle.net/hDxgME

Notice I am specifying -h in the args which then yields the error.  The desired functionality is that if the user specifies -h with no value then I want 15 to be the default otherwise it would be whatever number the user enters.

**Comment by moh-hassan** [comment]
Args should be`: -h <value>.`
You should add  a value e.g 123, not  blank.
You get the default when you didn't enter -h as I did in my demo.
Read [wiki](https://github.com/commandlineparser/commandline/wiki/Option-Attribute) default value.
