### ISSUE TITLE
How to define mutually exclusive Options set that is Required?

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#67]
<a href="https://github.com/SuperJMN"><img src="https://avatars3.githubusercontent.com/u/3109851?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SuperJMN](https://github.com/SuperJMN)**
_Wednesday Apr 06, 2016 at 12:28 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/299_

----

I have a set of options that the user has to specify (Required), but only of them at a time. Has can this be achieved?

Thanks!

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Thursday Apr 07, 2016 at 15:38 GMT_

----

It's not possible currently. You can mark individual options as required, but not exclusive groups.

**Comment by Good-man** [comment]
I would also like this capability.

**Comment by f-tischler** [comment]
> 
> 
> I would also like this capability.

Me too!

**Comment by moh-hassan** [comment]
Group in v2.7+ is supporting.

**Comment by vargonian** [comment]
Could someone please be a hero and explain how to do this now that it's allegedly supported?  You will save so many people who find this search result from Google and are left hanging.

**Comment by vargonian** [comment]
To answer my own question: It seems that if you use two options with different SetNames, each having Required = true, it will require one and only one of them to be set.
