### ISSUE TITLE
Optional list of strings

### ISSUE THREAD

**Issue by macko1977** [commandlineparser/commandline#671]
Hi,

It might be I'm missing some bits of the spec, or just doing something incorrectly, but i would be deeply grateful if you could tell me how to achieve the behavior I want. And the end result I want to see working can ideally be described with these snippets:
myApp.exe --Option1
myApp.exe --Option1 --List
myApp.exe --Option1 --List *.cs *.docx

For the first case, the List option is not present, thus ignored by my app.
For the second case, the List option is present, but no value is provided, therefore app performs the default operation for that option.
For the third case, the List option is followed by two values, so the app performs the operation for these two.

I thought I could define the option as:

[Option('s', "List", Required = false, Default = null)]
public IEnumerable< string > ListOption { get; set; }

but that does not work for the second case, i.e. it always ends with:

ERROR(S):
  Option 's, List' has no value.

Is my requirement actually feasible? I'm on version 2.8.0.

Any help greatly appreciated.

Best regards
Maciej

**Comment by moh-hassan** [comment]
>For the second case, the List option is present, but no value is provided, therefore app performs the default operation for that option.

No, the parser fire error: `Option 's, List' has no value.`

List option should have value(s) because it's a sequence. see [wiki: CommandLine-Grammar](https://github.com/commandlineparser/commandline/wiki/CommandLine-Grammar) and [default values](https://github.com/commandlineparser/commandline/wiki/Option-Attribute#default)

**Comment by macko1977** [comment]
Hi,

many thanks for your kind answer.

Regarding the default values wiki, that is what I would expect precisely:

When Default is set to null it may be ignored and the default values are set to:
- The IEnumerables are initialized to empty arrays rather than null.

So, in theory, my ListOption would be initialized as empty array, which suits my purposes. The problem, however, is it is not, and the error is shown. What am I doing incorrectly?

Best regards
Maciej

**Comment by moh-hassan** [comment]
Hi @macko1977 ,
For Sequence and scalar tokens:
If you enter the option, you should enter its value(s). Blank values are not allowed.
Example:
```
myApp.exe --Option1 --List    # invalid, because option without value (Blank values) is not allowed. Only bool switches has no value.
myApp.exe --Option1 --List  v1 v2  v3  # valid
myApp.exe --Option1     # valid, no --List option is passed, and ListOption  will be Empty list by default.

```
The ListOption can be:
```cs
//[Option('s', "List", Required = false, Default = null)]
[Option('s', "List", Required = false)]   //remove Default= null  for IEnumerable
public IEnumerable<string> ListOption { get; set; }
```

**Comment by macko1977** [comment]
Hi @moh-hassan 

Thanks. Jumping back to my original query, is there any way to achieve the result I want, i.e.:

myApp.exe --Option1
myApp.exe --Option1 --List
myApp.exe --Option1 --List *.cs *.docx

without introducing any artificial value, that would be recognised as "no value"?

Best regards
Maciej

**Comment by moh-hassan** [comment]
The grammar rules of Sequence and Scalar values is as i described above and is GNU standard.
The "no value" can be done without passing --List in the commandline (it will be default to empty list or no value). 
So omit --list from the commandline in case 2.

**Comment by macko1977** [comment]
I think you missed my point; if I remove --List from the second case, it would mean my application is not supposed to perform an operation related to that option, which wouldn't be different to the case 1. From the use-case point of view, I want to achieve the following scenarios to be feasible with my app:
- no action related to option List
- action for option List
- action for option List with the arguments provided.
The question is if that is feasible - from your answer so far I believe that is not (which, by itself, is perfectly fine, as your package does not need to be tailored to fulfill all possible needs; I just want to confirm if I'm really forced to look for a different solution).

Best regards
Maciej

**Comment by moh-hassan** [comment]
It's not possible to do senario2.

**Comment by macko1977** [comment]
Thanks. I think the current issue may be closed then.

**Comment by moh-hassan** [comment]
Thanks.
