### ISSUE TITLE
Could not parse double.PositiveInfinity ∞

### ISSUE THREAD

**Issue by GF-Huang** [commandlineparser/commandline#673]
![image](https://user-images.githubusercontent.com/4510984/89290208-189d9480-d68b-11ea-86b2-320089cf867b.png)

![image](https://user-images.githubusercontent.com/4510984/89290223-1e937580-d68b-11ea-9130-d1d7f41c625c.png)

![image](https://user-images.githubusercontent.com/4510984/89290452-7500b400-d68b-11ea-906c-66b73591eb67.png)

`∞` can not be parsed.

**Comment by moh-hassan** [comment]
To parse Infinity ∞ , you should use custom parser and set `ParsingCulture`, like 'en-Us':
```cs
var parser = new Parser(with =>
        {          
            //setup culture for parser 'en-US', for example
            with.ParsingCulture = new CultureInfo("en-US"); //modify to use your cultureinfo
        });
var result = parser.ParseArguments<Options>(args);

```
See [demo](https://dotnetfiddle.net/Q1YA6Y)

**Comment by GF-Huang** [comment]
Could I modify the default Parser's `ParsingCulture`? I prefer to use the default one.

**Comment by moh-hassan** [comment]
`CommandLine.Parser.Default` is a singleton uses `CultureInfo.InvariantCulture`, see [wiki: Multi Culture Support](https://github.com/commandlineparser/commandline/wiki/Multi-Culture-Support)

What is your `CultureInfo` name to check if `∞` is supported?

**Comment by GF-Huang** [comment]
I understand. The `∞` is `zh-CN`(Chinese) PositiveInfinity. Thanks.

**Comment by moh-hassan** [comment]
Welcome.
If you want to use `Parser.Default', you can use `Infinity` as a symbol value, e.g.
```
#-e ∞ -m 50 -p -w 0.25  //not supported in Parser.Default
-e Infinity -m 50 -p -w 0.25  # use Infinity instead of  ∞
```

**Comment by GF-Huang** [comment]
Got it. 🌹
