### ISSUE TITLE
Removed where T : new()

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#73]
<a href="https://github.com/CreepyGnome"><img src="https://avatars3.githubusercontent.com/u/935891?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [CreepyGnome](https://github.com/CreepyGnome)**
_Wednesday Jun 15, 2016 at 17:00 GMT_
_Originally opened as https://github.com/gsscoder/commandline/pull/323_

----

Removed where T : new() from the ParseArguments<T> factory method as it
shouldn't be required if convention is followed of only mutable classes
required a default constructor, and immutable classes are supported and
do not have this requirement, so the new() restriction is blocking
immutable classes which should typically not have a default constructor.

This resolves #310

----

_**[CreepyGnome](https://github.com/CreepyGnome)** included the following code: https://github.com/gsscoder/commandline/pull/323/commits_

**Comment by ericnewton76** [comment]
<a href="https://github.com/clmcgrath"><img src="https://avatars2.githubusercontent.com/u/452012?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clmcgrath](https://github.com/clmcgrath)**
_Monday Jul 10, 2017 at 19:40 GMT_

----

can we merge this please been over a year waiting on this fix

**Comment by ericnewton76** [comment]
<a href="https://github.com/ericnewton76"><img src="https://avatars0.githubusercontent.com/u/2211788?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ericnewton76](https://github.com/ericnewton76)**
_Saturday Nov 04, 2017 at 14:37 GMT_

----

Note: We have moved the project to a more team managed repository.  Please resubmit any pull requests to https://github.com/commandlineparser/commandline   Sorry for inconveniences.

**Comment by moh-hassan** [comment]
Resolved
