### ISSUE TITLE
[Question] Is it possible to make the parser ignore certain parameters ?

### ISSUE THREAD

**Issue by fededim** [commandlineparser/commandline#736]
I am using CommandLineParser on a .net core console application. The net core console applications have the possibility to specify the environment by using command line arguments (with option "--environment <ENVIRONMENT>"), the problem is that this argument makes CommandLine.Parser.Default.ParseArguments go into error with "option environment is unknown".

For now I have solved by adding the environment as an option for verbs, yet I was wondering if there is the possibility to tell the parser to ignore some parameters.

**Comment by elgonzo** [comment]
Can you explain the use case? Why would you even want to use an --environment argument if it is not supposed to do anything?

Imo, having a CLI tool silently ignore unknown commandline parameters doesn't sound like a good idea. If --xyz is not listed in the help text of the available commandline parameters, yet a user plonks --xyz as an argument causing no effect whatsoever, it can be quite confusing for the user attempting to understand the commandline interface of such a program...

**Comment by elgonzo** [comment]
Look into the ParserSettings (e.g., through the Parser.Default.Settings property). ParserSettings has a property to set this behavior.

**Comment by fededim** [comment]
I tried with

`CommandLine.Parser.Default.Settings.IgnoreUnknownArguments = true;`

but it gives me this exception

> Error Occured
>       System.InvalidOperationException: Operation is not valid due to the current state of the object.
>          at CommandLine.Infrastructure.PopsicleSetter.Set[T](Boolean consumed, T& field, T value)
>          at CommandLine.ParserSettings.set_IgnoreUnknownArguments(Boolean value)
>          at SincroADR_Batches.Program.Main(String[] args) in C:\Users\dimarco\source\repos\SincroADR\SincroADR_Batches\Program.cs:line 30

Here follows my code

```
      var parsed =CommandLine.Parser.Default.ParseArguments<HashingPlateOptions>(args);
      CommandLine.Parser.Default.Settings.IgnoreUnknownArguments = true;
      await parsed.WithParsedAsync<HashingPlateOptions>(opts => services.GetRequiredService<HashingBatch>().Run());
```

I tried also to set IgnoreUnknownArguments  at the beginning but it always give me the same exception. What can I do ?

**Comment by elgonzo** [comment]
Hmm, i guess it looks like you have to create a new Parser instance instead of using Parser.Default. Sorry for my misleading comment.

Look at the first code sample at https://github.com/commandlineparser/commandline/wiki/Getting-Started

It shows two variations of using a parser. The second variation - creating a parser instance - is probably the right approach for your scenario. Note how the Parser constructor accepts a delegate (in the example given an anonymous method) through which the settings for this parser instance can be modified.

**Comment by fededim** [comment]
Perfect it works, I close the the ticket, thank you.
