### ISSUE TITLE
How to specify exit code?

### ISSUE THREAD

**Issue by LegendaryB** [commandlineparser/commandline#738]
Hey,

I want to use your library for a github action and have the requirement to adjust the exit code. How can I do that? The library returns exit code 0 even in the error case.

Any ideas?

Kind Regards

**Comment by rmunn** [comment]
See https://github.com/commandlineparser/commandline/wiki/Getting-Started#method-2 for an example. Short version is to declare your Main method as `int Main(string[] args)` (or `Task<int> Main` if you're writing an async Main method), and then return 0 from Main if all went well, or a non-0 exit code if something failed (see the linked example for details).

**Comment by LegendaryB** [comment]
I feel a little bit dumb right now :D. Thank you very much. I close this ticket^^
