### ISSUE TITLE
Error setting Default value for Enum? Is Default supported for Enum?

### ISSUE THREAD

**Issue by mthgr** [commandlineparser/commandline#743]
Given the following enum:

    public enum RunningFrom
    {
        CommandLine,
        Task
    }

And the following Options class:

      public class Options
      {
              [Option("runningfrom", Default = "CommandLine" , Required = false, 
              HelpText = "Specify where the task is running from. ")]
              public RunningFrom RunningFrom { get; set; }
      }

Will give this error:
Error setting value to option 'runningfrom': Check if Option or Value
  attribute values are set properly for the given type.

Yet, passing this to the application works: --runningfrom CommandLine

Is this normal...? Or am I missing something here...

**Comment by elgonzo** [comment]
You have specified a string as default value. An enum is not a string...

**Comment by mthgr** [comment]
...
It's funny I could have sworn I tried the enum first and it didn't work... 

But it works. Thanks!
