### ISSUE TITLE
Parse args with option and verb together got error result

### ISSUE THREAD

**Issue by psimla** [commandlineparser/commandline#780]
### OPTION
public class Options
{
        [Option("export", Required = true, HelpText = "Export")]
        public bool Export { get; set; }

}

### VERB
[Verb("export",isDefault:false, HelpText = "Export")]
public class ExportVerb
{
        [Option('s', "source", Required = true, HelpText = "Source")]
        public string Source { get; set; }
}
### PARSING
static void Main(string[] args)
        {
            var parserResult = Parser.Default.ParseArguments<**Options**, **ExportVerb**>(args)
                .WithParsed<**Options**>(opts => { Console.WriteLine("Export: {0}", opts.Export); })
                .WithParsed<**ExportVerb**>((exp) => { Console.WriteLine(exp.Source); })...;
        }

### RUNNING
**ABC.exe --export**

### ERROR
ERROR(S):
  Verb '--export' is not recognized.

  --help       Display this help screen.

  --version    Display version information.

errors 1
Exit code -2

Kindly suggest me. Thank you

**Comment by elgonzo** [comment]
You will have to define a verb name for your `Options` as well, and make that verb the default, as per documentation https://github.com/commandlineparser/commandline/wiki/Verbs#default-verb.

**Comment by psimla** [comment]
> You will have to define a verb name for your `Options` as well, and make that verb the default, as per documentation https://github.com/commandlineparser/commandline/wiki/Verbs#default-verb.

Thank you. It's work!!!
