### ISSUE TITLE
MutuallyExclusiveSet as members of multiple sets, e.g. [Option(SetName = "ftp, www")] public string NewServiceUrl { get; set; }

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#79]
<a href="https://github.com/jochenwezel"><img src="https://avatars0.githubusercontent.com/u/3033827?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jochenwezel](https://github.com/jochenwezel)**
_Wednesday Jul 27, 2016 at 10:04 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/337_

----

The sample of wiki for Mutually Exclusive Options at https://github.com/gsscoder/commandline/wiki/Mutually-Exclusive-Options is already helpful.

But it would be great to be able to define options as members of multiple sets, e.g. 

``` C#
[Option(SetName = "ftp, www")] public string NewServiceUrl { get; set; }
```

which requires NewServiceUrl as argument as soon as other ftp or other www arguments are specified.

(Or is it already implemented but I haven't realized it/the wiki doesn't tell?)

**Comment by moh-hassan** [comment]
Option without SetName can be used in any set.

             [Option()] public string NewServiceUrl { get; set; }
