### ISSUE TITLE
VB.Net 4.8 ParseArguments does not work with Verb Example

### ISSUE THREAD

**Issue by DavidCarter-KDOR** [commandlineparser/commandline#791]
Tried using the example VB.Net code for using verbs on the README.md and keep getting the error on the ParseArguments of Overload resolution failed because no accessible 'ParseArguments' accepts this number of type arguments."  Using .Net framework 4.8. CommandLineParser version 2.8.0.

**Comment by elgonzo** [comment]
I cannot reproduce on dotnetfiddle using CommandLineParser 2.8.0: https://dotnetfiddle.net/AY9J53
Although dotnetfiddle uses .NET framework 4.7.2, i don't believe that the framework version difference 4.7.2 vs. 4.8 would matter here. But then again, i can't be 100% certain of that of course, without having checked with 4.8 (which dotnetfiddle unfortunately does not offer, though).

Thus, i rather suspect you did not use the example code **as-is** but did some alterations you failed to mention in your report. But just to be sure, i would also suggest you try your code with .NET framework 4.7.2 as a build target. If it still fails on 4.7.2, you can be certain that there is something wrong with your code or project / build setup (wrong library version being copied into the build folder, or some such...).
