### ISSUE TITLE
Required flag ignored for Values

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#8]
<a href="https://github.com/attilah"><img src="https://avatars2.githubusercontent.com/u/230432?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [attilah](https://github.com/attilah)**
_Monday Aug 26, 2013 at 21:06 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/93_

----

For this declaration

[Value(0, Required = true)]
public DateTime FromDate { get; set; }

I'm not getting any error, when I don't have any values on the command line.

**Comment by ericnewton76** [comment]
<a href="https://github.com/DrorHarari"><img src="https://avatars3.githubusercontent.com/u/1831901?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DrorHarari](https://github.com/DrorHarari)**
_Wednesday Sep 25, 2013 at 00:42 GMT_

----

Very elegant library

It also ignore required values when the command line is not empty as in:

```
[Verb("noreq")]
public class TestRequired
{
    [Value(0, Required=true)]
    public string val { get; set; }

    [Option('e', "exists")]
    public bool exists { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        args = new string[] { "-e" };
        var rslt = Parser.Default.ParseArguments<TestRequired>(args);
        Console.WriteLine("Is in error: {0}", rslt.Errors.Any());
     }
}
```

It tried to figure it out but the code is a bit abstract and I would appreciate any guidance on how to resolve it:

In the module SpecificationPropertyRules.cs in EnforceRequired() it looks for required options that are not fulfilled using the following code:

```
var options = specProps.Where(sp => sp.Value.IsNothing() && sp.Specification.Required);
```

The IsNothng() check in Maybe.c checks if maybe.Tag == MaybeType.Nothing but the tag value for the value element is actually MaybeType.Just which is why no error is reported. What is this Maybe thing and what does it mean when it is Just? I do not know....

Dror

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Sep 25, 2013 at 00:48 GMT_

----

`Maybe` is a [Monad/Haskellism](http://hackage.haskell.org/packages/archive/base/latest/doc/html/Data-Maybe.html): similar to `Nullable` but works with structs _and_ classes. `Just` is the name for when the "nullable" has a value (`Nothing` is when the "nullable" is null).

Do you know what the value of the `Just` is? An empty string, perhaps?

**Comment by ericnewton76** [comment]
<a href="https://github.com/DrorHarari"><img src="https://avatars3.githubusercontent.com/u/1831901?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DrorHarari](https://github.com/DrorHarari)**
_Wednesday Sep 25, 2013 at 02:30 GMT_

----

Thanks nemec - that is what that Maybe is. Still upon further examination (the code is very LINQ-rich so it is a bit tricky to figure out what happens) I think that the problem is elsewhere -- the specs collection simply does not include the Values only the Options. Still no idea how to change it.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Sep 25, 2013 at 02:37 GMT_

----

I missed before that you're using `Value` rather than `Option`.

Values have Min and Max attributes to specify the minimum and maximum number of parameters it can take. From the documentation on `Min`: if not set, no lower range is enforced. Try adding `Min = 1` instead of `Required = true`.

**Comment by moh-hassan** [comment]
Working in v2.x
