### ISSUE TITLE
Cannot mask password inputs and store string in securestring datatype

### ISSUE THREAD

**Issue by santoshkaranam** [commandlineparser/commandline#812]
Could not find a way to enter masked password (eg *******) by declaring password property as securestring or by specifying option as ResourceType = typeof(SecureString). Password are sensitive information and need to be masked. Using plain text password con console is a risk. 

Please suggest if there is away to mask the password on input

**Comment by elgonzo** [comment]
Wrong library for this job.

This libary is about defining commandline interfaces and parsing the commandline string(s) passed to the program.
The library is not about doing console input/output in your application. The library also cannot replace the shell's prompt, regardless of what shell you are using.

Even if some shell would offer the necessary APIs or configuration mechanisms allowing applications to influence the behavior of the shell prompt in such a manner (side note: i am not aware of any such shell existing), the CommandLineParser library does not have built-in support for such shells (assuming such shells exist).

Also, using the SecureString type is strongly discouraged (see the ["_Remarks_" section in SecureString's documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0#remarks)).

**Comment by santoshkaranam** [comment]
ok I found an alternative here - https://github.com/natemcmaster/CommandLineUtils/blob/main/src/CommandLineUtils/Utilities/Prompt.cs which accepts the passwords masked.
Sure i was looking for a args parser and one which can hide passwords from console. Thanks for reply.
