### ISSUE TITLE
MapResult does not support async

### ISSUE THREAD

**Issue by ghost** [commandlineparser/commandline#822]
If i use async in my application and want to use  Parser.Default.ParseArguments<,>(_args).MapResult(..)
then i need to do

```
.ConfigureAwait(false)
.GetAwaiter()
.GetResult();
```
somewhere.

It would be nice to be able to use async properly even with MapResult.

**Comment by elgonzo** [comment]
It already does. _MapResult_ itself does not need to be async to be able to call async methods. It only needs to forward the _Task_ object returned by the called async method so you can await that task. And that is exactly what _MapResult_ does: it returns whatever value the mapped delegates/lambdas/anonymous functions return, including those values being _Task_ instances returned by async functions.

Therefore, if you need/want async functionality, just let those mapped delegates/lambdas/anonymous functions return _Task_ instances. For example like in this silly demonstration:

```C#
public class Options
{
    [Option('v')]
    public int Value { get; set; }
}

var args = new string[] { "-v", "42" };
var parseResult = CommandLine.Parser.Default.ParseArguments<Options>(args);
var result = await parseResult
    .MapResult(
        async (Options o) => { await Task.Delay(10000); return o.Value; },
        errors => Task.FromResult(-1)
    )
    .ConfigureAwait(false);

Console.WriteLine(result);
```

**Comment by ghost** [comment]
Okay. Thanks for the help!
