### ISSUE TITLE
Ability to use converters and a type factory

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#83]
<a href="https://github.com/robsonfelix"><img src="https://avatars3.githubusercontent.com/u/9100568?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [robsonfelix](https://github.com/robsonfelix)**
_Tuesday Aug 16, 2016 at 04:36 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/343_

----

Giacomo, your library rocks!

I am trying to accommodate some needs we have for a project using the library and I need your help. We successfully added a way to use custom types (classes) as Options property types by changing the TypeConverter class on the MakeType function delegate by adding a try/catch with the constructor. That way we redirected the constructor to some other static factory method that was able to create the value instance.

The other thing we did was to change the ReflectionExtensions class on the SetValue method by adding a way to get the TypeDescriptor for a particular property once the original property.SetValue method failed on setting the property value.

However it looks like adding a Type Factory to the ParserSettings (instead of hardcoding such factory into the TypeConverter class) is too complicated. That would be the ideal scenario.

**Is there anything you suggest we do to make this change easier?**

We believe the changes we did are very good for other developers to use (we created a sort of type-variant class set that can work interchangeably with boolean, integer and other numeric types, text, etc). Hence the need to use other types (rather than struct or base .NET CLR types). As for the changes we did to your code, they can be gladly shared.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Tuesday Aug 23, 2016 at 21:05 GMT_

----

Hi @robsonfelix, if I understand you correctly, you're trying to add the ability for Options/Values to be custom classes with _no_ default constructor?

``` csharp
class Options
{
    [Option('n')]
    public MyClass Nothing { get; set; }
}

class MyClass
{
    public MyClass(int counter)
    {
    }
}
```

The easiest way I can think of is to allow _custom_ `TypeConverter`s to be created and applied to the property. Then you simply check that the converter can convert from `typeof(string)` and let the converter create the new instance (along with populating its data from the option value).

Within the code, you'd have to use reflection to get any `TypeConverterAttributes` attached to the property (_not_ the property Type itself, though you can do that too) and use them to convert the "string value" into a real type.

``` csharp
public class CustomDateTimeOptions
{
    [System.ComponentModel.TypeConverter(typeof(CustomDateTimeConverter))]
    [Option('d', "date", Description = "Store the date.")]
    public DateTime CurrentDate { get; set; }
}
```

You can, of course, do what you're suggesting with an entry in the parser settings, but you'll have to make sure those factories are passed into the inner parts of the code where conversion happens.

**Comment by shmuelie** [comment]
Would a pull request to make `CommandLine.Core.TypeConverter` use `System.ComponentModel.TypeConverterAttribute` on a property be accepted?

**Comment by nemec** [comment]
Doesn't it already (see line 61)? What would you plan to change?

https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/Core/TypeConverter.cs#L52-L63

**Comment by shmuelie** [comment]
@nemec Ah, yes it does, just not in latest release so I hadn't realized. That would solve my issues perfectly then! Guess I'll wait! Thanks

**Comment by ericnewton76** [comment]
So a change you’re waiting on is in the develop branch?

I’m working to try to get a release out relatively quickly. Anything in that develop branch will be part of it. 

E.Newton

**Comment by shmuelie** [comment]
Yup and great!

**Comment by kvalev** [comment]
I dont think this works in the latest version. I tried annotating my option's property, but the converter is not invoked. Instead I had to register it using `TypeDescriptor.AddAttributes()`.
