### ISSUE TITLE
nullable enums

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#84]
<a href="https://github.com/tofutim"><img src="https://avatars0.githubusercontent.com/u/157766?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tofutim](https://github.com/tofutim)**
_Wednesday Aug 17, 2016 at 18:54 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/344_

----

Hi, I have an enum called LoggingLevel

```
    public enum LoggingLevel
    {
        ALL,
        DEBUG,
        INFO,
        WARN,
        ERROR,
        FATAL,
        OFF
    }
```

which gets mapped to an option which is a nullable LoggingLevel

```
        [Option(HelpText = "Console logging level", DefaultValue =LoggingLevel.ALL)]
        public LoggingLevel? ConsoleLevel { get; set; }
```

The effect I want is that if the option is not specified, then ConsoleLevel is null. But when it is specified, but no level is given, then it will be ALL. However, it doesn't really work.

`--consolelevel` gives me null, rather than ALL. Not specifying anything gives me null. If I switch so that ConsoleLevel is not nullable, then the defaultvalue gets set to ALL always.

**Comment by ericnewton76** [comment]
<a href="https://github.com/SuperJMN"><img src="https://avatars3.githubusercontent.com/u/3109851?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SuperJMN](https://github.com/SuperJMN)**
_Sunday Oct 22, 2017 at 16:28 GMT_

----

Sorry, but the an enumerated type, the empty-none-off option should be the very first value in the enum. It should be:

```
 public enum LoggingLevel
    {
        OFF
        DEBUG,
        INFO,
        WARN,
        ERROR,
        FATAL,
        ALL,
    }
```

**Comment by xneg** [comment]
Did you ever get to use nullable enums?
When I tried in a similar way
```
[Option("side", Default = null)]
public OrderSide? Side { get; set; }
```
it just doesn't parse for me when I indicate --side value.

**Comment by moh-hassan** [comment]
nullable enums is working in v2.6.0
