### ISSUE TITLE
Does CommandLineParser support named array option?

### ISSUE THREAD

**Issue by zwcloud** [commandlineparser/commandline#854]
I didn't find any documentation on it and just tried on my own:

https://dotnetfiddle.net/Woe2pX

```C#
// @nuget: CommandLineParser -Version 2.9.1
using System;
using System.Collections.Generic;
using System.Linq;
using CommandLine;

public class Options
{
    [Option('s', "Strings", Required = false)]
    public IEnumerable<string> strs { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        Cmd(new[] { "--Strings", "abc def ghi" });
    }

    public static void Cmd(string[] args)
    {
        var parser = new Parser(with => with.HelpWriter = null);
        var parserResult = parser.ParseArguments<Options>(args);
        parserResult.WithParsed(o =>
        {
            var list = o.strs.ToList();
            for (var i = 0; i < list.Count; i++)
            {
                var str = list[i];
                Console.WriteLine($"{i}: {str}");
            }
        });
    }
}
```
expected result:
```
0: abc
1: def
2: ghi
```
actual result:
```
0: abc def ghi
```

**Comment by zwcloud** [comment]
Just found out the solution:
```C#
Cmd(new[] { "--Strings", "abc", "def", "ghi" });
```

It works as expected.

**Comment by zwcloud** [comment]
There is a very weid behavior of powershell (or cmd.exe but I haven't tested) which caused the misunderstanding.

For example,
```powershell
//(A)
$args = "123 456 789"
MyCSharpApp.exe $args
```
In C# `Main(string args[])`
`args` will contain only one string `"123 456 789"`

But,
```powershell
//(B)
$arg0 = "123"
$arg1="456"
$arg2="789"
MyCSharpApp.exe $arg0 $arg1 $arg2
```
In C# `Main(string args[])`
`args` will contain three string `"123"`, `"456"`, `"789"`.

I did the first (A), which caused `args` to contain one single string with spaces.

**Comment by elgonzo** [comment]
> There is a very weid behavior of powershell (or cmd.exe but I haven't tested) which caused the misunderstanding.

It's standard behavior of Powershell. You provided a single string variable at the call of your MyCSharpApp.exe, which equates 
with a single argument being passed to MyCSharpApp.exe. In other words, `$args = "123 456 789"; MyCSharpApp.exe $args` is equivalent to `MyCSharpApp.exe "123 456 789"`. If you want to keep using Powershell, you gotta get accustomed to it ;-) 

If you want to pass multiple arguments to your program from within Powershell, either use multiple variables (as you did already), or use a Powershell array like:
```
$arguments = "123", "456", "789"
MyCSharpApp.exe $arguments
```

Please close this issue report, as it is not a problem with the library. As author of this issue report, you should see the Close button at the very bottom of the issue report thread here. Thanks!
