### ISSUE TITLE
How can I do variadic arguments?

### ISSUE THREAD

**Issue by justinmchase** [commandlineparser/commandline#858]
Like suppose I want to support the user entering any number of paths:

```
myapp.exe file1.txt file2.txt file3.txt
```

What would my options object look like, if I wanted to get all of those paths into a single `IEnumerable<string> Paths { get; set; }` ?

**Comment by elgonzo** [comment]
Use the [`[Value(positionalIndex)]` attribute](https://github.com/commandlineparser/commandline/wiki/T_CommandLine_ValueAttribute) (in your particular case `[Value(0)]`) on the _Paths_ property.

**Comment by justinmchase** [comment]
Its a little confusing, the 2nd and 3rd arguments are not at position 0. Is it because its an IEnumerable it figures out that all additional arguments are part of the last positional value?
