### ISSUE TITLE
Does this library support arrays?

### ISSUE THREAD

**Issue by siddjain** [commandlineparser/commandline#860]
E.g., if I pass an argument like --foo 1,2

it should parse it as an array [1,2]. i tried this code but doesn't work:

```
// @nuget: CommandLineParser -Version 2.7.82
using System;
using System.Collections.Generic;
using CommandLine;
using System.Linq;


public class Program
{
	public static void Main()
	{
		var text = "-s 1,2,3";
		var args = text.Split();
		var result = CommandLine.Parser.Default.ParseArguments<Options>(args).MapResult((opts) => RunOptionsAndReturnExitCode(opts), //in case parser sucess
 errs => HandleParseError(errs)); //in  case parser fail
		Console.WriteLine("Return code= {0}", result);
	}

	//3)	//In sucess: the main logic to handle the options
	static int RunOptionsAndReturnExitCode(Options o)
	{
		Console.WriteLine("Success");
		var exitCode = 0;
		var props = o.seeds;
		foreach (var seed in props)
			Console.WriteLine("seed= {0}", seed);
		return exitCode;
	}

	//in case of errors or --help or --version
	static int HandleParseError(IEnumerable<Error> errs)
	{
		var result = -2;
		Console.WriteLine("errors {0}", errs.Count());
		foreach (var e in errs)
			Console.WriteLine(e.ToString());
		if (errs.Any(x => x is HelpRequestedError || x is VersionRequestedError))
			result = -1;
		Console.WriteLine("Exit code {0}", result);
		return result;
	}
}

class Options
{
	[Option('s')]
	public IEnumerable<int> seeds
	{
		get;
		set;
	}
}
```

gives following error:

```
ERROR(S):
  Option 's' is defined with a bad format.
```

**Comment by elgonzo** [comment]
> Does this library support arrays?

No, not specifically arrays or other collection types like _List\<T\>_.
`IEnumerable<T>`-typed options/properties (like you did for your _Options.seeds_ property) are fine, though.


> f I pass an argument like `--foo 1,2`

That's not supported by the commandline grammar established by this library. Use `--foo 1 2` instead. (See also here:  https://github.com/commandlineparser/commandline/wiki/CommandLine-Grammar#sequence-option).

If you really want/need to support the comma-separated argument list, you will have to manually handle this, unfortunately. I am not sure how to elegantly handle this (it would be simple enough to use a string option and property and then in the property setter parse the argument string, but i would expect proper error and help output could become quite messy to realize...)

**Comment by siddjain** [comment]
Thanks for the reply. I checked and the space separator works. Fwiw, The Linux practice is to use a comma separator if I am not mistaken.

**Comment by elgonzo** [comment]
Oh wow, that's embarassing. For me. I owe you a big apology.

You can use the comma as a separator for argument values. You just have to set the comma as the separator on the \[Option\] attribute accordingly, like:
```C#
[Option('s', Separator=',')]
public IEnumerable<int> seeds
{
get;
set;
}
```
I did put my trust on the project Wiki alone without checking the actual API documentation of the \[Option\] attribute.

Again, my apologies for misleading you. :-(

**Comment by siddjain** [comment]
Thanks for the correction! Will try it.
