### ISSUE TITLE
Cannot pass constant string array into VerbAttribute

### ISSUE THREAD

**Issue by rombethor** [commandlineparser/commandline#864]
The `VerbAttribute` constructor has the option to pass in `string[] aliases`, however attribute constructors should accept constants when used as attributes and, last I checked, arrays can't be constants.

I suggest using a `params` keyword.

**Comment by elgonzo** [comment]
Wrong, you can use single-dimension string arrays as attribute parameter types/values.

See the specification for allowed attribute parameter types here https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#2124-attribute-parameter-types

>The types of positional and named parameters for an attribute class are limited to the attribute parameter types, which are:
>
> - One of the following types: bool, byte, char, double, float, int, long, sbyte, short, **string**, uint, ulong, ushort.
> - The type object.
> - The type System.Type.
> - Enum types.
> - **Single-dimensional arrays of the above types.**
> - A constructor argument or public field that does not have one of these types, shall not be used as a positional or named parameter in an attribute specification.

<BR> 
Please also close this issue. (Aside from the repro/project maintainers, you as the issue creator have the ability to close it.)

**Comment by rombethor** [comment]
I stand corrected.  However, I will advocate a `params` keyword just because it's neater.
