### ISSUE TITLE
"All rights reserved." is not compatible with MIT licence.

### ISSUE THREAD

**Issue by Pharap** [commandlineparser/commandline#866]
The words "All rights reserved." contradict the MIT licence that the code is published under. The whole point of the MIT licence is that it confers certain rights to the end user, and therefore those rights are _not_ reserved, hence the contradiction.

If the intent is to publish the code under the MIT licence, the words "All rights reserved." should be removed to avoid confusion. If the intent truly is to reserve all rights, the MIT licence shouldn't be used.

See also:
https://opensource.stackexchange.com/a/4403

**Comment by elgonzo** [comment]
> The words "All rights reserved." contradict the MIT licence that the code is published under. 

Incorrect. At worst, "All rights reserved." it's just a redundant statement. But in no way does it contradict any MIT licensing agreement. You should have read the **accepted** answer of that SE question instead.

Please close this issue report here, as it's based on a false premise.

**Comment by Pharap** [comment]
The accepted answer is _incorrect_, the higher voted answer that I linked to is the correct one.

It's a simple contradiction:
* "All rights reserved" claims that the copyright holder retains _all_ rights and confers none.
* The MIT licence explicitly confers rights upon the user.

These cannot both be true. Either the authors reserve _all_ rights or they confer _some_ rights to the user.

The phrase "all rights reserved" is [an obsolete anachronism](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence) anyway, but in this case it's liable to cause confusion as to whether the intent is to reserve all rights or to grant the rights that the MIT licence is supposed to grant.

**Comment by elgonzo** [comment]
> The accepted answer is incorrect, the higher voted answer that I linked to is the correct one.

No, it definitely is not.

> "All rights reserved" claims that the copyright holder retains all rights and confers none.

That's such a ridiculous nonsense, it beggars belief...

"All rights reserved" does not and never did implying that no rights will be confered. How would the entire movie or music industry have been possible if your ridiculous claim would hold any water? The phrase "All rights reserved" is a claim or affirmation (once a legal claim in the past) that one (a person/group/org) is the holder of _all_ rights over a work, and therefore that one is an authority to grant any permissions/right to others with respect to the work.

Why "reseverd", you ask? When you (you as a person/group/org) create a work, who gets the rights to the work? When you create a work, the rights of the work are reserved to you. No one else can demand or claim that they are entitled to the rights to your work. The rights are originally solely reserved to you, the creator of the work That's it. It's then only you who can grant/confer rights to others, nobody else can. (Hypothetically, if _all_ rights are nonexclusively transferred, muliple parties could claim "All rights reserved" over the exact same work. However, in quite a few countries, Copyright is non-transferable or only exclusively transferable, so it's exceedingly difficult to find such a constellation in the wild, so you pretty much only see situations where there is only one party claiming "All rights reserved" over the same piece of work.)

> These cannot both be true.

To the contrary. They definitly can and are both be true.

> Either the authors reserve all rights or they confer some rights to the user.

As i explained above, it's about who is (or claims to be) the rightsholder and who therefore has (or claims to have) the authority to grant (or not grant, entirely upon their whims) rights to the work to others.

> The phrase "all rights reserved" is [an obsolete anachronism](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence) anyway,

Yes, of course it's obsolete without legal merit. But that's not what you based your issue report and claims here on, wasn't it?

> it's liable to cause confusion as to whether the intent is to reserve all rights or to grant the rights that the MIT licence is supposed to grant.

There is no real confusion there. Just a bunch of peeps without any legal background arguing on the internet about things they don't know about but act like they know shit...

Can we stop with the nonsene, please? Please close this issue now.

**Comment by jwdonahue** [comment]
I generally refrain form commenting on this sort of thing because I am not a lawyer, but I work with OSS on a daily basis so I've had a need to maintain some awareness on these matters.  I've been a lurker on the various opensource.org mailing lists for longer than I can remember.  My understanding is that in some jurisdictions, it's legally impossible for a creator to disavow their rights in the created work, but there are some jurisdictions where it's relatively easy to give up some or all rights.  

To the best of my knowledge there's nothing in the OSS cannon that requires a creator surrender their rights upon issuance of a license to other parties.  In the case of the MIT license, this is implicit in [there own guidance](https://opensource.org/license/mit/) where they clearly indicate the license text should contain the copyright notice in the form:

    Copyright <YEAR> <COPYRIGHT HOLDER>

From what I understand, in most if not all countries that enforce copyrights, that wording is tantamount to:

    Copyright <YEAR> <COPYRIGHT HOLDER> All rights reserved.

The additional clause is often used to ensure that rights not explicitly listed in a later licensing grants/agreements, cannot be implied to have been transferred to licensee.  I think there were some historical reasons for this due to how copyrights were enforced, or not, in some jurisdictions, but my understanding is that the shorter form is equivalent to the longer one today.  Depending how well defined a license grant is, there's still room to argue in some jurisdictions whether the grantor of a license surrendered one or more rights in the process, hence the stickiness of the "All rights reserved" phrase. 

I would also point that in some of the organizations I've worked for the past couple decades, the legal departments prohibit adding the year to any copyright boiler plate.  This avoids the need to continuously update the copy right notice as changes are introduced into the work.  For legal purposes, that date is ignored in the face of any physical evidence to the contrary, such as date of publication, RCS history, printouts, etc.

**Comment by Pharap** [comment]
@jwdonahue 

> My understanding is that in some jurisdictions, it's legally impossible for a creator to disavow their rights in the created work

That's correct. Specifically the problem lies with what's known as 'moral rights', which includes things like the right to be properly attributed.

However, that doesn't actually affect most open source licences because most open source licences _require_ the licensee to provide proper attribution by retaining the copyright notice and providing copies of the licence.

What it does affect is attempts to waive one's right to attribution, as one would when attempting to place something in the public domain. Hence the CC0 licence was created to deal with the problem.

See here for more info: https://opensource.stackexchange.com/a/9873

>To the best of my knowledge there's nothing in the OSS cannon that requires a creator surrender their rights upon issuance of a license to other parties.

Exactly. What open source licences do is to _confer_ rights onto others.

_Conferring_ a right does not mean that the creator no longer has that right, it means that all licensees now also hold that same right. Such conferred rights typically include things like the right to copy, modify, or publish a work. (Each of which are separate rights which may be conferred or reserved, hence various Creative Commons licences confer the right to copy a work but not to modify it.)

What I am saying is that stating that a right is 'reserved' effectively implies that it is (exclusively) reserved for the copyright owner, and thus not conferred to others. Hence why I say the reserving of rights is a contradiction to the open source licence's explicit conferring of rights.

I.e. I am saying that one cannot both _reserve_ and _confer_ a right - the two things contradict each other. That one can confer some rights and reserve others, but one cannot reserve _all_ rights and then confer _some_ rights because by conferring _some_ rights not _all_ rights are reserved.

(Reserve: "To keep back; to retain.", "To keep in store for future or special use.")

>I think there were some historical reasons for this due to how copyrights were enforced, or not, in some jurisdictions

The "All rights reserved." is a hangover from [the Buenos Aires Convention](https://en.wikipedia.org/wiki/Buenos_Aires_Convention).

The Buenos Aires Convention applied to precisely 18 countries on the continent of America (and their overseas territories). All of those countries are now members of [the Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention), with the last one joining in 2000, at which "all rights reserved" became entirely obsolete because while the Buenos Aires convention required an explicit reservation of property right, the Berne Convention does not.

>but my understanding is that the shorter form is equivalent to the longer one today.

It's equivalent for publications where all rights are exclusively retained for the creator, but not for when rights are being conferred to other people.

Historically it was uncommon for rights to be conferred to others, especially the sort of rights conferred by open source licences, thus the typical use of "all rights reserved" was with publications where _no_ rights are conferred and where such rights are not intended to be conferred, not for situations where rights were being conferred onto others.

---

See also: https://opensource.stackexchange.com/a/4403

**Comment by elgonzo** [comment]
> What I am saying is that stating that a right is 'reserved' effectively implies that it is (exclusively) reserved for the copyright owner, and thus not conferred to others. Hence why I say the reserving of rights is a contradiction to the open source licence's explicit conferring of rights.

> It's equivalent for publications where all rights are exclusively retained for the creator, but not for when rights are being conferred to other people.

No, it's not. But hey, stick to your fantasies....

You even mention the Berne convention, for crying out loud. Under the Berne convention, basis of modern copyright law, copyright is automatically granted. In other words, all rights are reserved by default, not requiring explicit notice of that anymore. So, by your ridiculous argument, the MIT license (or any other permissible license, for that matter) contradicts the Berne convention and therefore modern copyright law (or vice versa). You are one of the funniest guys i have ever seen on the internet...

**Comment by jwdonahue** [comment]
@Pharap 

>Historically it was uncommon for rights to be conferred to others, especially the sort of rights conferred by open source licences, thus the typical use of "all rights reserved" was with publications where no rights are conferred and where such rights are not intended to be conferred, not for situations where rights were being conferred onto others.

The fact that a book publisher does not go on to issue any license in the published material is not surprising. They do however issues such licenses to other publishers or entities from time to time. Applying your logic, any further licensing of rights in the work would not be valid, as they have already stated in a rather public place that "all rights reserved". But your logic ignores the fact that one of the rights so reserved is the right to license rights in the work.
