### ISSUE TITLE
Can single dash (short name) version be used with collection?

### ISSUE THREAD

**Issue by rgavrilov** [commandlineparser/commandline#867]
I configure an option as:
```
    [Option('a', "assessments", Required = false, Separator = ',')]
    public IEnumerable<int>? AssessmentIds { get; set; }
```

this works as expected with I use long name: `--assessments=1,2,3` but it does not work if I use a short name, e.g. `-a=1,2,3`, however, perhaps accidentally, it does work without an equal sign: `-a1,2,3`.

Is this intentional? I would expect that `--assessments` form and `-a` form would be interchangeable.

**Comment by elgonzo** [comment]
As per the description of the CLI grammar supported by this library(https://github.com/commandlineparser/commandline/wiki/CommandLine-Grammar), it seems only long option names with two dashes (`--optionname`)  support the `=` separator. For short single-letter options either `-o 1,2,3` or `-o1,2,3` should be supported.

(The library basically follows the POSIX argument syntax convention in this respect: https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html)
