### ISSUE TITLE
Is there a way to get the Option parameters to be  used in code?

### ISSUE THREAD

**Issue by metscore** [commandlineparser/commandline#874]
Hi all,

First of all, let me say I really like this package - well done!

Secondly, and I apologize beforehand if this is a noob question, but is there a way for the OptionAttribute to be used in code?
(I have tried to ask Google and looked in the source code, but I don't seem to be smart enough to stitch it together)

For example, if I have something like this

```
    [Verb("sync", false, HelpText = "Synchronize files")]
    internal class SyncOptions
    {
        [Option('n', "nogac", Required = false, HelpText = "Do not run GAC of components", Default = false)]
        public bool NoGac { get; set; }

        [Option('r', "skipreg", Required = false, HelpText = "Skip registration of IVI drivers", Default = false)]
        public bool SkipRegister { get; set; }
    }
```

It would be nice for me to do something like (elsewhere in my code) this pseudo code:
```
   Console.WriteLine("Please use argument \"" + CommandLine.GetOptionLongName(typeof(SyncOptions), nameof(SkipRegister)) + "\"");
```
and have something like this printed on the screen
```
Please use argument "skipreg"
```

If anyone has suggestions how the above could be achieved, it would be appreciated!
Thanks,
Magnus

**Comment by edokan** [comment]
@metscore , you can use [GetCustomAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.attribute.getcustomattribute?view=net-7.0) to get the attribute and use its properties to get what you want.
