### ISSUE TITLE
Argument value missing first two chars on Linux

### ISSUE THREAD

**Issue by gitzko** [commandlineparser/commandline#877]
When I run `./ApiCore/ApiCore -i "/mnt/c/Test.ini" -u -p 9001 -t` I receive this in my app for the `-i` flag: `nt/c/Test.ini`

**Comment by elgonzo** [comment]
Well, first inspect the the content of the `args` string array passed to the _Main_ method. If the respective string value in the _args_ string array is already the incorrect `nt/c/Test.ini`, then there is nothing the CommandlineParser library can do about it.

If however, the values in the `args` string array are correct and intact, you'll have to help us and provide a minimal yet complete code example of how you use the library that reproduces the issue, preferably runnable on [dotnetfiddle.net](https://dotnetfiddle.net/).

**Comment by gitzko** [comment]
Sorry, was working late. We had a '/' to '-' prefix converter for the cmd line switches, this only works on Windows.
