### ISSUE TITLE
Idea of supporting "Execution groups"

### ISSUE THREAD

**Issue by HannesHold** [commandlineparser/commandline#878]
Hi, i had a look at the CommandLineParser and was wondering if it implements something where i can assign options to an execution group.

**What do i understand under **Execution group**?**
An application takes a set of options and depending on the provided options, the actual program execution should differ. - Maybe there is a way to have an implementation using an extension method like .WithNotParsed where we can pass a function for the execution group.

For example we have a console application with the following options:

```
        #region Options

        [Option('g', "gencfg", Required = true, HelpText = "Generate default configuration file", ExecutionGroup = "Alpha")]
        public bool GenerateDefaultConfigFile { get; set; }

        [Option('c', "cfg", Required = true, HelpText = "Configuration file", ExecutionGroup = "Beta")]
        public string ConfigFile { get; set; }

        [Option('l', "lib", Required = true, HelpText = "Library file", ExecutionGroup = "Beta")]
        public string SystemDesignLibraryFile { get; set; }       

        #endregion
```

If the usage is shown, it should show the "Execution groups" with its options.
If i just pass "**--gencfg**" it should execute the **ExecutionGroup: Alpha** directly **without outputting an error that the required options "--cfg" or "--lib" are missing because they are in a different ExecutionGroup**.

An option should be able to be in multiple execution groups too e.g.: ExecutionGroup = "Alpha,Beta".

I tried arround to achieve this with the "SetName" and "Group" attribute properties, but i was not able to get this working. - As far as i understood, the purpose of those attribute properties is a different one.

Question i have is, is this somehow already possible with the CommandLineParser and i just need to figure out how? - If not, do you think it is a good idea to implement such a convenient solution?

Many thanks meanwhile, Hannes

**Comment by elgonzo** [comment]
It seems verbs (also sometimes called commands) are a good fit for your needs: https://github.com/commandlineparser/commandline/wiki/Verbs;  Also note the remarks about the default verb in the documentation i linked to...

**Comment by HannesHold** [comment]
Thanks, that fits what i was looking for. - Really nice.
