### ISSUE TITLE
Cannot pass "true" or "false" to a string option

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#88]
<a href="https://github.com/ptylenda"><img src="https://avatars3.githubusercontent.com/u/11139004?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ptylenda](https://github.com/ptylenda)**
_Tuesday Sep 20, 2016 at 11:30 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/353_

----

Define a string option:

```
[Option('e', "engineering", SetName = "console", Required = false, HelpText = "Flag whether the build is engineering build", ")]
        public string Engineering { get; set; }
```

It is intended to support not only "true" and "false" values and therefore is not boolean (and also not an enum, because it gives us less flexibility)

When you call the executable with "-e true", you receive:

```
Unhandled Exception: System.ArgumentException: Object of type 'System.Boolean' c
annot be converted to type 'System.String'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo
culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo cul
ture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder bi
nder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, Bindi
ngFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, O
bject[] index)
   at CommandLine.Core.ReflectionExtensions.SetValue[T](PropertyInfo property, T
 instance, Object value)
   at CommandLine.Core.ReflectionExtensions.<>c__DisplayClass6_0`1.<SetPropertie
s>b__0(T current, SpecificationProperty specProp)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source
, TAccumulate seed, Func`3 func)
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_2`1.<Build>b__15()
   at CommandLine.Core.InstanceBuilder.<>c__DisplayClass0_0`1.<Build>b__7()
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
```

I think it should be possible to assign ANY text value to a string object, it should not be limited by automatic type recognition.

**Comment by ericnewton76** [comment]
<a href="https://github.com/anthonylangsworth"><img src="https://avatars2.githubusercontent.com/u/1168640?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [anthonylangsworth](https://github.com/anthonylangsworth)**
_Saturday Oct 22, 2016 at 12:01 GMT_

----

This appears to be fixed in the master branch, @ptylenda . I cannot reproduce the issue. Please let me know if I am incorrect.

**Comment by ericnewton76** [comment]
<a href="https://github.com/jdelgado2002"><img src="https://avatars1.githubusercontent.com/u/2649871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdelgado2002](https://github.com/jdelgado2002)**
_Tuesday Oct 10, 2017 at 19:27 GMT_

----

I think I got the boolean logic down @ptylenda , if you include the flag, in your case -e, then it will get mapped to true, excluding it will set it to false.

regardless of what I pass as a parameter I was always getting "true"

**Comment by moh-hassan** [comment]
Nullable  bool is preferd.
