### ISSUE TITLE
Generated help when verb is help does not display the verb list..

### ISSUE THREAD

**Issue by sybaris** [commandlineparser/commandline#884]
**Describe the bug**
When I call my program with the following arguments : "help" or "--help", I expect that all the help was displayed. But the help is partial.

**To Reproduce**
```

    [Verb("Verb1")]
    internal class Verb1
    {
        [Option(Required = true)]
        public string MyOption { get; set; }
    }

    [Verb("Verb2")]
    internal class Verb2
    {
    }

    internal class Program
    {
        static void Main(string[] args)
        {

            var parser = new Parser(config => config.HelpWriter = null);
            var parserResult = parser.ParseArguments<
                Verb1,
                Verb2
            >
            (args);

            parserResult.MapResult(
                 (Verb1 options) => { return 0; },
                 (Verb2 options) => { return 0; },
                 errors => {
                     DisplayHelp(parserResult, errors);
                     return 0; });

            Console.ReadKey();

        }

        static void DisplayHelp<T>(ParserResult<T> result, IEnumerable<Error> errs)
        {


            var helpText = HelpText.AutoBuild(result, h =>
            {
                h.AdditionalNewLineAfterOption = false;
                h.Heading = "Myapp 2.0.0-beta"; //change header
                h.Copyright = "Copyright (c) 2019 Global.com"; //change copyright text
                return HelpText.DefaultParsingErrorsHandler(result, h);
            }, e => e);
            Console.WriteLine(helpText);
        }
    }

```
When I execute this command line : MyApp.exe
The actual result is :
![image](https://user-images.githubusercontent.com/11009997/233297789-950c497e-f669-4174-8914-9793d2de78a0.png)
And it's what I expect.

But when I execute the following command lines : 
- MyApp.exe --help
- MyApp.exe help
I expect the same result as before, but I get :
![image](https://user-images.githubusercontent.com/11009997/233298000-2ea1449e-a336-4e27-9717-218929e39379.png)

I am doing something wrong, or there is an issue ?

**Comment by elgonzo** [comment]
Based on the documentation https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration#custom-help-for-verbs, listing the verbs when invoking without any CLI parameter (e.g., just `MyApp.exe`) seems to be a bug. (Well, even if not, the inconsistency of the two results you observed doesn't seem right in any way.)

Aside from that, based on the same documentation i linked to, to include the verb list in your custom help output your code needs to set the `verbsIndex` parameter of the [HelpText.AutoBuild](https://github.com/commandlineparser/commandline/wiki/M_CommandLine_Text_HelpText_AutoBuild__1) method to `true`, but which your code currently doesn't do.

**Comment by sybaris** [comment]
Thanks for your answer.

> Aside from that, based on the same documentation i linked to, to include the verb list in your custom help output your code needs to set the `verbsIndex` parameter of the [HelpText.AutoBuild](https://github.com/commandlineparser/commandline/wiki/M_CommandLine_Text_HelpText_AutoBuild__1) method to `true`, but which your code currently doesn't do.

I was missing the `verbsIndex` to `true`
That was what i was looking for...

> Based on the documentation https://github.com/commandlineparser/commandline/wiki/HelpText-Configuration#custom-help-for-verbs, listing the verbs when invoking without any CLI parameter (e.g., just `MyApp.exe`) seems to be a bug. (Well, even if not, the inconsistency of the two results you observed doesn't seem right in any way.)

In my case, it doesn't bother me.
