### ISSUE TITLE
verb command with multiple options in version 2.0 

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#90]
<a href="https://github.com/zou-mono"><img src="https://avatars2.githubusercontent.com/u/7379612?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zou-mono](https://github.com/zou-mono)**
_Saturday Oct 08, 2016 at 09:55 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/360_

----

Hello,
In version 2, is there any way to implement the verb command with multiple options? e.g:
    `git tag -a tagname -m 'Tag Description'`

I have tried many ways, but it can support only single option, like `git tag -a tagname` or `git tag -m 'Tag Description'`. If a class is labeled VerbAttribute, and contains two options at least, then it will meet errors during argument parsing as follows:
`Options: 'X' is not compatible with : 'XX'. Options: 'XX' is not compatible with : 'X'.`  
where X and XX are custom options.

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Saturday Nov 05, 2016 at 07:09 GMT_

----

Hi, I cannot reproduce this issue. Does the example below work for you?

``` csharp
[Verb("tag")]
public class Verb
{
    [Option('a')]
    public string Name { get; set; }

    [Option('m')]
    public string Description { get; set; }
}
```

``` csharp
void Main()
{
    var result = CommandLine.Parser.Default.ParseArguments<Verb>("tag -a tagname -m TagDescription".Split());
    result.WithParsed<Verb>(opts => opts.Dump());
    result.WithNotParsed(err => err.Dump());
}
```

**Comment by fortfall** [comment]
Maybe the answer below would help. Try set multiple options with the same SetName or just leave their SetName's undefined.
[https://github.com/commandlineparser/commandline/issues/246#issuecomment-376872194](url)
