### ISSUE TITLE
bool value is not support

### ISSUE THREAD

**Issue by dashenxian** [commandlineparser/commandline#916]
code:
```c#
static void Main(string[] args)
{
	args = new[] {
		 "--y-up-to-z-up", "false",
		 "E:\\0.obj",
		 "E:\\DeskTop\\output1",
		 };
	var result=Parser.Default.ParseArguments<Options>(args);
	result.Value.Dump();
}
public class Options
{
	[Value(0, MetaName = "Input", Required = true, HelpText = "Input OBJ file.")]
	public string Input { get; set; }

	[Value(1, MetaName = "Output", Required = true, HelpText = "Output folder.")]
	public string Output { get; set; }

	[Option('t',"y-up-to-z-up", Required = false, HelpText = "Convert the upward Y-axis ",Default=true)]
	public bool YUpToZUp { get; set; }
}
```
YUpToZUp is not right,and input will be override by YUpToZUp's value
![image](https://github.com/commandlineparser/commandline/assets/18696614/db570d13-52ff-4075-9245-652dbd6b46fb)

**Comment by dashenxian** [comment]
if YUpToZUp is bool? type,it will be right;
```diff
     [Option('t',"y-up-to-z-up", Required = false, HelpText = "Convert the upward Y-axis ",Default=true)]
--   public bool YUpToZUp { get; set; }
++   public bool? YUpToZUp { get; set; }
```
![image](https://github.com/commandlineparser/commandline/assets/18696614/00f1cf28-69c0-45bc-8402-5f1968889285)

**Comment by VewDev** [comment]
`bool` parameters are a `Switch Option`. If the option is passed to the command line, it will always be `true`.

For your desired behavior (being able to pass it and set it to `false`) you need to declare it as a `bool?`.

For documentation about this, see:

https://github.com/commandlineparser/commandline/wiki/CommandLine-Grammar#switch-option

**Comment by dashenxian** [comment]
> `bool` parameters are a `Switch Option`. If the option is passed to the command line, it will always be `true`.
> 
> For your desired behavior (being able to pass it and set it to `false`) you need to declare it as a `bool?`.
> 
> For documentation about this, see:
> 
> https://github.com/commandlineparser/commandline/wiki/CommandLine-Grammar#switch-option

Thanks
