### ISSUE TITLE
Add UseDoubleQuoteOnArguments to UnParserSettings

### ISSUE THREAD

**Issue by ericnewton76** [commandlineparser/commandline#95]
<a href="https://github.com/lukefan6"><img src="https://avatars3.githubusercontent.com/u/8968212?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lukefan6](https://github.com/lukefan6)**
_Monday Nov 07, 2016 at 15:11 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/371_

----

Consider following scenario:

```
	public class ScaffoldCommand
	{
		[Value(0)]
		public string ConnectionString { get; set; }
                [Value(1)]
		public string Provider { get; set; }
        }
```

ConnectionString could be a long string that contains spaces and we usually surround them with double quotes so the CLI could recognize it, take entity framework core for example:

> dotnet ef dbcontext scaffold "Data Source = xxxxxx;Database = xxxxxx; User ID=xxxxxx; Password=xxxxxx" Microsoft.EntityFrameworkCore.SqlServer

Currently `public static string FormatCommandLine<T>(this Parser parser, T options, Action<UnParserSettings> configuration);` does not seem to have this kind of capability, I can only generate arguments **without** double quotes.

I wonder if we could add something like `UseDoubleQuoteOnArguments` to `UnParserSettings` so we could configure it to generate arguments surrounded by double quotes.

Any thoughts?

**Comment by ericnewton76** [comment]
<a href="https://github.com/nemec"><img src="https://avatars3.githubusercontent.com/u/136378?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nemec](https://github.com/nemec)**
_Wednesday Nov 09, 2016 at 18:38 GMT_

----

IMO that should be a default feature . Can you think of a reason why anyone would want to turn it off, assuming quotes are only added if there is whitespace in the value?

**Comment by ericnewton76** [comment]
<a href="https://github.com/lukefan6"><img src="https://avatars3.githubusercontent.com/u/8968212?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lukefan6](https://github.com/lukefan6)**
_Thursday Nov 10, 2016 at 02:09 GMT_

----

Actually adding quotes only when there is whitespace would be better. I was not thinking straight lol.

**Comment by ericnewton76** [comment]
<a href="https://github.com/jehrenzweig"><img src="https://avatars2.githubusercontent.com/u/6299333?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jehrenzweig](https://github.com/jehrenzweig)**
_Thursday Feb 02, 2017 at 17:13 GMT_

----

I desperately wanted this feature 1-2 years ago, and for the same reason: it was much more convenient to supply values such as connection strings by wrapping them in double-quotes.  It would be great to see CLP support passing values in this way.

**Comment by moh-hassan** [comment]
Resolved
